import { SeedOpportunity } from "./seed-types";

/**
 * NEW scholarships — added specifically to pair with the new ≤$30 university entries,
 * so students can see "apply to the university AND the scholarship" together.
 */
export const EXTRA_SCHOLARSHIPS: SeedOpportunity[] = [
  {
    name: "University of Helsinki Scholarship (100% Tuition Waiver)",
    slug: "helsinki-scholarship",
    kind: "SCHOLARSHIP",
    provider: "University of Helsinki",
    country: "Finland",
    countryCode: "fi",
    continent: "Europe",
    city: "Helsinki",
    lat: 60.205,
    lng: 24.962,
    levels: ["masters"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed free — the scholarship option is embedded inside the (already free) admission application.",
    related: ["university-helsinki", "aalto-university"],
    fundingType: "PARTIAL",
    fundingNote: "Covers 100% (or 50%) of the non-EU tuition fee for the full 2-year degree. No living stipend — combine with residence-permit savings or part-time work rights (25h/week).",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 14,
    cycleNote: "Same window as admission: ~1 Dec – 14 Jan. Scholarship decisions arrive with admission results (Mar–Apr).",
    moiAccepted: false,
    moiNote: "Admission needs IELTS 6.5 / TOEFL 92 — MOI waivers rare at Helsinki.",
    englishTests: "IELTS 6.5 (min 6.0/band) / TOEFL iBT 92.",
    localLanguageRequired: false,
    localLanguageNote: "English master's need no Finnish.",
    recommendationsRequired: false,
    recommendationsNote: "No separate letters for the scholarship — your admission file is the application.",
    unofficialTranscripts: true,
    transcriptsNote: "Same scans as the admission application.",
    essayRequired: true,
    essayNote: "The admission motivation letter doubles as the scholarship statement.",
    applicationSteps: [
      { title: "Choose Helsinki master's programmes on Studyinfo.fi", detail: "Check each programme accepts the scholarship (nearly all do)." },
      { title: "File ONE free admission application", detail: "List programme preferences; the whole application costs €0." },
      { title: "Tick 'I wish to be considered for the scholarship'", detail: "It's a checkbox inside the same form — many applicants miss it." },
      { title: "Upload a strong motivation letter + scans by 14 Jan", detail: "Scholarship ranking reuses your admission documents — the letter carries the merit argument." },
      { title: "Await results (Mar–Apr)", detail: "100% or 50% waiver appears on your tuition invoice if selected; accept within the deadline." },
    ],
    requirementsSummary: "Free application, checkbox opt-in, merit-based tuition waiver of 100%/50%.",
    eligibilityNote: "Admitted non-EU/EEA fee-paying students; awarded strictly on academic merit.",
    officialUrl: "https://www.helsinki.fi/en/admissions-and-education/scholarship",
    competitiveNote: "100% waivers limited; 50% more common. Pair with Aalto's equivalent scholarship as a backup.",
    successTips: "Apply on the first day of the December window — Helsinki files are reviewed competitively but early, complete files avoid the January document-rush pile where good applications fail on technicalities.",
  },
  {
    name: "Mastercard Foundation Scholars Program (Ashesi & partners)",
    slug: "mcf-scholars",
    kind: "SCHOLARSHIP",
    provider: "Mastercard Foundation",
    country: "Ghana",
    countryCode: "gh",
    continent: "Africa",
    city: "Berekuso (Ashesi)",
    lat: 5.703,
    lng: -0.152,
    levels: ["undergraduate", "masters"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed free — the program application itself costs nothing at African partner universities.",
    related: ["ashesi-mcf"],
    fundingType: "FULLY_FUNDED",
    fundingNote: "Comprehensive: tuition, housing, meals, books, stipend, laptop, travel. Partners include Ashesi (Ghana), ALU, USIU-Africa, plus international routes (Edinburgh, Toronto, McGill, UBC, Berkeley, ASU, Michigan State, EARTH).",
    opensMonth: 9,
    opensDay: 1,
    closesMonth: 3,
    closesDay: 31,
    cycleNote: "Each partner sets its own window (Sep–Mar typical). Ashesi's MCF Scholars round closes ~March for September intake.",
    moiAccepted: true,
    moiNote: "African partners (Ashesi etc.) accept WASSCE/WAEC English — no IELTS for Ghanaians. North American partners may still require TOEFL/IELTS.",
    englishTests: "Not needed at African partners; varies for international partner routes.",
    localLanguageRequired: false,
    localLanguageNote: "English medium.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Teacher + community/religious leader recommendations emphasizing leadership and service.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned WASSCE results slip + school reports accepted initially.",
    essayRequired: true,
    essayNote: "Leadership, give-back and community-impact essays are the heart of the selection.",
    applicationSteps: [
      { title: "Pick your partner university route", detail: "Ghanaian students usually start with Ashesi's MCF Scholars page; international partner routes (Toronto/UBC/etc.) run through those universities' admissions." },
      { title: "Apply to the university first (free at Ashesi for MCF applicants)", detail: "Ashesi waives the application fee for MCF-track applicants from low-income backgrounds — state it in the form." },
      { title: "Write the give-back story, not the hero story", detail: "Selection screens for financial need + leadership + intent to transform communities. Be specific: what you built, led, fixed." },
      { title: "Collect 2 grounded recommendations", detail: "A teacher who saw you lead + a community figure who can vouch for need and character beat generic big-shots." },
      { title: "Prepare for the interview + home-visit", detail: "Shortlisted candidates interview (sometimes family financial-need verification). Answer honestly — the program verifies." },
    ],
    requirementsSummary: "Free application, full-ride funding, WASSCE-friendly, need + leadership based.",
    eligibilityNote: "Academically strong, economically disadvantaged young Africans; Ghana is the flagship partner country.",
    officialUrl: "https://mastercardfdn.org/all/scholars/",
    competitiveNote: "Very competitive at international partners; Ashesi route has the largest seats for Ghanaians.",
    successTips: "Start with Ashesi — it's in Ghana, costs nothing to apply, and the MCF package there is identical in generosity. Apply in October–November, months before the March close.",
  },
  {
    name: "Common App Fee Waiver (NACAC) — Make US Applications $0",
    slug: "common-app-waiver",
    kind: "SCHOLARSHIP",
    provider: "Common App / NACAC",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "All US colleges",
    lat: 39.5,
    lng: -98.35,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed free — this IS the fee waiver: it turns the $60–90 application fee into $0 at 1,000+ US colleges.",
    related: ["smith-college", "wellesley-college", "bowdoin-college", "carleton-college", "colby-college", "reed-college", "berea-college"],
    fundingType: "PARTIAL",
    fundingNote: "Not a scholarship — it removes application costs. Pair it with each college's need-based financial aid (several meet 100% of demonstrated need: Smith, Wellesley, Bowdoin, Colby...).",
    rolling: true,
    cycleNote: "Available whenever Common App is open (Aug 1 – college deadlines). No separate deadline — request it inside each application.",
    moiAccepted: false,
    moiNote: "English tests depend on each college; many waive for English-medium schooling.",
    englishTests: "College-specific; TOEFL/IELTS/Duolingo accepted at most, waived often.",
    localLanguageRequired: false,
    localLanguageNote: "English medium.",
    recommendationsRequired: false,
    recommendationsNote: "No new letters — your counselor confirms the waiver request (the counselor recommendation is already standard at US colleges).",
    unofficialTranscripts: true,
    transcriptsNote: "Self-reported grades + uploaded scans accepted by many Common App colleges initially.",
    essayRequired: true,
    essayNote: "Common App personal essay (650 words) — write once, send everywhere.",
    applicationSteps: [
      { title: "Create your Common App account (free)", detail: "commonapp.org — add your colleges; the fee shows as payable until the waiver is granted." },
      { title: "Open the fee-waiver section in Profile", detail: "Confirm you meet one NACAC criterion: public assistance, orphan/ward status, housing support, counselor-confirmed financial hardship (international students qualify through this last one)." },
      { title: "Ask your school counselor to verify", detail: "Your counselor (or head of school in Ghana) clicks the verification — no fee, no documents upload needed." },
      { title: "Watch the fee flip to $0 everywhere", detail: "Once granted, the fee is waived at EVERY Common App college you add — apply to 8–10 schools freely." },
      { title: "Stack need-based aid applications", detail: "Submit CSS Profile / college aid forms; schools like the $0-fee colleges in this database can meet full need — making attendance cost less than a visa fee." },
    ],
    requirementsSummary: "Counselor-confirmed hardship = $0 at 1,000+ colleges; one essay, unlimited applications.",
    eligibilityNote: "International students qualify via counselor confirmation of financial need — you do NOT need US residency.",
    officialUrl: "https://www.commonapp.org/apply/first-time-students",
    competitiveNote: "The waiver is need-based, not merit — nearly every low-income applicant gets it.",
    successTips: "Ghanaians: this waiver + the $0-fee colleges in our database is how students with $0 budget apply to America. Ask your counselor FIRST so the waiver clears before deadlines.",
  },
  {
    name: "Malaysia International Scholarship (MIS)",
    slug: "mis-malaysia",
    kind: "SCHOLARSHIP",
    provider: "Ministry of Higher Education Malaysia",
    country: "Malaysia",
    countryCode: "my",
    continent: "Asia",
    city: "Kuala Lumpur",
    lat: 3.14,
    lng: 101.687,
    levels: ["masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed free — MIS applications carry no fee.",
    related: ["universiti-malaya", "usm-malaysia"],
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + RM 3,500/month living allowance + annual grant for books/conference. Tenable at UM, USM, UPM, UKM, UTM, UMP, UniMAP and other public universities.",
    opensMonth: 3,
    opensDay: 15,
    closesMonth: 5,
    closesDay: 31,
    cycleNote: "Annual round typically opens ~mid-Mar – end May. Prepare admission applications to host universities FIRST — MIS requires an offer letter for the final stage.",
    moiAccepted: true,
    moiNote: "Host universities accept MOI letters — Ghanaians with English-medium degrees routinely skip IELTS for MIS host institutions.",
    englishTests: "IELTS 5.5+ / TOEFL recommended, or MOI letter accepted by host universities.",
    localLanguageRequired: false,
    localLanguageNote: "English medium programmes.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two referee reports in the MIS online form.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scans; certified copies at acceptance.",
    essayRequired: true,
    essayNote: "Research proposal / study plan is central for postgraduate MIS.",
    applicationSteps: [
      { title: "Secure admission at an MIS host university first", detail: "Apply to UM/USM/UTM etc. (RM 50–100 fees) — MIS applicants need the offer." },
      { title: "Watch hitsem.moe.gov.my for the March window", detail: "MIS portal opens ~mid-Mar; prepare documents in Feb." },
      { title: "Upload: offer letter, transcripts, 2 references, proposal", detail: "Scans sufficient at application." },
      { title: "Interview stage (some years)", detail: "Be ready to defend your research plan and your reasons for Malaysia." },
      { title: "Award + student pass", detail: "MIS award letter + university support → EMGS visa process; stipend starts on arrival." },
    ],
    requirementsSummary: "Free to apply, needs a host offer first, full tuition + RM 3,500/month.",
    eligibilityNote: "Open to internationals incl. Ghana; master's applicants usually under 40 with a good bachelor's; PhD needs a proposal.",
    officialUrl: "https://biasiswa.moe.gov.my/MIS/",
    competitiveNote: "Moderate — far less saturated than UK/US awards; strong proposals win.",
    successTips: "Apply for UM (RM 100) AND USM (RM 50) admission in December–January, then submit MIS in March with whichever offer arrives first. Total spend to a full ride: under $25.",
  },
  {
    name: "MTCP Scholarship (Malaysia Technical Cooperation Programme)",
    slug: "mtcp",
    kind: "SCHOLARSHIP",
    provider: "Ministry of Foreign Affairs Malaysia",
    country: "Malaysia",
    countryCode: "my",
    continent: "Asia",
    city: "Putrajaya",
    lat: 2.94,
    lng: 101.69,
    levels: ["masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed free — no application fee for MTCP.",
    related: ["universiti-malaya", "usm-malaysia"],
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + RM 3,500/month allowance for postgraduate study at Malaysian public universities. Priority fields include engineering, science, agriculture, economy, ICT.",
    opensMonth: 2,
    opensDay: 15,
    closesMonth: 5,
    closesDay: 31,
    cycleNote: "Window typically ~mid-Feb – end May annually. Like MIS, you need a host-university admission offer.",
    moiAccepted: true,
    moiNote: "English-medium background (MOI letter) accepted by host universities in lieu of IELTS for many programmes.",
    englishTests: "IELTS/TOEFL recommended or MOI letter via host university.",
    localLanguageRequired: false,
    localLanguageNote: "English medium.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Referee reports + sometimes employer endorsement.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans at application.",
    essayRequired: true,
    essayNote: "Study plan + how your field serves development cooperation.",
    applicationSteps: [
      { title: "Confirm Ghana eligibility", detail: "MTCP targets developing countries — Ghana qualifies (Commonwealth + OIC + bilateral programmes list)." },
      { title: "Get your Malaysian university admission first", detail: "Same strategy as MIS: UM/USM/UTM offers (RM 50–100 application fees)." },
      { title: "Apply in the Feb–May window via the MTCP portal", detail: "Upload offer letter, transcripts, references, study plan." },
      { title: "Frame your field around development impact", detail: "MTCP is a foreign-aid instrument — 'water engineering for West Africa' beats generic career talk." },
      { title: "Award → visa → fly", detail: "Allowance + tuition handled; Malaysian High Commission in Accra processes the student visa." },
    ],
    requirementsSummary: "Free application, full funding, needs host offer, development-impact framing.",
    eligibilityNote: "Citizens of MTCP-recipient developing countries (Ghana included); under 40 for master's typically.",
    officialUrl: "https://www.kln.gov.my/web/guest/mtcp",
    competitiveNote: "Less known than MIS — fewer applicants per seat.",
    successTips: "Apply to BOTH MIS and MTCP in the same March–May season with the same host offer — double the chances on one admission letter, all application costs still under $25.",
  },
];
