import { SeedOpportunity } from "./seed-types";

// ─── Americas, Africa, Oceania ───────────────────────────────────────────────
export const AMERICAS_AFRICA_OCEANIA_SEED: SeedOpportunity[] = [
  {
    name: "Fulbright Foreign Student Program (Ghana)",
    kind: "SCHOLARSHIP",
    provider: "U.S. Department of State — via U.S. Embassy Accra",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Washington, D.C.",
    lat: 38.8951,
    lng: -77.0364,
    levels: ["masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — the Fulbright application is free in every participating country.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition at the placed U.S. university + monthly stipend + round-trip international airfare + health benefits (ASPE) + pre-academic and enrichment programs.",
    opensMonth: 2,
    opensDay: 1,
    closesMonth: 5,
    closesDay: 31,
    cycleNote: "Ghana's window typically runs February-May — confirm exact dates with US Embassy Accra / Ghana Fulbright announcements each January.",
    moiAccepted: false,
    moiNote: "US J-1 placements almost always require TOEFL/IELTS eventually; a few institutions accept MOI but plan to take TOEFL (~90+) if shortlisted. Tests can be scheduled after the interview stage in many cycles.",
    englishTests: "TOEFL iBT 90+/IELTS 7.0 usually required before placement (can follow the initial application in many country cycles).",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 3,
    recommendationsNote: "Three recommendation letters (academic/professional mix) submitted through the online system.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts at application; certified copies if you progress.",
    essayRequired: true,
    essayNote: "A study/research objective (~1 page) + a personal statement (~1 page) — the core of the review.",
    applicationSteps: [
      { title: "Confirm Ghana's annual window (Jan)", detail: "Watch the US Embassy Accra and Fulbright Ghana pages; the country office publishes exact fields (some years exclude medicine/clinical fields)." },
      { title: "Draft the two essays (Jan-Feb)", detail: "Study objective: precise, Ghana-anchored problem + US program fit. Personal statement: your story and return commitment." },
      { title: "Apply free before the deadline (Feb-May)", detail: "Via the Fulbright foreign student portal — scans + 3 referees. No fee, no test scores initially in most cycles." },
      { title: "National screening & interview (Jun-Aug)", detail: "The US Embassy in Accra reviews and interviews shortlisted candidates." },
      { title: "IIE placement & TOEFL (Sep-Feb)", detail: "If nominated, IIE places you at US universities; you take TOEFL/IELTS and GRE/GMAT if the field requires during placement." },
      { title: "J-1 visa & departure (Jul-Aug)", detail: "2-year home residency requirement applies — plan your Ghana return." },
    ],
    requirementsSummary: "Free application, 3 references, 2 essays, scans. TOEFL comes later at placement. Return-home rule for 2 years.",
    eligibilityNote: "Ghanaian citizens with bachelor's; strong academic/professional record; return commitment.",
    officialUrl: "https://foreign.fulbrightonline.org/",
    competitiveNote: "Ghana nominates a small cohort yearly — a polished essay set matters more than famous university brands.",
    successTips: "Show an explicit Ghana-return plan with named institutions/sectors — Fulbright's mission is mutual understanding through return.",
  },
  {
    name: "Joint Japan/World Bank Graduate Scholarship (JJ/WBGSP)",
    kind: "SCHOLARSHIP",
    provider: "World Bank + Government of Japan",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Washington, D.C.",
    lat: 38.9101,
    lng: -77.0147,
    levels: ["masters"],
    fields: ["development studies", "public policy", "business & economics", "environment", "energy", "medicine & health", "agriculture & food"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee for the scholarship.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition at 50+ preferred programs (Harvard Kennedy, Columbia SIPA, Carnegie Mellon, UChicago, UPenn, Cornell, plus Japan & Africa programs) + monthly living stipend + round-trip economy airfare + health insurance.",
    opensMonth: 2,
    opensDay: 28,
    closesMonth: 6,
    closesDay: 30,
    cycleNote: "Two application windows yearly: ~Feb 28-Apr and ~May-Jun — check the World Bank page for current windows.",
    moiAccepted: true,
    moiNote: "Language rules follow the host program; many preferred programs accept English-medium degrees (MOI) — program-specific.",
    englishTests: "Per host program; MOI accepted by several preferred programs.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two professional/academic references (one should speak to your development work).",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts/certificates uploaded to the application.",
    essayRequired: true,
    essayNote: "Development-focused statements: your contribution to development in Ghana after the degree.",
    applicationSteps: [
      { title: "Meet the core criteria", detail: "Ghanaian citizen + bachelor's earned ≥3 years ago + 3+ years of development-related professional experience + currently NOT working for World Bank Group or IMF + admission offer from a preferred program (or apply in parallel)." },
      { title: "Choose preferred programs", detail: "The published list spans US, Europe, Japan, and Africa (incl. African Development University). Programs like CMU Heinz, UChicago Harris, Cornell Dyson regularly admit JJ/WBGSP scholars." },
      { title: "Apply in the open window (free)", detail: "Online: scans, 2 references, development statements. Application is scored on professional experience + essay quality." },
      { title: "Committee review (6-10 weeks)", detail: "Scholarship committee scores and awards within each window." },
      { title: "Award & enrollment", detail: "Funds flow through the university; stipend setup at arrival." },
    ],
    requirementsSummary: "3 yrs development experience + bachelor's ≥3 yrs old + free application + 2 references. Full ride at 50+ programs.",
    eligibilityNote: "Ghana is a World Bank member country — fully eligible.",
    officialUrl: "https://www.worldbank.org/en/programs/scholarships",
    competitiveNote: "~200-300 awards/year; the 3-year experience filter thins the pool significantly.",
    successTips: "Quantify your development impact (budgets managed, beneficiaries, policies touched) — the essays are scored on evidence, not aspirations.",
  },
  {
    name: "Rotary Peace Fellowship",
    kind: "SCHOLARSHIP",
    provider: "Rotary Foundation",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Evanston, IL",
    lat: 42.0451,
    lng: -87.6877,
    levels: ["masters"],
    fields: ["public policy", "social sciences", "development studies", "law"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + fees + room & board + round-trip transportation + internship/study expenses at 7 partner universities (Duke/UNC, Bradford, Uppsala, Queensland, Tokyo, Makerere, Kampala; plus professional certificate centers). Up to 130 fellowships/year.",
    opensMonth: 2,
    opensDay: 1,
    closesMonth: 5,
    closesDay: 15,
    cycleNote: "Application window ~February 1 - May 15 (district endorsement deadlines in between), for study starting the following year.",
    moiAccepted: true,
    moiNote: "Partner universities handle admission language rules; English-medium degrees (Ghana) are widely accepted with MOI letters.",
    englishTests: "IELTS/TOEFL per partner university; MOI frequently accepted for English-medium degrees.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "A Rotary district endorsement process + references demonstrating peace & development engagement.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans accepted.",
    essayRequired: true,
    essayNote: "Peace/development experience essays — 5+ years of relevant work strongly preferred for the master's track.",
    applicationSteps: [
      { title: "Connect with a local Rotary club (Jan)", detail: "The fellowship requires district endorsement — contact a Rotary club in Accra early; clubs sponsor candidates through District 9104." },
      { title: "Apply via the Rotary portal (Feb 1 - May 15)", detail: "Free: essays, scans, references, program choices." },
      { title: "District interview & endorsement (May-Jun)", detail: "Your district interviews and endorses your candidacy." },
      { title: "Rotary global selection (Jul-Oct)", detail: "The Foundation ranks endorsed candidates globally." },
      { title: "Partner university admission", detail: "Selected fellows apply to the partner program (Duke-UNC, Uppsala, Bradford...) with fee guidance." },
    ],
    requirementsSummary: "Free application + Rotary district endorsement + peace/development track record. Full ride.",
    eligibilityNote: "All nationalities; master's track wants 5+ years relevant experience (certificate track wants 7+).",
    officialUrl: "https://www.rotary.org/en/our-programs/peace-fellowships",
    competitiveNote: "~130 fellowships but few know the process starts with a local club — early club contact is the real bottleneck.",
    successTips: "Document concrete peacebuilding/development work — community mediation, NGO programs, policy work all count.",
  },
  {
    name: "Lester B. Pearson International Scholarships (U of Toronto)",
    kind: "SCHOLARSHIP",
    provider: "University of Toronto",
    country: "Canada",
    countryCode: "ca",
    continent: "North America",
    city: "Toronto",
    lat: 43.6532,
    lng: -79.3832,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 180,
    feeCurrency: "CAD",
    feeConfirmedFree: false,
    feeNote: "School nomination + scholarship application are free, but the standard U of T undergraduate application fee (~CAD 180) applies unless the university's fee-waiver provisions cover you — verify with your school counselor.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + books + incidental fees + full residence support for FOUR years — Canada's most generous international undergrad award (~37-40 scholars/year).",
    opensMonth: 9,
    opensDay: 1,
    closesMonth: 11,
    closesDay: 30,
    cycleNote: "School nomination + application: September-30 November (application to U of T by January).",
    moiAccepted: true,
    moiNote: "U of T accepts English-medium education; if your Ghanaian school taught in English you may not need IELTS — counselor confirmation letter typically suffices.",
    englishTests: "IELTS 6.5/TOEFL 100 normally; waivable with English-medium schooling evidence.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 1,
    recommendationsNote: "School nomination (principal/counselor) + teacher recommendation built into the U of T application.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned/interim transcripts standard for undergrad admission.",
    essayRequired: true,
    essayNote: "Pearson online questionnaire (short answers on leadership and impact).",
    applicationSteps: [
      { title: "Get your school's nomination (Sep)", detail: "Your secondary school must be a recognized Pearson-participating school OR request nomination — talk to your head of school in September of your final year." },
      { title: "Apply to U of T (by Nov 30 for Pearson consideration)", detail: "Apply to at least one U of T program first — this triggers your Pearson invitation email if nominated." },
      { title: "Complete the Pearson scholarship application", detail: "The invitation links you to the Pearson questionnaire — short essays on creativity, leadership, community impact." },
      { title: "Selection (Feb-Apr)", detail: "~37 scholars chosen on academic excellence + creativity + leadership + school community impact." },
    ],
    requirementsSummary: "School nomination + U of T application + Pearson questionnaire. 4-year full ride (~CAD 300k+ value).",
    eligibilityNote: "International secondary students nominated by their school; Ghanaian schools can request participation.",
    officialUrl: "https://future.utoronto.ca/pearson/",
    competitiveNote: "~37 awards/year globally.",
    successTips: "Your school's nomination letter is the gate — invest in a genuine relationship with your counselor from Grade 11.",
  },
  {
    name: "Vanier Canada Graduate Scholarships",
    kind: "SCHOLARSHIP",
    provider: "Government of Canada",
    country: "Canada",
    countryCode: "ca",
    continent: "North America",
    city: "Ottawa",
    lat: 45.4215,
    lng: -75.6972,
    levels: ["phd"],
    fields: ["any", "medicine & health", "natural sciences", "engineering", "social sciences"],
    feeAmount: 0,
    feeCurrency: "CAD",
    feeConfirmedFree: true,
    feeNote: "No application fee for the Vanier award itself — you apply through the Canadian university's internal nomination.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "CAD $50,000/year for 3 years — Canada's flagship doctoral award (166 per year).",
    opensMonth: 8,
    opensDay: 15,
    closesMonth: 10,
    closesDay: 31,
    cycleNote: "Internal university deadlines run Aug-Oct; the central deadline is end of October/1 November. Contact your target university by August.",
    moiAccepted: true,
    moiNote: "Canadian universities decide English proof; several (Memorial, Saskatchewan, Manitoba...) accept MOI from English-speaking countries incl. Ghana.",
    englishTests: "IELTS 6.5-7.0 per university — MOI accepted at several Canadian universities.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two referee assessments + institutional endorsement.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts via the university's internal process.",
    essayRequired: true,
    essayNote: "Three-part narrative: academic excellence, research potential, leadership (1,150 words each max) — the leadership piece is Vanier's differentiator.",
    applicationSteps: [
      { title: "Secure a Canadian PhD supervisor (spring-summer)", detail: "Vanier requires nomination BY the university — email potential supervisors first; admission comes first, nomination second." },
      { title: "Confirm your university's internal deadline (Aug)", detail: "Each university (UBC, Toronto, McGill, Waterloo...) runs its own Vanier competition with earlier internal deadlines." },
      { title: "Build the 3-part narrative", detail: "Academic record + research proposal + leadership evidence (mentoring, community, policy). Referee assessments mirror these headings." },
      { title: "University nominates you (Oct)", detail: "Universities submit 2 nominees per doctoral program to the central competition." },
      { title: "National adjudication (Nov-Mar)", detail: "Results ~March; $50k/year begins the following May or September." },
    ],
    requirementsSummary: "University nomination + supervisor + 3-part narrative + 2 referees. Free. $50k/yr for 3 years.",
    eligibilityNote: "All nationalities; must be nominated by a Canadian institution.",
    officialUrl: "https://vanier.gc.ca/",
    competitiveNote: "166 awards/year nationally — among the highest-value awards with a defined leadership scoring rubric.",
    successTips: "Read the published Vanier scoring rubric and write TO it: each heading gets equal weight, so don't over-invest only in research.",
  },
  {
    name: "Smith College — $0 Application + Full Need Aid",
    kind: "UNIVERSITY",
    provider: "Smith College (women's college)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Northampton, MA",
    lat: 42.3251,
    lng: -72.6412,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee for international first-year applicants — confirmed $0.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Smith meets 100% of demonstrated financial need for admitted international students — aid packages typically cover $50k-70k/year (tuition, housing, meals) via grants; top applicants pay near zero.",
    opensMonth: 8,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 15,
    cycleNote: "Common App opens Aug 1; Early Decision Nov 15, Regular Decision Jan 15.",
    moiAccepted: true,
    moiNote: "No SAT/ACT required. English proof: students from English-medium schools (Ghana's WAEC/English curriculum) generally satisfy requirements via counselor documentation.",
    englishTests: "TOEFL/IELTS recommended for non-English-medium schools; waivable with English-medium schooling evidence.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "School report + 2 teacher recommendations via Common App.",
    unofficialTranscripts: true,
    transcriptsNote: "School-submitted transcripts; no certified-translation hurdles initially.",
    essayRequired: true,
    essayNote: "Common App personal essay + Smith supplement.",
    applicationSteps: [
      { title: "Create a Common App account (Aug)", detail: "One free application covers Smith — select Smith and the international applicant track. $0 fee." },
      { title: "Complete CSS Profile + ISFAA", detail: "International applicants submit the CSS Profile (or International Student Financial Aid Application) to document need — be thorough and honest; Smith budgets generously for full-need admits." },
      { title: "Submit essays + recommendations (Nov-Jan)", detail: "Common App essay + Smith writing supplement + teacher letters + school transcript." },
      { title: "Admission + aid letter (Mar)", detail: "Smith's admission is need-aware for internationals but full-need-met for admits — the aid package arrives with the offer." },
    ],
    requirementsSummary: "$0 application fee, no SAT/ACT, need-blind-quality full aid for internationals. Women's college (one of the strongest aid programs anywhere).",
    eligibilityNote: "International first-year applicants; Smith is a women's college.",
    officialUrl: "https://www.smith.edu/admission-aid",
    competitiveNote: "Selectivity ~20%; full-need international admits are the norm for strong applicants.",
    successTips: "The financial documentation must be consistent — discrepancies between CSS Profile and school documents sink international aid offers.",
  },
  {
    name: "Wellesley College — $0 Application + Full Need Aid",
    kind: "UNIVERSITY",
    provider: "Wellesley College (women's college)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Wellesley, MA",
    lat: 42.2934,
    lng: -71.2948,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed $0 for all applicants.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Meets 100% of demonstrated need for admitted internationals — packages commonly cover tuition + housing + meals ($80k+/year value) through grants, no loans.",
    opensMonth: 8,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 8,
    cycleNote: "Common App opens Aug 1; Early Decision Nov 1; Regular Decision Jan 8.",
    moiAccepted: true,
    moiNote: "English-medium schooling (Ghana) satisfies language documentation via counselor letter.",
    englishTests: "Waivable with English-medium education evidence.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "2 teacher recommendations + counselor report via Common App.",
    unofficialTranscripts: true,
    transcriptsNote: "School-submitted.",
    essayRequired: true,
    essayNote: "Common App essay + Wellesley 'Why Wellesley' short response.",
    applicationSteps: [
      { title: "Common App (free, Aug-Jan)", detail: "Select Wellesley, mark international + financial aid intent. $0." },
      { title: "CSS Profile / ISFAA", detail: "Document family finances carefully — Wellesley computes need-based grants covering the full gap." },
      { title: "Essays + recommendations", detail: "Standard Common App set + the Wellesley supplement." },
      { title: "Decision + aid (Mar)", detail: "Admission and full-need aid letter together." },
    ],
    requirementsSummary: "$0 fee, no SAT/ACT, full-need aid for international admits. Women's college with the strongest aid reputation.",
    eligibilityNote: "International first-year applicants; women's college.",
    officialUrl: "https://www.wellesley.edu/admission",
    competitiveNote: "~14-20% acceptance; international aid spots are competitive but Wellesley's no-loan packages are exceptional.",
    successTips: "Wellesley reads the 'Why Wellesley' response closely — reference specific programs (Wellesley Centers for Women, Madeleine Korbel Albright Institute).",
  },
  {
    name: "Bowdoin College — $0 Application + Full Need Aid",
    kind: "UNIVERSITY",
    provider: "Bowdoin College",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Brunswick, ME",
    lat: 43.9145,
    lng: -69.9653,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed $0.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Meets 100% of demonstrated need for all admitted students including internationals; packages are grant-heavy and loan-free. Total cost of attendance ~$85k/yr covered by aid for full-need admits.",
    opensMonth: 8,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 5,
    cycleNote: "Common App Aug 1; ED Nov 1; RD Jan 5.",
    moiAccepted: true,
    moiNote: "English-medium schooling satisfies requirements; no SAT/ACT (test-optional permanently).",
    englishTests: "Waivable with English-medium evidence.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "2 teacher recs + counselor materials.",
    unofficialTranscripts: true,
    transcriptsNote: "School-submitted.",
    essayRequired: true,
    essayNote: "Common App essay + Bowdoin supplemental (including the famous 'offer your perspective' list).",
    applicationSteps: [
      { title: "Common App + Bowdoin supplement (free)", detail: "$0 application. Choose test-optional path." },
      { title: "CSS Profile for international aid", detail: "Document need; Bowdoin computes a loan-free grant package." },
      { title: "Submit by Jan 5 (RD)", detail: "Essays, recs, transcripts via Common App." },
      { title: "Decision + aid (Mar-Apr)", detail: "Full-need admits get their complete package with the offer." },
    ],
    requirementsSummary: "$0 fee, test-optional, full-need aid for internationals, loan-free packages.",
    eligibilityNote: "International first-years; coeducational liberal arts at New England's coast.",
    officialUrl: "https://admissions.bowdoin.edu/",
    competitiveNote: "~9% overall; the $0 fee + full aid makes Bowdoin a top-value target for Ghanaian applicants.",
    successTips: "The supplement's 'common threads' list rewards genuine quirks — be specific and human.",
  },
  {
    name: "Carleton College — $0 Application + Generous Aid",
    kind: "UNIVERSITY",
    provider: "Carleton College",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Northfield, MN",
    lat: 44.4581,
    lng: -93.1548,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed $0.",
    fundingType: "PARTIAL",
    fundingNote: "International aid is need-based and substantial (typical packages $40k-60k/yr) though Carleton is need-aware and not every international admit receives full-need aid — ask early via the aid office.",
    opensMonth: 8,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 15,
    cycleNote: "Common App Aug 1; ED Nov 15; RD Jan 15.",
    moiAccepted: true,
    moiNote: "English-medium schooling accepted; test-optional.",
    englishTests: "Waivable with English-medium evidence.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "2 teacher recs + school report.",
    unofficialTranscripts: true,
    transcriptsNote: "School-submitted.",
    essayRequired: true,
    essayNote: "Common App essay + Carleton supplement.",
    applicationSteps: [
      { title: "Common App ($0)", detail: "Select Carleton; test-optional." },
      { title: "ISFAA/CSS Profile", detail: "Apply for international aid the same season — Carleton requires the aid application with admission." },
      { title: "Submit RD by Jan 15", detail: "Essays, recs, transcript." },
      { title: "Decision + aid (Mar)", detail: "Aid packages disclosed with admission." },
    ],
    requirementsSummary: "$0 fee, test-optional, strong need-based aid (ask about full-need coverage for internationals).",
    eligibilityNote: "International first-years.",
    officialUrl: "https://www.carleton.edu/admissions/",
    competitiveNote: "~18% acceptance; strong sciences and rigorous academics.",
    successTips: "Email the international aid office in October confirming current policy for full-need international aid before investing the application.",
  },
  {
    name: "Colby College — $0 Application + Full Need Aid",
    kind: "UNIVERSITY",
    provider: "Colby College",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Waterville, ME",
    lat: 44.5521,
    lng: -69.6639,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed $0.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Colby meets 100% of demonstrated need for admitted internationals with loan-free packages — total cost of attendance ~$85k/yr covered for full-need admits.",
    opensMonth: 8,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 15,
    cycleNote: "Common App Aug 1; ED I Nov 15, ED II Jan 1; RD Jan 15.",
    moiAccepted: true,
    moiNote: "English-medium schooling accepted; test-optional.",
    englishTests: "Waivable with English-medium evidence.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "2 teacher recs + counselor report.",
    unofficialTranscripts: true,
    transcriptsNote: "School-submitted.",
    essayRequired: true,
    essayNote: "Common App essay + Colby supplement.",
    applicationSteps: [
      { title: "Common App ($0)", detail: "Select Colby; test-optional path." },
      { title: "CSS Profile", detail: "Full-need international aid application with admission." },
      { title: "Submit by Jan 15", detail: "Essays, recs, transcripts." },
      { title: "Decision + aid (Mar)", detail: "Loan-free full-need packages." },
    ],
    requirementsSummary: "$0 fee, test-optional, full-need loan-free aid for international admits.",
    eligibilityNote: "International first-years; strong AI/government programs (Davis Institute for AI).",
    officialUrl: "https://www.colby.edu/admission/",
    competitiveNote: "~8-10% acceptance; Jan Plan and AI institute are differentiators to mention.",
    successTips: "Mention Colby's Davis Institute for Artificial Intelligence if you're STEM-bound — it signals fit.",
  },
  {
    name: "Reed College — $0 Application + Need-Based Aid",
    kind: "UNIVERSITY",
    provider: "Reed College",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Portland, OR",
    lat: 45.5430,
    lng: -122.6320,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee for international applicants — confirmed $0.",
    fundingType: "PARTIAL",
    fundingNote: "International aid packages average $40k-70k/yr; Reed is need-aware for internationals — aid levels vary by admit cycle.",
    opensMonth: 8,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 15,
    cycleNote: "Common App Aug 1; ED Nov 1; RD Jan 15.",
    moiAccepted: true,
    moiNote: "English-medium schooling accepted; test-optional.",
    englishTests: "Waivable with English-medium evidence.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "2 teacher recs + counselor report.",
    unofficialTranscripts: true,
    transcriptsNote: "School-submitted.",
    essayRequired: true,
    essayNote: "Common App essay + Reed 'Why Reed' supplement.",
    applicationSteps: [
      { title: "Common App ($0)", detail: "Select Reed; test-optional." },
      { title: "ISFAA/CSS Profile", detail: "Aid application parallel to admission." },
      { title: "Submit by Jan 15", detail: "Essays, recs, transcript." },
      { title: "Decision + aid (Mar-Apr)", detail: "Packages with offer." },
    ],
    requirementsSummary: "$0 fee, test-optional, substantial need-based aid; intellectual rigor is the brand.",
    eligibilityNote: "International first-years.",
    officialUrl: "https://www.reed.edu/admission/",
    competitiveNote: "~30% acceptance; heavy academic writing culture.",
    successTips: "Reed's supplement rewards genuine intellectual curiosity — write about ideas, not achievements.",
  },
  {
    name: "US PhD Programs with Application Fee Waivers (STEM pattern)",
    kind: "SCHOLARSHIP",
    provider: "US research universities",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Chicago, IL",
    lat: 41.8781,
    lng: -87.6298,
    levels: ["phd"],
    fields: ["any", "computer science", "engineering", "natural sciences", "mathematics", "medicine & health"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "Many US STEM PhD programs charge NO application fee at all (documented examples: University of Chicago physical/biological sciences PhDs, Duke natural sciences & engineering PhDs, MIT EECS, Caltech option). Others waive fees on request for financial hardship or diversity programs — always ask the graduate coordinator.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "US PhD students receive Research/Teaching Assistantships: $30,000-48,000/yr stipend + full tuition waiver + health insurance — admission IS the funding in STEM.",
    opensMonth: 9,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 15,
    cycleNote: "Applications open Sep-Oct with deadlines Dec 1-15 (some Jan 5) for fall entry.",
    moiAccepted: true,
    moiNote: "TOEFL is commonly required, but many programs accept IELTS or waive with English-medium degrees — and several programs dropped English test requirements post-2020. Check each program's FAQ.",
    englishTests: "TOEFL 90-100/IELTS 7.0 typical; waivable at several programs with English-medium degrees.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 3,
    recommendationsNote: "Three recommendation letters standard for US PhD admissions.",
    unofficialTranscripts: true,
    transcriptsNote: "Unofficial/scanned transcripts are universally accepted at application — official copies only after admission.",
    essayRequired: true,
    essayNote: "Statement of Purpose (SOP) + often a diversity/personal history statement.",
    applicationSteps: [
      { title: "Build a target list (Aug-Sep)", detail: "20-30 programs in your field; check each department's fee policy ('no application fee' or 'fee waiver available'). FindAPhD and department FAQs document this." },
      { title: "Email potential PIs (Sep)", detail: "Short, specific emails: their recent paper + your fit + your CV. At many US programs, a professor's support pre-decides admission." },
      { title: "Request fee waivers (Oct)", detail: "Email the graduate coordinator: 'Is a fee waiver available for exceptional applicants with financial need?' Programs grant these routinely but rarely advertise." },
      { title: "Submit applications by Dec 1-15", detail: "SOP (evidence of research), CV, scans (unofficial ok), 3 referees, English test or waiver." },
      { title: "Interviews (Jan-Feb)", detail: "Virtual interviews; expect research deep-dives with 3-5 faculty." },
      { title: "Offers with full funding (Feb-Apr)", detail: "Admission letters include assistantship offers — never accept unfunded US PhD offers in STEM." },
    ],
    requirementsSummary: "Free/waived applications common in US STEM PhDs; unofficial transcripts standard; 3 letters; full funding = admission.",
    eligibilityNote: "All nationalities; Ghanaian applicants succeed in CS, engineering, and biomedical fields especially.",
    officialUrl: "https://www.findaphd.com/guides/phd-in-usa",
    competitiveNote: "Per-program admit rates 5-20%, but applying to 15-25 fee-free/waived programs is normal strategy.",
    successTips: "The SOP must read as a research biography: problem → method → result → what's next. US committees fund evidence of research capability, not dreams.",
  },
  {
    name: "Australia Awards Scholarships (Africa incl. Ghana)",
    kind: "SCHOLARSHIP",
    provider: "Australian Government (DFAT)",
    country: "Australia",
    countryCode: "au",
    continent: "Oceania",
    city: "Canberra",
    lat: -35.2809,
    lng: 149.1300,
    levels: ["masters"],
    fields: ["any", "agriculture & food", "medicine & health", "public policy", "environment", "energy", "development studies"],
    feeAmount: 0,
    feeCurrency: "AUD",
    feeConfirmedFree: true,
    feeNote: "No application fee — free online application through OASIS.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + return air travel + establishment allowance (~A$5,000) + fortnightly stipend (CLE) + introductory academic program + health cover (OSHC) + fieldwork allowance for research masters.",
    opensMonth: 2,
    opensDay: 1,
    closesMonth: 4,
    closesDay: 30,
    cycleNote: "Stable annual window: 1 February - 30 April for intake the following year.",
    moiAccepted: false,
    moiNote: "IELTS 6.5 (no band below 6.0) is required for Australia Awards — MOI is NOT sufficient here. Plan the IELTS test 6 months ahead (IELTS is available in Accra).",
    englishTests: "IELTS 6.5 (min 6.0 per band) — mandatory.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Referee reports requested at interview/final stage.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned certificates/transcripts uploaded to OASIS.",
    essayRequired: true,
    essayNote: "Development-impact questions in OASIS — how your study advances Ghana's development priorities.",
    applicationSteps: [
      { title: "Check Ghana's priority sectors (Jan)", detail: "Australia Awards Africa publishes priority fields for Ghana (mining governance, agriculture, health, water...) — choose within them." },
      { title: "Take IELTS in Accra (Jan-Feb)", detail: "You need IELTS 6.5 before applying — book early; results take 2 weeks." },
      { title: "Apply on OASIS (Feb 1 - Apr 30)", detail: "Free portal: scans, IELTS result, development-impact answers, referee contacts." },
      { title: "Shortlisting & panel interview (Jun-Aug)", detail: "Interviews in Accra assess development commitment and return plans." },
      { title: "Award & university placement (Oct-Dec)", detail: "DFAT matches you to Australian universities in your field." },
      { title: "Pre-departure & study (Jan-Feb)", detail: "Introductory academic program before the degree; 2-year home-return rule applies." },
    ],
    requirementsSummary: "Free application + IELTS 6.5 mandatory + scans + development essays. Feb-Apr window.",
    eligibilityNote: "Ghana is an Australia Awards Africa country — strong bilateral quota.",
    officialUrl: "https://www.australiaawardsafrica.org/",
    competitiveNote: "Ghana's cohort is well established; public-sector experience helps.",
    successTips: "Tie your application to a named Ghanaian institution that will absorb your skills (e.g. Minerals Commission, Ministry of Food and Agriculture).",
  },
  {
    name: "Manaaki New Zealand Scholarships",
    kind: "SCHOLARSHIP",
    provider: "New Zealand Ministry of Foreign Affairs (MFAT)",
    country: "New Zealand",
    countryCode: "nz",
    continent: "Oceania",
    city: "Wellington",
    lat: -41.2866,
    lng: 174.7756,
    levels: ["masters", "phd"],
    fields: ["agriculture & food", "environment", "medicine & health", "engineering", "development studies", "energy"],
    feeAmount: 0,
    feeCurrency: "NZD",
    feeConfirmedFree: true,
    feeNote: "No application fee — free online application.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + NZ$531 weekly living allowance + NZ$3,000 establishment + travel + insurance + reintegration support.",
    opensMonth: 2,
    opensDay: 1,
    closesMonth: 3,
    closesDay: 28,
    cycleNote: "Application window ~1 February - late March each year.",
    moiAccepted: false,
    moiNote: "IELTS 6.5 typically required by NZ universities — MOI is not a standard waiver route here.",
    englishTests: "IELTS 6.5 (academic) generally required.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two referees who can speak to your development leadership.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans uploaded.",
    essayRequired: true,
    essayNote: "Development-relevance questions in the application.",
    applicationSteps: [
      { title: "Verify country eligibility (Jan)", detail: "Manaaki covers selected African countries — confirm Ghana's current inclusion on the MFAT list before applying." },
      { title: "Apply free (Feb-Mar)", detail: "Online: scans, referees, development answers, IELTS plan." },
      { title: "Shortlist & interview", detail: "NZ embassy regional processing." },
      { title: "University placement", detail: "MFAT allocates NZ universities in your field." },
    ],
    requirementsSummary: "Free application, IELTS 6.5, 2 referees, development focus.",
    eligibilityNote: "Selected African/Asian/Pacific countries — VERIFY Ghana's current eligibility (it has varied by year).",
    officialUrl: "https://www.mfat.govt.nz/en/aid-and-development/new-zealand-scholarships/",
    competitiveNote: "Smaller pool than Australia Awards; agriculture/climate fields favored.",
    successTips: "Climate-resilience and food-security framings match NZ's aid strategy priorities.",
  },
  {
    name: "AIMS Structured Masters (incl. Ghana campus)",
    kind: "UNIVERSITY",
    provider: "African Institute for Mathematical Sciences",
    country: "Ghana",
    countryCode: "gh",
    continent: "Africa",
    city: "Biriwa",
    lat: 5.2360,
    lng: -1.2900,
    levels: ["masters"],
    fields: ["mathematics", "computer science", "natural sciences", "data science"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "For selected students: full tuition + accommodation + meals + stipend + travel to the campus (Ghana, Rwanda, Senegal, South Africa, Tanzania). Pan-African cohort taught by global lecturers.",
    rolling: true,
    cycleNote: "Applications open ~November and close March-April (rolling review until places fill) for September intake.",
    moiAccepted: true,
    moiNote: "English-taught; English-medium Ghanaian degrees accepted with MOI — no IELTS demanded.",
    englishTests: "Not required.",
    localLanguageRequired: false,
    localLanguageNote: "None (French used at Senegal campus).",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two academic referees submit online.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts at application.",
    essayRequired: true,
    essayNote: "Statement of purpose focused on mathematical sciences ambitions.",
    applicationSteps: [
      { title: "Choose your campus + track", detail: "AIMS Ghana (Biriwa), Rwanda (Kigali), Senegal (Mbour, French), South Africa (Cape Town), Tanzania (Zanzibar). Tracks: structured masters, teacher training, ML/AI streams." },
      { title: "Apply free (Nov-Apr)", detail: "Online form: scans, 2 referees, SOP. No fee, no IELTS." },
      { title: "Review & interviews", detail: "Academic review + occasional short online interviews." },
      { title: "Full sponsorship for selected students", detail: "Tuition + living + travel covered; pan-African network access (AIMS alumni network is elite)." },
    ],
    requirementsSummary: "Free application, scans, 2 referees, no IELTS. Fully funded for selected students. Ghana campus = study at home with world faculty.",
    eligibilityNote: "African students prioritized (pan-African mission); strong math background required.",
    officialUrl: "https://aims.ac.rw/",
    competitiveNote: "Hundreds of places across 5 campuses; mathematical sciences pipeline to global PhDs (AIMS feeds Oxford, Cambridge, MIT PhD programs).",
    successTips: "For Ghanaians, AIMS Ghana is the highest-leverage free-apply option in the dataset — admission + funding + home-base transition into global PhD programs.",
  },
  {
    name: "Pan African University (PAU) Scholarships",
    kind: "SCHOLARSHIP",
    provider: "African Union Commission",
    country: "Cameroon",
    countryCode: "cm",
    continent: "Africa",
    city: "Yaoundé",
    lat: 3.8480,
    lng: 11.5021,
    levels: ["masters", "phd"],
    fields: ["any", "engineering", "natural sciences", "agriculture & food", "medicine & health", "water", "energy", "social sciences"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + monthly stipend (~$500 masters) + accommodation + airfare (one-time) + research support. Institutes: PAUSTI (Kenya), PAUWES (Algeria), PAULESI (Nigeria), PAV (Nigeria), PAUGHSS (Cameroon).",
    opensMonth: 4,
    opensDay: 1,
    closesMonth: 6,
    closesDay: 30,
    cycleNote: "Call typically opens April and closes June for October intake.",
    moiAccepted: true,
    moiNote: "English-taught institutes accept English-medium degrees — Ghanaian applicants are among the largest cohorts. French needed only for PAUWES (Algeria) tracks.",
    englishTests: "Generally not required; university entrance evaluations per institute.",
    localLanguageRequired: false,
    localLanguageNote: "English at most institutes; French at PAUWES Algeria.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two recommendation letters + transcripts uploaded.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans accepted at application.",
    essayRequired: true,
    essayNote: "Motivation/impact statement on AU Agenda 2063 themes.",
    applicationSteps: [
      { title: "Pick your PAU institute (Mar)", detail: "Water & energy (PAUWES, Algeria — French), life & earth sciences (PAULESI, Nigeria), basic tech/innovation (PAUSTI, Kenya), governance (PAUGHSS, Cameroon), veterinary (PAV, Nigeria)." },
      { title: "Apply free (Apr-Jun)", detail: "Single online portal: scans, 2 references, statement. No fee." },
      { title: "Institute-level evaluation (Jul-Aug)", detail: "Entrance assessment/interview per institute." },
      { title: "AU scholarship confirmation & relocation (Sep-Oct)", detail: "Stipend + housing + flight arranged." },
    ],
    requirementsSummary: "Free application, scans, 2 references, impact statement. Full AU funding across 5 continental institutes.",
    eligibilityNote: "African Union citizens incl. Ghanaians; women's participation is explicitly encouraged with extra seats.",
    officialUrl: "https://pau-au.africa/",
    competitiveNote: "Strong odds for well-prepared applicants; PAULESI and PAUSTI are the largest pools.",
    successTips: "Anchor your statement in Agenda 2063 priorities (industrialization, food security, water) — the AU reads against its own strategy.",
  },
  {
    name: "Ashesi University — Mastercard Foundation Scholars",
    kind: "UNIVERSITY",
    provider: "Ashesi University + Mastercard Foundation",
    country: "Ghana",
    countryCode: "gh",
    continent: "Africa",
    city: "Berekuso",
    lat: 5.7480,
    lng: -0.1900,
    levels: ["undergraduate"],
    fields: ["computer science", "business & economics", "engineering"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "The Mastercard Scholars application at Ashesi is free (regular Ashesi admission has a small local fee, but the scholarship route waives it).",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + housing + meals + laptop + learning materials + stipend for 4 years — for Ghanaian and African students with financial need and leadership promise.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 3,
    closesDay: 31,
    cycleNote: "Scholarship applications typically Dec-March for August intake (rolling review of complete files).",
    moiAccepted: true,
    moiNote: "English-medium (Ghana) — no IELTS needed; WASSCE results and school records suffice.",
    englishTests: "None required.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two letters (teacher/head of school/community leader).",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned school records + WASSCE/BECE results accepted.",
    essayRequired: true,
    essayNote: "Leadership & financial-need essays in the scholarship form.",
    applicationSteps: [
      { title: "Check eligibility (Nov)", detail: "Academically strong Ghanaian/African students with demonstrated financial need + leadership/community service record." },
      { title: "Apply free (Dec-Mar)", detail: "Ashesi scholarship portal: essays, scans, 2 letters. No fee on the scholarship route." },
      { title: "Interview & home visit (Apr-May)", detail: "Scholarship committee interviews; need verification may include local visits." },
      { title: "Enroll (Aug)", detail: "Full package: tuition, room, board, laptop, stipend." },
    ],
    requirementsSummary: "Free scholarship application, school scans, 2 letters, leadership essays. Full 4-year funding in Ghana.",
    eligibilityNote: "Ghanaian and other African students with financial need; leadership focus.",
    officialUrl: "https://www.ashesi.edu.gh/admissions/scholarships",
    competitiveNote: "Ashesi is Ghana's top-ranked private university — Mastercard seats are limited but the process is transparent.",
    successTips: "Concrete community-impact evidence (clubs founded, projects led) carries the essays.",
  },
  {
    name: "Ghana Scholarships Secretariat — Local & Foreign Awards",
    kind: "SCHOLARSHIP",
    provider: "Government of Ghana",
    country: "Ghana",
    countryCode: "gh",
    continent: "Africa",
    city: "Accra",
    lat: 5.6037,
    lng: -0.1870,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "GHS",
    feeConfirmedFree: false,
    feeNote: "The government scholarship application is free in principle, but some schemes have announced nominal processing/form fees in past cycles — confirm the current fee schedule with the Secretariat or your District Assembly before applying.",
    fundingType: "PARTIAL",
    fundingNote: "Varies by scheme: local tertiary support (fee reimbursement), bilateral foreign scholarships (full tuition + stipend where offered), GNPC Foundation and district-level schemes. Amounts change yearly.",
    rolling: true,
    cycleNote: "Announcements roll out through the year via District Assemblies and the Secretariat — check scholarships.gov.gh monthly.",
    moiAccepted: true,
    moiNote: "For foreign placements, English-medium documentation from Ghana suffices at application.",
    englishTests: "Per destination university.",
    localLanguageRequired: false,
    localLanguageNote: "None.",
    recommendationsRequired: false,
    recommendationsNote: "Usually not; district endorsement letter instead.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans + local certification at district offices.",
    essayRequired: false,
    applicationSteps: [
      { title: "Register at your District Assembly", detail: "Ghana's scholarship system starts locally — the District Scholarship Committee validates residency and need." },
      { title: "Watch scholarships.gov.gh for calls", detail: "Bilateral foreign awards (China, Hungary, Morocco, India, Russia...) are routed through the Secretariat — these pair with the free applications in this database." },
      { title: "Submit district-verified file", detail: "Scans + endorsement." },
      { title: "Interview & award", detail: "Secretariat/committee review; foreign nominations forwarded to partner governments." },
    ],
    requirementsSummary: "District-endorsed free application route that UNLOCKS bilateral foreign scholarships (Hungary, China, Russia, India...).",
    eligibilityNote: "Ghanaian citizens; need- and merit-based tracks.",
    officialUrl: "https://scholarships.gov.gh/",
    competitiveNote: "Bilateral slots are under-marketed — most Ghanaians never register at district level, thinning competition.",
    successTips: "Register at your district EARLY (even without an active call) — bilateral scholarships often require pre-existing district files.",
  },
];
