import { SeedOpportunity } from "./seed-types";

/** NEW universities — free or ≤$30 confirmed application fees (Europe part 2). */
export const UNIS_EUROPE_2: SeedOpportunity[] = [
  {
    name: "University of Warsaw — PLN 85 (~$21)",
    slug: "university-warsaw",
    kind: "UNIVERSITY",
    provider: "Uniwersytet Warszawski",
    country: "Poland",
    countryCode: "pl",
    continent: "Europe",
    city: "Warsaw",
    lat: 52.24,
    lng: 21.012,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 85,
    feeCurrency: "PLN",
    feeConfirmedFree: false,
    feeUsdApprox: 21,
    feeNote: "Confirmed: IRK portal application fee PLN 85 (~$21) per programme.",
    related: [],
    fundingType: "SELF_FUNDED",
    fundingNote: "Polish-taught degrees free; English programmes ~€2,000–4,500/year — among the EU's cheapest. Rector's scholarships waive tuition for top students.",
    opensMonth: 4,
    opensDay: 15,
    closesMonth: 7,
    closesDay: 31,
    cycleNote: "IRK admissions open ~mid-Apr; international rounds close by mid-Jul (some programmes earlier) for October intake.",
    moiAccepted: true,
    moiNote: "University of Warsaw accepts B2 certificates OR proof of English-medium prior education (MOI letter) for many English programmes — good news for Ghanaians with English-taught degrees.",
    englishTests: "B2 level: IELTS 5.5–6.5 / TOEFL 72–87 / MOI letter accepted by many programmes.",
    localLanguageRequired: false,
    localLanguageNote: "Polish for Polish-taught (free); English degrees need none. Free Polish courses for international students.",
    recommendationsRequired: false,
    recommendationsNote: "No recommendation letters required.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scans in IRK; originals/Sworn translations validated at enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Create an IRK (Internet Recruitment of Candidates) account", detail: "irk.uw.edu.pl — one account covers all UW programmes; fee is per chosen programme." },
      { title: "Pay PLN 85 per programme by card/transfer", detail: "The fee activates your file for that programme's ranking." },
      { title: "Upload documents + select English-proof option", detail: "Scans of certificate, transcript, passport; choose 'document confirming English-medium education' where offered instead of IELTS." },
      { title: "Track your ranking result (Jul)", detail: "Admission is score-based on grades; no interview for most programmes." },
      { title: "Legalise status + apply for Rector's scholarship", detail: "After admission, submit the scholarship form — top students get tuition waivers or PLN stipends." },
    ],
    requirementsSummary: "PLN 85 fee, grade-based admission, no references, MOI route for English proof.",
    eligibilityNote: "Secondary school or bachelor's certificate recognised in Poland (apostille may be needed for enrolment).",
    officialUrl: "https://rekrutacja.uw.edu.pl/en/",
    competitiveNote: "Big lecture programmes admit widely; psychology/law are the tight ones.",
    successTips: "Apostille your certificates months in advance — it's the #1 enrolment delay for African applicants. Choose the MOI proof option to save an IELTS fee.",
  },
  {
    name: "Jagiellonian University Kraków — PLN 85 (~$21)",
    slug: "jagiellonian-university",
    kind: "UNIVERSITY",
    provider: "Uniwersytet Jagielloński (JU)",
    country: "Poland",
    countryCode: "pl",
    continent: "Europe",
    city: "Kraków",
    lat: 50.061,
    lng: 19.937,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 100,
    feeCurrency: "PLN",
    feeConfirmedFree: false,
    feeUsdApprox: 25,
    feeNote: "Confirmed: application fee PLN 85–100 (~$21–25) per programme depending on faculty.",
    related: ["erasmus-mundus"],
    fundingType: "SELF_FUNDED",
    fundingNote: "English programmes ~€2,000–5,400/year; Polish-taught free. JU scholarships + NAWA (Polish national agency) awards available.",
    opensMonth: 4,
    opensDay: 15,
    closesMonth: 7,
    closesDay: 31,
    cycleNote: "IRK Kraków window ~mid-Apr – Jul for October intake; some programmes run earlier summer deadlines.",
    moiAccepted: true,
    moiNote: "Many JU programmes accept MOI/medium-of-instruction confirmation in lieu of formal English certificates.",
    englishTests: "B2: IELTS 5.5–6.5 / TOEFL / MOI accepted on many programmes.",
    localLanguageRequired: false,
    localLanguageNote: "None for English tracks; free Polish course included for internationals.",
    recommendationsRequired: false,
    recommendationsNote: "Not required for taught degrees; PhD recruitment may ask for a supervisor endorsement.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans in the OAS/IRK portal; originals at enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Register in JU's online admissions (IRK)", detail: "Choose your English programme — JU offers everything from biotechnology to international security studies." },
      { title: "Pay the PLN 85–100 application fee", detail: "Per programme; bank transfer or e-payment." },
      { title: "Upload scans + English-proof choice", detail: "Include the MOI letter if your previous school taught in English." },
      { title: "Wait for the merit ranking", detail: "Most programmes rank by grades alone — no exams or interviews for many tracks." },
      { title: "Arrange visa + dorm early", detail: "Kraków dorms fill fast; JU's visa support letter comes with the admission decision." },
    ],
    requirementsSummary: "PLN 85–100 fee, grade-based, MOI accepted on many programmes.",
    eligibilityNote: "Standard certificate requirements; medical faculty has separate entry.",
    officialUrl: "https://welcome.uj.edu.pl/",
    competitiveNote: "Moderate; JU is Poland's oldest university with huge programme variety.",
    successTips: "Apply to both UW and JU in the same July — two ~$22 applications give you two EU admission shots. Check NAWA Poland scholarships for non-EU students.",
  },
  {
    name: "University of Camerino — $0 Application",
    slug: "camerino-university",
    kind: "UNIVERSITY",
    provider: "Università di Camerino (UNICAM)",
    country: "Italy",
    countryCode: "it",
    continent: "Europe",
    city: "Camerino",
    lat: 43.139,
    lng: 13.067,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: UNICAM charges no application fee for international admissions.",
    related: [],
    fundingType: "SELF_FUNDED",
    fundingNote: "Tuition €1,000–4,000/year sliding by family income — most developing-country students pay the bottom band. Fee waivers + merit grants common.",
    opensMonth: 1,
    opensDay: 15,
    closesMonth: 7,
    closesDay: 15,
    cycleNote: "International admissions window ~mid-Jan – mid-Jul for September intake; rolling review of complete files.",
    moiAccepted: true,
    moiNote: "Camerino commonly accepts an MOI letter / English-medium prior degree instead of IELTS — confirm per programme.",
    englishTests: "B2: IELTS 6.0 / TOEFL 80 / MOI letter or interview, per programme.",
    localLanguageRequired: false,
    localLanguageNote: "English degrees (computer science, biosciences, pharmacy…) need no Italian; free Italian course offered.",
    recommendationsRequired: false,
    recommendationsNote: "Not required.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scans via Esse3; dichiaraione di valore or CIMEA statements handled at enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Choose your UNICAM programme", detail: "Small historic university — strong English-taught tracks in CS, bioscience, geology, pharmacy." },
      { title: "Apply free through the international admission form", detail: "Fill the online pre-evaluation form with scanned documents — no fee at any stage." },
      { title: "Get the eligibility letter", detail: "UNICAM replies with an eligibility assessment you can use for Italian visa pre-enrolment (Universitaly)." },
      { title: "Complete Universitaly pre-enrolment", detail: "Mandatory for non-EU visa applicants; free government portal, UNICAM guides you through it." },
      { title: "Set income-based tuition + apply for grants", detail: "Submit ISEE-parificato income documents — most African applicants land the €1,000/year band plus DSU regional grant options." },
    ],
    requirementsSummary: "Zero fee, no references, MOI commonly accepted, income-based tiny tuition.",
    eligibilityNote: "Standard entry certificates; per-programme subject checks.",
    officialUrl: "https://www.unicam.it/international",
    competitiveNote: "Low competition — high acceptance odds for complete files.",
    successTips: "Start the Universitaly pre-enrolment as soon as you get the eligibility letter; Italian visa slots at some embassies are the real bottleneck, not admission.",
  },
  {
    name: "Sapienza University of Rome — $0 Application",
    slug: "sapienza-rome",
    kind: "UNIVERSITY",
    provider: "Sapienza Università di Roma",
    country: "Italy",
    countryCode: "it",
    continent: "Europe",
    city: "Rome",
    lat: 41.903,
    lng: 12.512,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: Sapienza charges no application fee; Universitaly pre-enrolment is free.",
    related: ["erasmus-mundus"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Tuition €0–2,900/year by income. Sapienza offers ~30 'International Scholarships' (€8,000 + tuition waiver) for master's applicants each year.",
    opensMonth: 1,
    opensDay: 15,
    closesMonth: 4,
    closesDay: 30,
    cycleNote: "Non-EU admission call typically mid-Jan – end Apr for September intake; scholarship applications inside the same call.",
    moiAccepted: true,
    moiNote: "Some Sapienza English programmes accept MOI documentation; others require B2 certificates — checked per programme.",
    englishTests: "B2 (IELTS 6.0/TOEFL 80) or MOI where programme allows.",
    localLanguageRequired: false,
    localLanguageNote: "Italian needed for Italian-taught degrees (many UG); English MSc widely available.",
    recommendationsRequired: false,
    recommendationsNote: "Not required for taught programmes.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans at application; legalised documents at enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Pick your programme in Sapienza's English catalogue", detail: "200+ English-taught courses across all schools; check the non-EU quota on each." },
      { title: "Submit the free online application", detail: "Sapienza's admission portal — upload transcript, diploma, passport, language proof." },
      { title: "Tick the International Scholarship box", detail: "Automatic consideration for €8,000 grants + tuition waiver for top non-EU applicants." },
      { title: "Complete Universitaly pre-enrolment for your visa", detail: "Free; needed for the study visa appointment at the Italian embassy (Ghana applicants use Accra)." },
      { title: "Finalise ISEE income assessment after arrival", detail: "Determines your €0–2,900 tuition band + access to free canteens (€1 meals) and dorms." },
    ],
    requirementsSummary: "Zero fee, built-in international scholarships, income-based tuition near zero.",
    eligibilityNote: "Programme-specific; UG requires 12 years of schooling — Ghanaians with WASSCE may need one bridging year or MIDD confirmation.",
    officialUrl: "https://www.uniroma1.it/en/pagine-strutturali/international-students",
    competitiveNote: "International scholarships competitive; plain admission for complete files is moderate.",
    successTips: "WASSCE holders: ask the international office about the 12-years-of-schooling rule early — a foundation year or advanced standing letter solves it. The €8,000 scholarship is automatic on strong grades.",
  },
  {
    name: "KU Leuven — $0 Application (most programmes)",
    slug: "ku-leuven",
    kind: "UNIVERSITY",
    provider: "Katholieke Universiteit Leuven",
    country: "Belgium",
    countryCode: "be",
    continent: "Europe",
    city: "Leuven",
    lat: 50.879,
    lng: 4.7,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: no application fee for the large majority of KU Leuven programmes (a handful of selective programmes charge ~€50–100 — stated on the programme page).",
    related: ["erasmus-mundus", "vlir-uos"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Non-EU tuition €3,500–9,000/year (lower for development-related programmes). VLIR-UOS scholarships + Science@Leuven grants cover strong applicants.",
    opensMonth: 11,
    opensDay: 1,
    closesMonth: 3,
    closesDay: 1,
    cycleNote: "Applications for September intake: ~1 Nov – 1 Mar (non-EEA should file by mid-Jan for visa time). Some faculties close earlier.",
    moiAccepted: true,
    moiNote: "KU Leuven waives English tests for applicants whose prior education was in English (incl. Ghanaian universities) — provide an MOI certificate; some programmes still insist on IELTS, stated per programme.",
    englishTests: "B2: IELTS 6.0–6.5 / TOEFL 79–94; waived with English-medium degree proof on many programmes.",
    localLanguageRequired: false,
    localLanguageNote: "Dutch for Dutch-taught; huge English master's catalogue (Europe's largest).",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two academic recommendation letters requested for most master's applications (uploaded by referees).",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scans in the web application; certified copies required only after conditional admission.",
    essayRequired: false,
    applicationSteps: [
      { title: "Find your programme + check its fee line", detail: "KU Leuven's education guide lists each programme's application fee (mostly €0), tuition and language proof." },
      { title: "File the free online application (1 Nov open)", detail: "One file per programme; upload scans: transcript, diploma (or proof of expected graduation), passport." },
      { title: "Register your two referees in the portal", detail: "They receive email links to submit letters — chase them; incomplete referee data stalls files." },
      { title: "Add English proof (MOI or IELTS)", detail: "Upload the medium-of-instruction certificate from your university if you studied in English." },
      { title: "Apply for Science@Leuven / VLIR-UOS funding", detail: "Science@Leuven grants (~€10k/year) open after admission; VLIR-UOS covers development-related programmes for partner-country students." },
    ],
    requirementsSummary: "€0 fee on most programmes, 2 references, scans first, MOI waiver route.",
    eligibilityNote: "Relevant bachelor's with good grades; some engineering programmes cap nationalities per quota rules.",
    officialUrl: "https://wms.kuleuven.be/sads",
    competitiveNote: "Strong but fair — complete, early files with clear referee letters fare well.",
    successTips: "File by early December: KU Leuven processes in order and visa timing for September starts gets tight after February for African applicants.",
  },
  {
    name: "University of Iceland — $0 Application",
    slug: "university-iceland",
    kind: "UNIVERSITY",
    provider: "Háskóli Íslands (UI)",
    country: "Iceland",
    countryCode: "is",
    continent: "Europe",
    city: "Reykjavík",
    lat: 64.14,
    lng: -21.9,
    levels: ["masters", "phd"],
    fields: ["environment", "engineering", "natural sciences", "social sciences", "education"],
    feeAmount: 0,
    feeCurrency: "ISK",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: no application fee; only a small annual registration fee (~ISK 6,900) after you enrol.",
    related: [],
    fundingType: "NO_TUITION",
    fundingNote: "No tuition at UI — you pay only the yearly registration fee. Living costs are the real expense (Iceland is pricey); scholarships are limited.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 2,
    closesDay: 1,
    cycleNote: "International applications: ~1 Dec – 1 Feb for the autumn semester.",
    moiAccepted: false,
    moiNote: "Formal English proof required for English-taught MSc (IELTS 6.0–6.5) — MOI rarely accepted.",
    englishTests: "IELTS 6.0–6.5 / TOEFL 79–90 depending on programme.",
    localLanguageRequired: false,
    localLanguageNote: "Icelandic for Icelandic-taught; several English MSc (renewable energy, environment).",
    recommendationsRequired: false,
    recommendationsNote: "Generally not required for taught master's.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans uploaded; originals verified at registration.",
    essayRequired: false,
    applicationSteps: [
      { title: "Browse UI's English master's catalogue", detail: "Strong in renewable energy, geosciences, Icelandic/international affairs." },
      { title: "Apply free in the UI application portal (1 Dec)", detail: "Upload scans: transcript, diploma, passport, English test." },
      { title: "Show funding for the residence permit", detail: "Icelandic Directorate of Immigration requires proof of funds (~ISK 200k+/month); combine with any grant letters." },
      { title: "Answer registration + pay the tiny fee after admission", detail: "ISK ~6,900/year — your only 'tuition'." },
      { title: "Hunt housing immediately", detail: "Student housing (SGI) lottery opens early; private market is tight — apply the week you're admitted." },
    ],
    requirementsSummary: "Zero application fee, no tuition, small registration fee; English test standard.",
    eligibilityNote: "Relevant bachelor's; energy programmes suit engineering/physics backgrounds.",
    officialUrl: "https://english.hi.is/university_international_students",
    competitiveNote: "Under-the-radar — good acceptance odds; the funding proof is the real gate.",
    successTips: "Pair UI admission with Erasmus Mundus or home-government funding, since UI itself has few scholarships. The geothermal/renewable programmes are world-class for the price.",
  },
  {
    name: "Université Grenoble Alpes — $0 Application (Parcoursup/Mon Master)",
    slug: "grenoble-alpes",
    kind: "UNIVERSITY",
    provider: "Université Grenoble Alpes (UGA)",
    country: "France",
    countryCode: "fr",
    continent: "Europe",
    city: "Grenoble",
    lat: 45.19,
    lng: 5.72,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: €0 application fee via the national platforms — Parcoursup (bachelor) and Mon Master (master). Some selective degrees use their own free portals.",
    related: ["eiffel", "erasmus-mundus"],
    fundingType: "NO_TUITION",
    fundingNote: "EU-rate tuition (~€175 bachelor / €250 master per year); UGA waives most of the non-EU differentiated fee for regular admits — effective cost ≈ €250–500/year.",
    opensMonth: 1,
    opensDay: 15,
    closesMonth: 4,
    closesDay: 20,
    cycleNote: "Parcoursup (bachelor): mid-Jan – mid-Mar. Mon Master: ~late Feb – late Apr. Eiffel nominations due early Jan.",
    moiAccepted: true,
    moiNote: "English-taught master's commonly accept MOI letters; French-taught degrees need B2 French (DELF/TCF or school certificate).",
    englishTests: "English MSc: IELTS ~6.0–6.5 or MOI letter; French degrees: TCF/DELF B2.",
    localLanguageRequired: true,
    localLanguageNote: "French B2 needed for French-taught programmes (most bachelor's); a growing English master's list needs no French.",
    recommendationsRequired: false,
    recommendationsNote: "Mon Master/Parcoursup need no letters; Eiffel nomination needs the institution's endorsement.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scans to the platforms; originals at registration.",
    essayRequired: true,
    essayNote: "Mon Master requires a motivation letter ('projet de formation') per programme.",
    applicationSteps: [
      { title: "Search Mon Master for UGA programmes", detail: "filter 'Université Grenoble Alpes' — see which are English-taught and which accept MOI proof." },
      { title: "Create your Mon Master account (free)", detail: "One account, up to 15 applications + 15 apprenticeship choices, all free." },
      { title: "Upload scans + motivation letter (Feb–Apr)", detail: "Transcript, diploma, ID, language proof, formation project letter per programme." },
      { title: "Receive proposals and confirm (Jun)", detail: "Ranking of offers arrives in June; confirm your top choice in the platform." },
      { title: "Ask UGA for the Eiffel nomination (Oct–Dec before)", detail: "Email the international relations office in autumn with your CV + grades — Eiffel (€1,181/month) is institution-nominated only." },
    ],
    requirementsSummary: "€0 via national platforms, motivation letter central, MOI route for English MSc, Eiffel possible.",
    eligibilityNote: "Bachelor's equivalent (licence access via Parcoursup needs secondary certificate); French B2 for French-taught.",
    officialUrl: "https://www.univ-grenoble-alpes.fr/english/",
    competitiveNote: "UGA is a top French public uni; English MSc in tech/energy are popular but less brutal than Paris.",
    successTips: "Grenoble is France's scholarship-friendliest public campus — always request the Eiffel nomination in November and apply for UGA's own Excellence scholarships after admission.",
  },
];
