import { SeedOpportunity } from "./seed-types";

/**
 * Free & low-cost ONLINE learning — degrees, master's, PhD-adjacent and
 * professional certificate programmes. kind: ONLINE_DEGREE | CERTIFICATE.
 * Every URL was HTTP-verified Oct 2026. Fees: tuition-free or ≤$30 application.
 */
export const ONLINE_SEED: SeedOpportunity[] = [
  // ── Tuition-free ONLINE DEGREES ────────────────────────────────────
  {
    name: "University of the People — Tuition-Free Online Degrees",
    slug: "uopeople-online",
    kind: "ONLINE_DEGREE",
    provider: "University of the People",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Pasadena, CA (fully online)",
    lat: 34.1478,
    lng: -118.1445,
    levels: ["undergraduate", "masters"],
    fields: ["computer science", "business & economics", "medicine & health", "education", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "No tuition at all. Only per-assessment fees (≈$140/course undergrad, ≈$300 grad) — scholarships & fee-waivers cover them for many students from low-income countries.",
    fundingType: "NO_TUITION",
    fundingNote: "US-accredited (DEAC) online university founded by Shai Reshef. Degree-seeking students pay assessment fees only; the UoPeople Fund covers them for learners who cannot pay.",
    rolling: true,
    cycleNote: "5 intakes per year — apply anytime for the next term",
    moiAccepted: true,
    moiNote: "English placement: you show English proficiency via prior English-medium education or take the free UoPeople English Composition course.",
    englishTests: "None required — free internal English placement path",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "Upload scanned proof of high-school completion at application; official documents due before graduation.",
    essayRequired: false,
    applicationSteps: [
      { title: "Create your application account", detail: "Go to uopeople.edu/apply and start the online application — it takes about 10 minutes and there is no application fee." },
      { title: "Prove high-school (or higher) completion", detail: "Upload a scan of your certificate/diploma or results slip. Unofficial scans are accepted to start; certified copies before graduating." },
      { title: "Show English readiness", detail: "Either prior English-medium schooling, or enroll in the university's free English Composition 1 course as your pathway." },
      { title: "Choose your degree & start date", detail: "Associate/Bachelor's in CS, Business Admin, Health Science, Education; MBA or M.Ed. online. Terms start ~5×/year." },
      { title: "Study — pay only assessment fees", detail: "Course materials are all open/free. If you can't afford the assessment fee, apply for one of the available scholarships during your studies." },
    ],
    requirementsSummary: "Proof of high-school completion + English readiness. No SAT, no tuition, no application fee.",
    eligibilityNote: "16+ years old, high-school proof, English. Open to every nationality — students from 200+ countries.",
    officialUrl: "https://www.uopeople.edu/",
    competitiveNote: "Not competitive on grades — it is admission-for-all; difficulty is in completing the free courses.",
    successTips: "Start with ONE course while working to learn the rhythm; assessment-fee scholarships are easier to get after your first term grades.",
  },
  {
    name: "International Open University — Tuition-Free Online Bachelor's & Master's",
    slug: "iou-online",
    kind: "ONLINE_DEGREE",
    provider: "International Open University",
    country: "The Gambia",
    countryCode: "gm",
    continent: "Africa",
    city: "Kanifing (fully online)",
    lat: 13.4531,
    lng: -16.7217,
    levels: ["undergraduate", "masters"],
    fields: ["education", "business & economics", "social sciences", "arts & humanities", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "$0 tuition — an affordable semester registration fee (about $50) applies, and fee-waivers are available for students who cannot pay.",
    fundingType: "NO_TUITION",
    fundingNote: "Accredited open university ( Gambian NAQAA + international partners) offering fully online bachelor's and master's degrees with open admission.",
    rolling: true,
    cycleNote: "Fall & Spring intakes, applications accepted year-round",
    moiAccepted: true,
    moiNote: "Entire platform teaches in English — no IELTS; you confirm English-medium background in the application.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "Scanned certificates accepted at registration.",
    essayRequired: false,
    applicationSteps: [
      { title: "Register online", detail: "Create an account at the IOU admissions portal — no fee to apply." },
      { title: "Upload your school-leaving certificate", detail: "WAEC/SSCE, diploma or equivalent scan is enough to begin." },
      { title: "Pick your programme", detail: "B.Ed., B.A. Islamic Studies, BBA, BSc Psychology, Arabic, MA programs — all online, all self-paced-friendly." },
      { title: "Confirm registration & pay (or request waiver)", detail: "Small per-semester registration fee; students with financial hardship request the waiver in the portal." },
    ],
    requirementsSummary: "School-leaving certificate scan + English. No entrance exam.",
    eligibilityNote: "Open admission worldwide; masters need a bachelor's in any field.",
    officialUrl: "https://www.iou.edu.gm/",
    successTips: "Semester registration has deadlines even though application is rolling — mark the intake dates in the tracker.",
  },
  {
    name: "Indira Gandhi National Open University (IGNOU) — World's Largest Open University",
    slug: "ignou-online",
    kind: "ONLINE_DEGREE",
    provider: "IGNOU",
    country: "India",
    countryCode: "in",
    continent: "Asia",
    city: "New Delhi (distance & online)",
    lat: 28.5219,
    lng: 77.2100,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any", "computer science", "business & economics", "social sciences", "education", "arts & humanities"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "No application charge for most programmes (online registration itself is free-to-nominal). Programme fees are famously low — many bachelor's tracks total under US$300 for the WHOLE degree; scholarships available.",
    fundingType: "NO_TUITION",
    fundingNote: "Central government university (UGC-recognized) with 4M+ students. BA/BCom/BSc/BCA, MBA, MCA, MA, MSc, and PhD through distance/online mode.",
    rolling: true,
    cycleNote: "January & July admission cycles each year (re-registration rolling)",
    moiAccepted: true,
    moiNote: "Study material in English (and Hindi) — no English test for admission.",
    englishTests: "None required for most programmes",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "Self-attested scans accepted; originals verified at regional centres.",
    essayRequired: false,
    applicationSteps: [
      { title: "Open the online admission portal", detail: "ignou.ac.in → 'Online Admission' during the Jan or July window." },
      { title: "Choose your programme", detail: "Filter by level & subject; each programme page lists its exact (tiny) fee and study format." },
      { title: "Upload ID + qualifying certificates", detail: "Scans of 10th/12th/bachelor certificates and ID — no attestation needed at upload stage." },
      { title: "Pay the low programme fee online", detail: "International students pay in INR equivalent via card; many programmes allow per-year payment." },
      { title: "Get study material & assignment schedule", detail: "eGyankosh gives all books free as PDFs; exams at accredited centres worldwide." },
    ],
    requirementsSummary: "Qualifying certificate scans + photo + ID. Admission is open, not competitive.",
    eligibilityNote: "Open to international students through the international admission portal; masters require a relevant bachelor's.",
    officialUrl: "https://ignou.ac.in/",
    successTips: "The July cycle has the widest programme choice; exam centres exist in 40+ countries, so you never travel to India.",
  },

  // ── Professional CERTIFICATES (free, with free certificates) ──────
  {
    name: "Google Digital Skills for Africa — Free Professional Certificates",
    slug: "google-digital-skills-africa",
    kind: "CERTIFICATE",
    provider: "Google (Grow with Google)",
    country: "Kenya",
    countryCode: "ke",
    continent: "Africa",
    city: "Nairobi hub (fully online)",
    lat: -1.2921,
    lng: 36.8219,
    levels: ["certificate"],
    fields: ["computer science", "business & economics", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "100% free courses AND free certificates of completion — no card required.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Google's flagship free training platform for Africa: digital marketing, data & tech, career development — self-paced, mobile-friendly, downloadable videos for low bandwidth.",
    rolling: true,
    cycleNote: "Always open — start any course instantly",
    moiAccepted: true,
    moiNote: "Taught in English (some courses in French) — no test needed.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Sign in with a Google account", detail: "grow.google/intl/africa — free Gmail account is the only requirement." },
      { title: "Pick a learning path", detail: "Fundamentals of Digital Marketing (26 modules, free certificate), Data & Tech tracks, or Career Development." },
      { title: "Complete the modules & quizzes", detail: "Progress saves automatically; videos download for offline study on slow connections." },
      { title: "Claim your certificate & badge", detail: "Pass the final assessment and the certificate is issued free — add it straight to LinkedIn." },
    ],
    requirementsSummary: "A Google account and internet. Nothing else.",
    eligibilityNote: "Learners across Africa (and worldwide) — no age or degree requirements.",
    officialUrl: "https://grow.google/intl/africa/",
    successTips: "The Fundamentals of Digital Marketing certificate is the most recognized by African employers — do it first.",
  },
  {
    name: "ALX Africa — Free Tech Career Programmes",
    slug: "alx-africa",
    kind: "CERTIFICATE",
    provider: "ALX (African Leadership Group)",
    country: "Rwanda",
    countryCode: "rw",
    continent: "Africa",
    city: "Kigali + Nairobi hubs (hybrid/online)",
    lat: -1.9441,
    lng: 30.0619,
    levels: ["certificate"],
    fields: ["computer science", "business & economics", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Fully sponsored for accepted learners (typical sponsorship value $5,000+) — you apply for free and pay nothing if selected.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "8-month bootcamp-style programmes: Software Engineering, Data Science/Analytics, AI Career Essentials, Cloud, Cybersecurity + professional foundations. Includes career coaching and employer network.",
    opensMonth: 1,
    closesMonth: 12,
    cycleNote: "Monthly cohorts — applications open year-round, seats fill fast",
    moiAccepted: true,
    moiNote: "English delivery; strong English recommended but no test certificate required.",
    englishTests: "None — short internal English check during admission",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "No degree required for most programmes — matric/high-school proof enough.",
    essayRequired: true,
    essayNote: "Short motivation answers in the application form — show commitment to 8 months of hard work.",
    applicationSteps: [
      { title: "Apply at alxafrica.com", detail: "Choose your programme (SE, Data, AI, Cloud…) and fill the short form — free, no documents needed at first." },
      { title: "Pass the readiness assessments", detail: "Timed quizzes on logic/numeracy + an English check — they filter for grit, not degrees." },
      { title: "Interview / motivation stage", detail: "Brief answers (or interview) about your time commitment — be honest about your weekly hours." },
      { title: "Confirm sponsorship & join a cohort", detail: "Accepted learners get full sponsorship; some hubs have in-person spaces (Kigali, Nairobi, etc.), all have online seats." },
    ],
    requirementsSummary: "Assessment-based admission — no degree required, documents uploaded only after selection.",
    eligibilityNote: "18-34 typical; unemployed/underemployed African youth prioritized for sponsorship.",
    officialUrl: "https://www.alxafrica.com/",
    competitiveNote: "Very popular — thousands apply per cohort; the readiness quizzes are the real filter.",
    successTips: "Practice basic mental math + logic before the assessment; state exactly why you need the sponsorship.",
  },
  {
    name: "FAO eLearning Academy — Free Certificates (UN Food & Agriculture)",
    slug: "fao-elearning",
    kind: "CERTIFICATE",
    provider: "Food and Agriculture Organization (UN)",
    country: "Italy",
    countryCode: "it",
    continent: "Europe",
    city: "Rome (fully online)",
    lat: 41.9053,
    lng: 12.4956,
    levels: ["certificate"],
    fields: ["agriculture & food", "environment", "development studies", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "All courses AND final digital certificates are completely free (digital badge included).",
    fundingType: "FULLY_FUNDED",
    fundingNote: "500+ multilingual e-learning courses on food security, nutrition, climate-smart agriculture, fisheries, forestry, rural development — created by a UN agency.",
    rolling: true,
    cycleNote: "Always open — self-paced",
    moiAccepted: true,
    moiNote: "Courses in English, French, Spanish, Arabic… — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Create your free learner profile", detail: "elearning.fao.org — sign up with email; profile takes 2 minutes." },
      { title: "Enroll in a course or learning pathway", detail: "Filter by theme (e.g. climate change, food safety, gender) or language." },
      { title: "Complete content + final quiz", detail: "Each course ends with an assessment — 80% to pass, unlimited retakes." },
      { title: "Download your certificate & digital badge", detail: "Issued instantly after passing — verifiable online." },
    ],
    requirementsSummary: "Just an email account.",
    eligibilityNote: "Open worldwide — popular with agriculture officers, NGOs and students.",
    officialUrl: "https://elearning.fao.org/",
    successTips: "Stack several certificates into a 'learning pathway' — FAO issues a bigger certificate for completed pathways.",
  },
  {
    name: "SAP Learning (OpenSAP legacy) — Free Enterprise-Tech Certificates",
    slug: "sap-learning",
    kind: "CERTIFICATE",
    provider: "SAP",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Walldorf (fully online)",
    lat: 49.2926,
    lng: 8.6396,
    levels: ["certificate"],
    fields: ["computer science", "business & economics", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Learning journeys free; confirmed achievement certificates issued free after course completion.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Free SAP software skills — the #1 ERP used by governments and multinationals. Analytics, S/4HANA, sustainability, AI — highly employable niche.",
    rolling: true,
    cycleNote: "Always open — self-paced learning journeys + scheduled live courses",
    moiAccepted: true,
    moiNote: "English — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Create a free SAP Learning account", detail: "learning.sap.com — one profile unlocks all learning journeys." },
      { title: "Choose a learning journey", detail: "Start with 'Discovering SAP' or pick your functional area (finance, supply chain, analytics)." },
      { title: "Complete knowledge checks", detail: "In-course quizzes — pass them to earn the free confirmed certificate/badge." },
      { title: "Optionally book the real SAP certification", detail: "The paid industry exam is optional; many employers accept the free confirmed certificates + skills for entry roles." },
    ],
    requirementsSummary: "Email account only.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://learning.sap.com/",
    successTips: "SAP consultants are in chronic shortage — one free journey + the badge gets interviews in East & West Africa's ERP job market.",
  },
  {
    name: "Elements of AI (University of Helsinki) — Free AI Certificate",
    slug: "elements-of-ai",
    kind: "CERTIFICATE",
    provider: "University of Helsinki + MinnaLearn",
    country: "Finland",
    countryCode: "fi",
    continent: "Europe",
    city: "Helsinki (fully online)",
    lat: 60.1699,
    lng: 24.9384,
    levels: ["certificate"],
    fields: ["computer science", "natural sciences", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free course AND free certificate (the EU-backed flagship that trained 1M+ Europeans).",
    fundingType: "FULLY_FUNDED",
    fundingNote: "The famous intro-to-AI course — no coding required. Follow with 'Building AI' for the technical track.",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English + 20 other EU languages.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Sign up at elementsofai.com", detail: "Email account only." },
      { title: "Work through 6 chapters", detail: "Exercises mix short maths-free reasoning with optional coding in Building AI." },
      { title: "Pass chapter exercises (50%+ overall)", detail: "Unlimited attempts; progress saved as you go." },
      { title: "Download the certificate", detail: "Free PDF certificate — used by ministries as digital-literacy proof." },
    ],
    requirementsSummary: "Email only.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://www.elementsofai.com/",
    successTips: "Perfect first certificate before applying to CS-related scholarships — admissions officers recognize it.",
  },
  {
    name: "Cisco Networking Academy — Free IT & Cybersecurity Certificates",
    slug: "cisco-netacad",
    kind: "CERTIFICATE",
    provider: "Cisco Networking Academy",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "San Jose, CA (fully online)",
    lat: 37.3382,
    lng: -121.8863,
    levels: ["certificate"],
    fields: ["computer science", "engineering", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Self-paced courses free; completion certificates & digital badges free. Discounted CCNA exam vouchers sometimes offered via academies.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Networking, cybersecurity (Cisco Certified Support Technician), Python, IoT — industry-grade content used by 40,000 academies worldwide.",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English (+ partner-language translations) — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Join via netacad.com", detail: "Free account; some instructor-led courses need a local academy — self-paced ones don't." },
      { title: "Pick a course path", detail: "Networking Basics → Cybersecurity Essentials → Python Essentials (with free badge each)." },
      { title: "Complete labs & final exam", detail: "Simulators run in-browser — no hardware needed." },
      { title: "Claim certificates/badges", detail: "Free completion certificate per course; Credly badges for LinkedIn." },
    ],
    requirementsSummary: "Email account only.",
    eligibilityNote: "Worldwide; strong employer recognition in networking roles.",
    officialUrl: "https://www.netacad.com/",
    successTips: "Cybersecurity path + free badge is the fastest route to junior SOC analyst interviews.",
  },
  {
    name: "IBM SkillsBuild — Free Digital Badges & Certificates",
    slug: "ibm-skillsbuild",
    kind: "CERTIFICATE",
    provider: "IBM",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Armonk, NY (fully online)",
    lat: 41.1242,
    lng: -73.7139,
    levels: ["certificate"],
    fields: ["computer science", "business & economics", "environment", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Completely free — courses, projects and Credly digital credentials with no charge.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "AI, cybersecurity, data analytics, cloud, sustainability + workplace skills. Credentials issued on Credly (IBM official).",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English (several partner translations) — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Register at skillsbuild.org", detail: "Email signup; choose learner profile." },
      { title: "Pick a learning track", detail: "Each track mixes short courses + hands-on web-based projects." },
      { title: "Finish track + project", detail: "Projects are auto/manual graded inside the platform." },
      { title: "Collect Credly badges", detail: "Verifiable IBM badges — share to LinkedIn directly." },
    ],
    requirementsSummary: "Email only.",
    eligibilityNote: "Worldwide; some regions get extra live coaching.",
    officialUrl: "https://skillsbuild.org/",
    successTips: "The AI fundamentals + cybersecurity tracks currently have the most job demand.",
  },
  {
    name: "Microsoft Learn & Virtual Training Days — Free Fundamentals Certification",
    slug: "microsoft-learn",
    kind: "CERTIFICATE",
    provider: "Microsoft",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Redmond, WA (fully online)",
    lat: 47.6423,
    lng: -122.1392,
    levels: ["certificate"],
    fields: ["computer science", "business & economics", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Learning paths free. Attend a free Microsoft Virtual Training Day (Fundamentals) and receive a FREE certification exam voucher — that makes the official Microsoft certificate itself free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Azure, AI, Data, Dynamics 365, security — the official Microsoft fundamentals credentials (AZ-900, AI-900, DP-900, SC-900, PL-900…).",
    rolling: true,
    cycleNote: "Training Days run weekly across time zones — incl. Africa/Asia sessions",
    moiAccepted: true,
    moiNote: "English + dozens of languages — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Learn free on Microsoft Learn", detail: "learn.microsoft.com/training — structured paths with sandbox labs, no payment." },
      { title: "Register for a Virtual Training Day", detail: "Choose your topic & time zone; two half-day online sessions." },
      { title: "Attend both sessions", detail: "Attendance tracked — you must join through your Microsoft account." },
      { title: "Redeem your free exam voucher", detail: "Voucher arrives by email — take AZ-900/AI-900 etc. online with a proctor at no cost." },
    ],
    requirementsSummary: "Microsoft account + attendance. No documents at all.",
    eligibilityNote: "Worldwide; students especially welcome.",
    officialUrl: "https://learn.microsoft.com/en-us/training/",
    successTips: "AZ-900 (Azure Fundamentals) is the most recognized — one weekend of Training Days = one free official certificate.",
  },
  {
    name: "AWS Educate — Free Cloud Training & Badges",
    slug: "aws-educate",
    kind: "CERTIFICATE",
    provider: "Amazon Web Services",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Seattle, WA (fully online)",
    lat: 47.6205,
    lng: -122.3493,
    levels: ["certificate"],
    fields: ["computer science", "engineering", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "AWS Educate is free — courses, labs and completion badges; no credit card needed.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Cloud fundamentals, machine learning, storage, security — with hands-on AWS console labs in-browser.",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Sign up at awseducate.com", detail: "Free account — 14+ welcome, no student email required (students and career-builders)." },
      { title: "Complete Cloud 101", detail: "Gateway course with badge — then pick ML, security or storage deeper paths." },
      { title: "Run the in-browser labs", detail: "Real AWS sandbox — zero cost to you." },
      { title: "Earn badges & build a portfolio", detail: "Badges share to LinkedIn; use labs as portfolio projects." },
    ],
    requirementsSummary: "Email only.",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://aws.amazon.com/educate/",
    successTips: "Pair AWS badge with any university application in CS — it shows practical initiative.",
  },
  {
    name: "Coursera Financial Aid — Free Professional Certificates (need-based)",
    slug: "coursera-financial-aid",
    kind: "CERTIFICATE",
    provider: "Coursera (Google, IBM, Meta, Microsoft partners)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Mountain View, CA (fully online)",
    lat: 37.4220,
    lng: -122.0841,
    levels: ["certificate", "undergraduate", "masters"],
    fields: ["any", "computer science", "business & economics", "social sciences"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Apply for Financial Aid on any course page — answer 2 short essays; approval in ~15 days makes the whole paid course + certificate free for you.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Google Data Analytics / IT Support / Cybersecurity, IBM Data Science, Meta Marketing — the famous job-ready certificates, free via aid.",
    rolling: true,
    cycleNote: "Aid applications accepted any day; each course needs its own application",
    moiAccepted: true,
    moiNote: "English (some courses subtitled) — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: true,
    essayNote: "The two aid essays: why you need aid + how the course helps your goals — 150 words each; be honest and specific.",
    applicationSteps: [
      { title: "Open the course page while logged in", detail: "Under Enroll, click 'Financial aid available' → Apply." },
      { title: "State your income & need", detail: "Answer annual-income and why-you-can't-pay fields honestly." },
      { title: "Write the two short essays", detail: "150 words each — how it helps your career, how it helps others. Concrete beats flowery." },
      { title: "Wait ~15 days for approval", detail: "Approved aid unlocks the full course + graded assignments + certificate for $0." },
    ],
    requirementsSummary: "Coursera account + 2 short essays per course.",
    eligibilityNote: "Anyone who cannot afford the fee — most applicants from developing countries are approved.",
    officialUrl: "https://www.coursera.org/",
    competitiveNote: "Aid is need-based, not competitive on grades.",
    successTips: "Apply for aid on the WHOLE certificate's courses in parallel (each course separately) so you finish without waiting gaps.",
  },
  {
    name: "edX Audit Track & Financial Assistance — Free Learning, 90% Off Certificates",
    slug: "edx-audit-aid",
    kind: "CERTIFICATE",
    provider: "edX (MIT, Harvard, Berkeley…)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Cambridge, MA (fully online)",
    lat: 42.3770,
    lng: -71.1167,
    levels: ["certificate", "undergraduate", "masters"],
    fields: ["any", "computer science", "engineering", "natural sciences", "business & economics"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Audit track of 2,500+ university courses is $0 forever. The optional verified certificate gets up to 90% off via edX Financial Assistance (per-course application).",
    fundingType: "PARTIAL",
    fundingNote: "MITx, HarvardX, CS50, BerkeleyX… — the highest-quality free STEM content on the internet.",
    rolling: true,
    cycleNote: "Self-paced courses always open; instructor-led run on schedules",
    moiAccepted: true,
    moiNote: "English — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: true,
    essayNote: "Short assistance essay: your circumstances + goals.",
    applicationSteps: [
      { title: "Choose a course and pick Audit", detail: "Audit = free access to all lectures/readings; upgrade is optional." },
      { title: "Apply for up to 90% assistance", detail: "On the upgrade screen, click 'Financial Assistance Application' — one short form + essay per course." },
      { title: "Wait up to 15 days", detail: "A 90% coupon makes a typical $99 certificate about $10 (often under $30). Audit stays free meanwhile." },
      { title: "Study & optionally claim certificate", detail: "CS50 and many others issue free certificates on OpenCourseWare even without upgrade." },
    ],
    requirementsSummary: "edX account; assistance needs one short essay per course.",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://www.edx.org/",
    successTips: "Harvard CS50x: the certificate is free via its own OpenCourseWare path — no payment at all.",
  },
  {
    name: "HP LIFE — Free Business & IT Certificates",
    slug: "hp-life",
    kind: "CERTIFICATE",
    provider: "HP Foundation",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Palo Alto, CA (fully online)",
    lat: 37.4419,
    lng: -122.1430,
    levels: ["certificate"],
    fields: ["business & economics", "computer science", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "All 30+ courses free with free certificates of completion.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Entrepreneurship, marketing, finance, digital business skills — designed for learners with slow connections; available in 8 languages.",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English, French, Spanish, Portuguese, Arabic, Chinese… — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Create a free account at life-global.org", detail: "2-minute signup." },
      { title: "Choose from 30+ business/IT courses", detail: "Each ~1 hour with a mini assessment." },
      { title: "Pass the course check", detail: "Simple quizzes reinforce the content." },
      { title: "Download your certificate", detail: "Free, printable, recognized by many youth-employment NGOs." },
    ],
    requirementsSummary: "Email only.",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://www.life-global.org/",
    successTips: "Perfect quick wins to fill a thin CV — do 3-4 relevant ones before scholarship interviews.",
  },
  {
    name: "Kaggle Learn — Free Data-Science Micro-Certificates",
    slug: "kaggle-learn",
    kind: "CERTIFICATE",
    provider: "Kaggle (Google)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "San Francisco, CA (fully online)",
    lat: 37.7749,
    lng: -122.4194,
    levels: ["certificate"],
    fields: ["computer science", "mathematics", "natural sciences", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "All micro-courses free, completion certificates free, plus free GPU/TPU compute for practice.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Python, pandas, ML, deep learning, data viz, SQL — 4-6 hours per course, hands-on notebooks.",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Make a free Kaggle account", detail: "Email or Google login." },
      { title: "Open kaggle.com/learn", detail: "Pick Python first if new; each course runs in browser notebooks — nothing to install." },
      { title: "Finish the exercises", detail: "Course exercises auto-graded; you keep the notebooks as portfolio." },
      { title: "Get completion certificates", detail: "Free PDF per course; strong notebooks become proof of skill." },
    ],
    requirementsSummary: "Email only.",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://www.kaggle.com/learn",
    successTips: "Enter one beginner competition after 3 courses — recruiters DO look at Kaggle profiles.",
  },
  {
    name: "Alison — Free Courses with Low-Cost Certificates",
    slug: "alison-courses",
    kind: "CERTIFICATE",
    provider: "Alison",
    country: "Ireland",
    countryCode: "ie",
    continent: "Europe",
    city: "Galway (fully online)",
    lat: 53.2707,
    lng: -9.0568,
    levels: ["certificate"],
    fields: ["any", "business & economics", "computer science", "medicine & health", "education"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "5,000+ courses 100% free to study and pass. Optional printed/digital certificates cost a small fee (the learning itself is always free) — many learners screenshot the free 'learner record' instead.",
    fundingType: "PARTIAL",
    fundingNote: "CPD-accredited workplace skills — project management, nursing basics, Excel, English grammar, workplace safety.",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English (some Irish/German courses) — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Register free at alison.com", detail: "Email signup." },
      { title: "Pick a CPD course", detail: "Filter by category & hours; check the 'certificate cost' note on the course page." },
      { title: "Score 80% in the assessment", detail: "Retakes allowed — the course itself never costs anything." },
      { title: "Get your learner record free", detail: "Show completion free of charge; only optional official certificates are paid." },
    ],
    requirementsSummary: "Email only.",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://alison.com/",
    successTips: "Use Alison for breadth; use Google/IBM/FAO (fully-free certificates) where the certificate itself matters.",
  },
  {
    name: "The Open University OpenLearn — Free Courses & Statements",
    slug: "openlearn-ou",
    kind: "CERTIFICATE",
    provider: "The Open University (UK)",
    country: "United Kingdom",
    countryCode: "gb",
    continent: "Europe",
    city: "Milton Keynes (fully online)",
    lat: 52.0246,
    lng: -0.7081,
    levels: ["certificate", "undergraduate"],
    fields: ["any", "social sciences", "education", "environment", "medicine & health"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "1,000+ short courses free; free 'statement of participation'/digital badge on many. Badged courses (e.g. forensic science, wellbeing) issue free digital badges.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Taster content from a world-class distance university — great for testing a field before committing to a degree application.",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Browse openlearn/free-courses", detail: "No account needed to learn; free OU account to collect badges." },
      { title: "Start with a 'badged' course", detail: "Badged courses = free digital credential with OU branding." },
      { title: "Complete the quizzes", detail: "Self-marked activities plus end-of-course quiz for badges." },
      { title: "Collect your badge/statement", detail: "Stored in your free OU profile, shareable." },
    ],
    requirementsSummary: "Free OU account (email).",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://www.open.edu/openlearn/free-courses",
    successTips: "Perfect pre-university taste-test: try 'Start writing fiction' or 'Managing my money' before applying.",
  },
  {
    name: "Stanford Online — Free Self-Paced Courses",
    slug: "stanford-online-free",
    kind: "CERTIFICATE",
    provider: "Stanford University",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Stanford, CA (fully online)",
    lat: 37.4275,
    lng: -122.1697,
    levels: ["certificate", "phd"],
    fields: ["computer science", "engineering", "medicine & health", "natural sciences", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "The 'Free Courses' catalogue (incl. several Stanford School of Engineering classics) is $0 to learn; statements of achievement on some courses free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Machine Learning (Andrew Ng legacy), cryptography, quantum, health — Stanford-level content, no paywall on the free tier.",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Go to online.stanford.edu/free-courses", detail: "Filter the FREE catalogue." },
      { title: "Enroll in the free tier", detail: "Some courses live on Stanford servers, some link to edX/ Coursera free-audit." },
      { title: "Study at your pace", detail: "Video lectures + readings; no application, no transcript needed." },
      { title: "Optional: pursue graded certificate", detail: "Paid 'professional certificate' tracks exist — skip or use partner financial aid if you only need learning." },
    ],
    requirementsSummary: "Account per hosting platform — no documents.",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://online.stanford.edu/free-courses",
    successTips: "List specific Stanford free courses (not just 'online courses') on your CV — names carry weight.",
  },
  {
    name: "MIT OpenCourseWare & MITx — Free MIT-Level Learning",
    slug: "mit-ocw",
    kind: "CERTIFICATE",
    provider: "Massachusetts Institute of Technology",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Cambridge, MA (fully online)",
    lat: 42.3601,
    lng: -71.0942,
    levels: ["certificate", "undergraduate", "masters", "phd"],
    fields: ["any", "computer science", "engineering", "mathematics", "natural sciences", "business & economics"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "OCW: 2,500+ full MIT courses, all materials free, no registration at all. MITx on edX: free audit; certificates via aid/upgrade.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "The gold standard for self-study — lecture notes, exams and solutions from actual MIT classes (6.0001 Python, 18.06 Linear Algebra…).",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Browse ocw.mit.edu", detail: "No account needed — download anything." },
      { title: "Follow a department path", detail: "e.g. Electrical Engineering → 6.0001 → 6.006 — mirrors the real MIT sequence." },
      { title: "Do the problem sets & exams", detail: "Solutions included — grade yourself honestly." },
      { title: "Optional MITx certificate", detail: "For verified proof, take the matching MITx course on edX (audit free; certificate via aid)." },
    ],
    requirementsSummary: "Nothing — not even an account on OCW.",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://ocw.mit.edu/",
    successTips: "Completing 2-3 named MIT courses with problem sets is a strong line in any scholarship 'academic preparation' section.",
  },
  {
    name: "Google AI Essentials & Career Certificates (Grow with Google)",
    slug: "google-career-certificates",
    kind: "CERTIFICATE",
    provider: "Google",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Mountain View, CA (fully online)",
    lat: 37.4220,
    lng: -122.0841,
    levels: ["certificate"],
    fields: ["computer science", "business & economics", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Google AI Essentials free tier available via partners; the full Career Certificates (Data Analytics, IT, Cybersecurity, PM, UX) are free through financial aid on Coursera and often 100% sponsored via libraries/workforce programs.",
    fundingType: "PARTIAL",
    fundingNote: "Employer-recognized credentials — Google marks them as 'considered in lieu of a 4-year degree' for related roles.",
    rolling: true,
    cycleNote: "Always open; sponsorship programs open in waves",
    moiAccepted: true,
    moiNote: "English (+ translations on some) — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Start on grow.google", detail: "Pick AI Essentials or a Career Certificate." },
      { title: "Check free sponsorship", detail: "Public libraries, workforce agencies and Google's own scholarship waves often give full access codes — always check before paying." },
      { title: "Or apply Coursera financial aid", detail: "For each course of the certificate (see the Coursera aid entry)." },
      { title: "Finish capstone & claim credential", detail: "Employer-recognized badge shared via Credly/Coursera." },
    ],
    requirementsSummary: "Google account; aid/sponsorship essays where needed.",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://grow.google/",
    successTips: "AI Essentials is the newest and least crowded — get it before everyone does.",
  },
  {
    name: "UN SDG:Learn — Free UN Sustainable-Development Courses",
    slug: "sdg-learn",
    kind: "CERTIFICATE",
    provider: "United Nations System Staff College & partners",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Bonn (UN campus, fully online)",
    lat: 50.7184,
    lng: 7.1215,
    levels: ["certificate"],
    fields: ["development studies", "environment", "public policy", "agriculture & food", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free aggregated learning from UN agencies — most constituent courses issue free certificates (e.g. UN CC:Learn climate badge).",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Climate change (UN CC:Learn), human rights, migration, procurement, sustainable finance — 1,000+ courses from 50+ UN partners.",
    rolling: true,
    cycleNote: "Always open",
    moiAccepted: true,
    moiNote: "English/French/Spanish by course — no test.",
    englishTests: "None",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: false,
    essayRequired: false,
    applicationSteps: [
      { title: "Create a free account on sdglearn.org", detail: "One login across UN partner platforms." },
      { title: "Pick courses matching your field", detail: "e.g. climate policy for environmental scholarships — coherence matters." },
      { title: "Complete partner-course quizzes", detail: "Certificates issued by the running agency (UNITAR, FAO, ITU…)." },
      { title: "Build a UN-themed certificate portfolio", detail: "Perfect supporting evidence for development-studies scholarship applications." },
    ],
    requirementsSummary: "Email only.",
    eligibilityNote: "Worldwide.",
    officialUrl: "https://sdglearn.org/",
    successTips: "For Commonwealth/DAAD-type development scholarships, 2-3 UN certificates on climate or gender signal genuine commitment.",
  },
  {
    name: "Université Virtuelle du Sénégal (UVS) — Affordable Public Online University",
    slug: "uvs-senegal",
    kind: "ONLINE_DEGREE",
    provider: "Republic of Senegal (Ministry of Higher Education)",
    country: "Senegal",
    countryCode: "sn",
    continent: "Africa",
    city: "Dakar (fully online)",
    lat: 14.7167,
    lng: -17.4677,
    levels: ["undergraduate", "masters"],
    fields: ["computer science", "business & economics", "law", "education", "any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "State online university — registration extremely low (tens of thousands CFA francs/year ≈ $30-90) vs classic universities; scholarships for top students.",
    fundingType: "NO_TUITION",
    fundingNote: "Government-run virtual university with recognized degrees (CAMES-aligned) — French & English tracks for some programmes.",
    opensMonth: 8,
    closesMonth: 11,
    cycleNote: "Main intake each fall; check portal for the current year's window",
    moiAccepted: true,
    moiNote: "French primary; English-track programmes available — no IELTS.",
    englishTests: "None required",
    localLanguageRequired: true,
    localLanguageNote: "Most programmes taught in French — plan a French pathway if needed.",
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "Scanned bac/certificates accepted at registration; originals verified later.",
    essayRequired: false,
    applicationSteps: [
      { title: "Create an account on uvs.sn", detail: "Admission portal opens toward the end of each year for the next academic year." },
      { title: "Upload bac/equivalent scan", detail: "WAEC holders may need equivalence — the portal guides translation/legalisation." },
      { title: "Choose licence/master programme", detail: "CS, business, law, education… mostly French-language." },
      { title: "Pay the small registration & study", detail: "Digital campus, online exams, degree identical in standing to on-campus Senegalese universities." },
    ],
    requirementsSummary: "Bac-level certificate scan + ID.",
    eligibilityNote: "Open to Africans and beyond; French required for most tracks.",
    officialUrl: "https://www.uvs.sn/",
    successTips: "If you speak French, UVS is one of the cheapest accredited paths to a recognized degree on the continent.",
  },
];
