import { SeedOpportunity } from "./seed-types";

/**
 * Accredited professional certificates — issued by universities, industry
 * standards bodies and institutions employers actually respect.
 * kind: CERTIFICATE · every URL verified Oct 2026.
 *
 * Covers the areas users asked for: software engineering, aviation
 * (cabin crew / air hostess, airports), communications, data & AI,
 * cybersecurity, project management — plus 100% free routes where they exist.
 */
export const CERTS_SEED: SeedOpportunity[] = [
  // ── SOFTWARE ENGINEERING (100% free) ────────────────────────────────
  {
    name: "Harvard CS50x — Introduction to Computer Science (free certificate)",
    slug: "harvard-cs50x",
    kind: "CERTIFICATE",
    provider: "Harvard University (CS50)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Cambridge, MA (online)",
    lat: 42.377,
    lng: -71.117,
    levels: ["certificate"],
    fields: ["computer science", "software engineering", "data & ai", "information technology"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "100% free — all lectures, problem sets and the final CS50 certificate from Harvard are free. The optional edX 'verified' certificate is the only paid part, and you never need it.",
    fundingType: "NO_TUITION",
    fundingNote: "Harvard's flagship intro course, open to the world. A CS50 certificate carries real weight with employers — Harvard itself issues it for free.",
    rolling: true,
    cycleNote: "Self-paced — start any week, work at your own speed",
    moiAccepted: true,
    moiNote: "All materials are in English with subtitles — no English test is ever asked.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "No transcripts at all — open to everyone with internet.",
    essayRequired: false,
    applicationSteps: [
      { title: "Enroll free at cs50.harvard.edu/x", detail: "Create a free edX account and enroll in audit mode — or use CS50's own site which tracks everything without edX." },
      { title: "Work through 9 problem sets", detail: "Hands-on programming in C, Python, SQL and web (HTML/CSS/JavaScript/Flask). Weeks 0-9, each pset graded automatically." },
      { title: "Build your final project", detail: "Anything you want — a website, app, or tool — and publish it with a short write-up." },
      { title: "Claim your free CS50 certificate", detail: "cs50.me issues your Harvard CS50 certificate (free PDF with a verifiable URL) the moment you finish." },
    ],
    requirementsSummary: "A laptop + internet. No application, no fee, no English test, no prior coding.",
    eligibilityNote: "Open to every nationality and age — most students worldwide are first-time programmers.",
    officialUrl: "https://cs50.harvard.edu/x/",
    competitiveNote: "Not competitive — completion is the filter. Employers respect it because the problem sets are genuinely hard.",
    successTips: "Finish CS50P (Python) first if C feels heavy — both are free and either alone earns a certificate.",
  },
  {
    name: "freeCodeCamp — Full Curriculum Developer Certifications (100% free)",
    slug: "freecodecamp-certifications",
    kind: "CERTIFICATE",
    provider: "freeCodeCamp (US 501(c)(3) nonprofit)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Fully online",
    lat: 37.7749,
    lng: -122.4194,
    levels: ["certificate"],
    fields: ["software engineering", "information technology", "data & ai"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Everything free forever — no paywall at any stage, certificates included. A donor-supported nonprofit.",
    fundingType: "NO_TUITION",
    fundingNote: "Responsive Web Design, JavaScript Algorithms, Front-End Libraries, Data Visualization, APIs & Microservices, Machine Learning with Python, Data Analysis — each with a portfolio project and a free verified certificate.",
    rolling: true,
    cycleNote: "Self-paced — instant start",
    moiAccepted: true,
    moiNote: "English curriculum with community forums in dozens of languages.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "No transcripts — account creation is the only requirement.",
    essayRequired: false,
    applicationSteps: [
      { title: "Create a free account", detail: "freecodecamp.org — sign up with email or GitHub in under a minute." },
      { title: "Pick your certification track", detail: "Responsive Web Design or JavaScript Algorithms is the classic first pair for software engineering." },
      { title: "Complete the interactive challenges", detail: "300 hours of hands-on coding in the browser — no setup needed, works on low-end laptops." },
      { title: "Build the 5 required projects", detail: "Each certification ends with real portfolio projects — these are what you show employers." },
      { title: "Claim your verified certificate", detail: "freeCodeCamp issues a free verifiable certificate URL you can add to LinkedIn and CVs." },
    ],
    requirementsSummary: "Just internet access. Everything runs in the browser.",
    eligibilityNote: "Anyone, any country — used by millions of self-taught developers.",
    officialUrl: "https://www.freecodecamp.org/learn",
    competitiveNote: "Not competitive — the portfolio projects are your real credential.",
    successTips: "Join the freeCodeCamp forum + local study group; the projects double as your first portfolio site.",
  },
  {
    name: "The Odin Project — Open-Source Full-Stack Curriculum (100% free)",
    slug: "odin-project-fullstack",
    kind: "CERTIFICATE",
    provider: "The Odin Project (open source)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Fully online",
    lat: 37.0902,
    lng: -95.7129,
    levels: ["certificate"],
    fields: ["software engineering", "information technology"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "100% free and open source — the full curriculum, community and support cost nothing.",
    fundingType: "NO_TUITION",
    fundingNote: "A full-stack path (HTML/CSS → JavaScript → React → Node.js or Ruby on Rails) built around real projects and a public GitHub profile — exactly what hiring managers review.",
    rolling: true,
    cycleNote: "Self-paced — instant start",
    moiAccepted: true,
    moiNote: "English curriculum; very active Discord community.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None — open curriculum.",
    essayRequired: false,
    applicationSteps: [
      { title: "Start at theodinproject.com", detail: "Choose the Full Stack JavaScript path (or Rails) — 'Introduction' sets up your computer step by step." },
      { title: "Learn by building", detail: "Every module ends with real projects: landing pages, to-do apps, REST APIs, a full social network clone." },
      { title: "Push everything to GitHub", detail: "The curriculum trains you to commit daily — your profile becomes your proof of skill." },
      { title: "Finish with portfolio + job prep", detail: "The final section covers CVs, portfolios and interview prep, all free." },
    ],
    requirementsSummary: "A computer (Windows/Mac/Linux) + internet + discipline.",
    eligibilityNote: "Open worldwide — no account gates on the curriculum itself.",
    officialUrl: "https://www.theodinproject.com/",
    competitiveNote: "Not competitive — completing the full path puts you ahead of most bootcamp graduates.",
    successTips: "Do NOT skip the projects. They are the certificate employers actually look at.",
  },

  // ── AVIATION: CABIN CREW / AIR HOSTESS / AIRPORTS (IATA) ────────────
  {
    name: "IATA Cabin Crew Course — Airline-Recognised Flight Attendant Training",
    slug: "iata-cabin-crew",
    kind: "CERTIFICATE",
    provider: "IATA (International Air Transport Association)",
    country: "Canada",
    countryCode: "ca",
    continent: "North America",
    city: "Montreal (self-study online / partner schools)",
    lat: 45.5017,
    lng: -73.5673,
    levels: ["certificate"],
    fields: ["aviation & hospitality", "communications & media"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: false,
    feeUsdApprox: 0,
    feeNote: "Course fees vary by format (self-study e-learning is the cheapest, typically a few hundred USD). IATA is the global airline industry body — its aviation certificates are recognised by airlines worldwide.",
    fundingType: "SELF_FUNDED",
    fundingNote: "The most employer-recognised aviation training body on earth: IATA certificates appear on airline job requirements everywhere. Some IATA Authorised Training Centres offer instalment plans.",
    rolling: true,
    cycleNote: "Self-study starts anytime; classroom editions follow partner-school calendars",
    moiAccepted: true,
    moiNote: "Course is in English; airlines require fluent English plus often a second language for cabin crew.",
    englishTests: "None required for the course itself (fluency expected by airlines)",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "High-school completion is the usual baseline airlines ask for.",
    essayRequired: false,
    applicationSteps: [
      { title: "Open the IATA training catalogue", detail: "Go to iata.org → Training → search 'Cabin Crew' to see current formats, dates and exact fees." },
      { title: "Choose self-study e-learning or a partner school", detail: "Self-study lets you start today from anywhere; Authorised Training Centres add practical sessions." },
      { title: "Register and pay securely online", detail: "Create an IATA Training account, enroll, and pay (instalments sometimes available via partners)." },
      { title: "Complete the course modules", detail: "Safety & emergency procedures, service delivery, aviation security, first-aid awareness, crew responsibilities." },
      { title: "Pass the exam and receive your IATA certificate", detail: "The certificate is verifiable and goes straight on your airline applications." },
      { title: "Apply to airline cabin-crew recruitments", detail: "Meet airline basics: 18+, high-school diploma, reach/height rules, swimming, fluent English." },
    ],
    requirementsSummary: "High-school completion, English fluency, 18+ by airline hiring rules. IATA course itself has no entry exam.",
    eligibilityNote: "Open to all nationalities — airlines each set their own hiring criteria (height reach, swimming, languages).",
    officialUrl: "https://www.iata.org/en/training/courses/",
    competitiveNote: "The certificate is respected everywhere; airline selection itself is competitive — presentation, languages and service experience matter.",
    successTips: "Pair the certificate with a customer-service job or volunteering — recruiters weigh service experience heavily.",
  },
  {
    name: "IATA Airport Operations & Passenger Service Certificates",
    slug: "iata-airport-operations",
    kind: "CERTIFICATE",
    provider: "IATA (International Air Transport Association)",
    country: "Canada",
    countryCode: "ca",
    continent: "North America",
    city: "Montreal (self-study online / partner schools)",
    lat: 45.5017,
    lng: -73.5673,
    levels: ["certificate"],
    fields: ["aviation & hospitality", "business & economics"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: false,
    feeUsdApprox: 0,
    feeNote: "Fees vary by course and format — the catalogue shows exact prices. Recognised by ground handlers, airlines and airport authorities globally.",
    fundingType: "SELF_FUNDED",
    fundingNote: "Covers Airport Operations Foundation, Passenger Ground Services, Aviation Security awareness — the standard entry path into airport ground careers.",
    rolling: true,
    cycleNote: "Self-study starts anytime",
    moiAccepted: true,
    moiNote: "English course materials.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None for foundation-level courses.",
    essayRequired: false,
    applicationSteps: [
      { title: "Browse the IATA catalogue", detail: "iata.org → Training → 'Airport, Passenger, Security & Ground Services' category." },
      { title: "Pick your course", detail: "Passenger Ground Services and Airport Operations Foundation are the classic entry pair." },
      { title: "Enroll online and study at your pace", detail: "E-learning with tutor support over several weeks." },
      { title: "Sit the exam and download your IATA certificate", detail: "Add it to your CV for ground-handling and airport authority applications." },
    ],
    requirementsSummary: "No prerequisites for foundation courses; English reading fluency.",
    eligibilityNote: "Open worldwide — ideal for airport/airline ground-career starters.",
    officialUrl: "https://www.iata.org/en/training/courses/",
    competitiveNote: "Foundation certificates are open-enrolment; airport employers value them + customer-service history.",
    successTips: "Passenger Ground Services + a language skill is a strong combo for international airports.",
  },

  // ── CYBERSECURITY ───────────────────────────────────────────────────
  {
    name: "ISC2 Certified in Cybersecurity (CC) — free official training",
    slug: "isc2-cc",
    kind: "CERTIFICATE",
    provider: "ISC2 (International Information Security Certification Consortium)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Alexandria, VA (online + PearsonVUE test centres)",
    lat: 38.8048,
    lng: -77.0469,
    levels: ["certificate"],
    fields: ["cybersecurity", "information technology"],
    feeAmount: 199,
    feeCurrency: "USD",
    feeConfirmedFree: false,
    feeUsdApprox: 199,
    feeNote: "Official self-paced training is 100% free. The certification exam is USD 199 — but ISC2's 'One Million Certified in Cybersecurity' programme frequently issues FREE exam vouchers, so check the page first.",
    fundingType: "PARTIAL",
    fundingNote: "The only entry-level cert backed by ISC2, the world's largest security certification body (CISSP's issuer) — employers know it instantly.",
    rolling: true,
    cycleNote: "Self-paced training anytime; exams year-round",
    moiAccepted: true,
    moiNote: "English exam (translated versions exist for some languages).",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "No degree needed — no prerequisites at all.",
    essayRequired: false,
    applicationSteps: [
      { title: "Create a free ISC2 account", detail: "isc2.org → Certifications → CC → 'Self-Paced Training' — free with registration." },
      { title: "Check for a free exam voucher", detail: "Join the 1MCC programme when open — it has already put free training + exam vouchers in students' hands worldwide." },
      { title: "Complete the 5 domains", detail: "Security principles, business continuity, access controls, network security, security operations." },
      { title: "Book the exam (online proctored or test centre)", detail: "100 questions, 2 hours — schedule through PearsonVUE when you score well on practice." },
      { title: "Get certified and stay member", detail: "Passing earns the CC designation; annual maintenance is low-cost and ISC2 runs free CPD events." },
    ],
    requirementsSummary: "No experience or degree required — this is the designed entry point into cybersecurity.",
    eligibilityNote: "Open to all nationalities; online proctoring available in most countries.",
    officialUrl: "https://www.isc2.org/certifications/cc",
    competitiveNote: "Open-enrolment exam — respected because it is ANSI/ISO-accredited and issued by ISC2.",
    successTips: "The free official course alone can be enough to pass; do the practice questions twice.",
  },

  // ── DATA & AI ───────────────────────────────────────────────────────
  {
    name: "MITx MicroMasters — Statistics and Data Science (free to learn)",
    slug: "mitx-micromasters-sds",
    kind: "CERTIFICATE",
    provider: "Massachusetts Institute of Technology (MITx on edX)",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Cambridge, MA (online)",
    lat: 42.3601,
    lng: -71.0942,
    levels: ["certificate"],
    fields: ["data & ai", "mathematics", "computer science"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: false,
    feeUsdApprox: 0,
    feeNote: "All MITx courses are free to learn in audit mode. Only the optional proctored exams for the MicroMasters credential cost money (~USD 1,500 total). Many learners complete the courses free and never pay.",
    fundingType: "PARTIAL",
    fundingNote: "Graduate-level MIT content: probability, statistics, machine learning, capstone. The credential can ladder into MIT's blended master's — but the free-track certificates per course are already powerful proof.",
    rolling: true,
    cycleNote: "Courses run on session calendars several times a year (audit anytime in archive mode)",
    moiAccepted: true,
    moiNote: "English materials; transcripts of video available.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "Undergraduate calculus + linear algebra recommended knowledge.",
    essayRequired: false,
    applicationSteps: [
      { title: "Open the certificate page on Coursera", detail: "coursera.org → search 'MITx Statistics and Data Science MicroMasters' or go to micromasters.mit.edu/ds/." },
      { title: "Audit each course free", detail: "Choose the free audit track for Probability, Statistics, Machine Learning with Python and the Capstone." },
      { title: "Do the real problem sets", detail: "Same assignments MIT graduate students get — this is what makes the credential respected." },
      { title: "Optional: pay for proctored exams", detail: "Only if you want the MicroMasters credential itself; otherwise course certificates from the free track (where offered) + your projects already demonstrate skill." },
      { title: "Use it", detail: "Apply the capstone project in job applications, or ladder the credential into a blended master's pathway." },
    ],
    requirementsSummary: "Calculus and basic Python. No application, no English test.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://micromasters.mit.edu/ds/",
    competitiveNote: "The learning is free and open; respect comes from the difficulty of the content itself.",
    successTips: "Pair with free Kaggle competitions — MIT content + Kaggle rank is a job-ready portfolio.",
  },
  {
    name: "Google Data Analytics Professional Certificate (Coursera financial aid)",
    slug: "google-data-analytics",
    kind: "CERTIFICATE",
    provider: "Google · Coursera",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Mountain View, CA (online)",
    lat: 37.422,
    lng: -122.0841,
    levels: ["certificate"],
    fields: ["data & ai", "business & economics"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free to audit. The paid certificate (≈$49/month) becomes FREE via Coursera Financial Aid — apply on the course page (two short essays), approved in ~15 days. Apply per course, 8 courses total.",
    fundingType: "PARTIAL",
    fundingNote: "One of the most recognised entry-level data credentials with a huge employer consortium (Google, Deloitte, Bayer and more).",
    rolling: true,
    cycleNote: "Self-paced — instant start",
    moiAccepted: true,
    moiNote: "English with subtitles in many languages including French, Portuguese, Vietnamese.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None — open enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Open the certificate page on Coursera", detail: "coursera.org/professional-certificates/google-data-analytics → Enroll for free." },
      { title: "Apply for Financial Aid on course 1", detail: "Click 'Financial aid available' under the Enroll button — answer the two questions honestly (income + how it helps your career)." },
      { title: "Wait ~15 days, then start free", detail: "Once approved, every graded item in that course unlocks free — repeat the aid application for the remaining courses." },
      { title: "Learn spreadsheets, SQL, R and Tableau", detail: "Hands-on with case studies; keep the artifacts for your portfolio." },
      { title: "Earn the certificate and share it", detail: "Add the verifiable URL to LinkedIn; use Google's employer consortium job boards." },
    ],
    requirementsSummary: "No degree, no experience — designed for absolute beginners.",
    eligibilityNote: "Financial aid is open to learners in most countries — this is the standard free route.",
    officialUrl: "https://www.coursera.org/professional-certificates/google-data-analytics",
    competitiveNote: "Open enrolment; recognised because of Google's brand + the employer consortium.",
    successTips: "Write the aid essays yourself and specifically — approvals are near-automatic for honest need.",
  },

  // ── SOFTWARE ENGINEERING (university + industry backed) ─────────────
  {
    name: "University of Michigan — Python 3 Programming Specialization",
    slug: "umich-python3",
    kind: "CERTIFICATE",
    provider: "University of Michigan · Coursera",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Ann Arbor, MI (online)",
    lat: 42.278,
    lng: -83.738,
    levels: ["certificate"],
    fields: ["software engineering", "computer science", "data & ai"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free to audit; the certificate is FREE via Coursera Financial Aid (apply per course, ~15-day approval). One of the highest-rated Python sequences ever made.",
    fundingType: "PARTIAL",
    fundingNote: "A top public US university teaches this — 'Python for Everybody' grew out of it and is the world's most-taken Python course.",
    rolling: true,
    cycleNote: "Self-paced — instant start",
    moiAccepted: true,
    moiNote: "English with subtitles in many languages.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None.",
    essayRequired: false,
    applicationSteps: [
      { title: "Enroll in audit mode", detail: "coursera.org → search 'Python 3 Programming Specialization' → Enroll → Audit." },
      { title: "Apply for Financial Aid per course", detail: "Five courses; submit the short aid application on each and start the free path." },
      { title: "Work through the projects", detail: "Text processing, web data with regex, SQL + Python, data visualisation with pygal." },
      { title: "Collect your university-backed certificate", detail: "Share the verifiable certificate on LinkedIn/CV." },
    ],
    requirementsSummary: "None — starts from zero programming.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://www.coursera.org/specializations/python-3-programming",
    competitiveNote: "Open enrolment — the University of Michigan name carries the weight.",
    successTips: "Finish 'Python for Everybody' courses 1-2 first inside this specialization — same professors.",
  },
  {
    name: "Meta Back-End Developer Professional Certificate",
    slug: "meta-back-end-developer",
    kind: "CERTIFICATE",
    provider: "Meta · Coursera",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Menlo Park, CA (online)",
    lat: 37.4852,
    lng: -122.1476,
    levels: ["certificate"],
    fields: ["software engineering", "information technology"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free to audit; certificate FREE via Coursera Financial Aid (per-course application, ~15 days).",
    fundingType: "PARTIAL",
    fundingNote: "Built by Meta engineers: Python, Django, REST APIs, MySQL, and thecoding interview prep that Meta actually uses.",
    rolling: true,
    cycleNote: "Self-paced",
    moiAccepted: true,
    moiNote: "English with subtitles.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None.",
    essayRequired: false,
    applicationSteps: [
      { title: "Enroll free on Coursera", detail: "coursera.org/professional-certificates/meta-back-end-developer." },
      { title: "Apply for Financial Aid per course", detail: "12 courses; approve-and-start flow takes about 15 days each — apply to the next course while studying the current one." },
      { title: "Build the API capstone", detail: "A Django REST API with MySQL — deploy it publicly and link it on your CV." },
      { title: "Use Meta's interview prep + job boards", detail: "The certificate includes coding-interview practice and connects to Meta's hiring ecosystem." },
    ],
    requirementsSummary: "Basic programming comfort helps; no degree needed.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://www.coursera.org/professional-certificates/meta-back-end-developer",
    competitiveNote: "Open enrolment; recognised for Meta's engineering brand and practical content.",
    successTips: "Combine with freeCodeCamp projects — Meta cert teaches, your GitHub proves.",
  },
  {
    name: "Google IT Automation with Python Professional Certificate",
    slug: "google-it-automation",
    kind: "CERTIFICATE",
    provider: "Google · Coursera",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Mountain View, CA (online)",
    lat: 37.422,
    lng: -122.0841,
    levels: ["certificate"],
    fields: ["software engineering", "information technology"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free to audit; certificate FREE via Coursera Financial Aid (per-course, ~15 days).",
    fundingType: "PARTIAL",
    fundingNote: "The follow-up to Google IT Support — Python, Git, troubleshooting at scale. Direct pipeline into IT/software-adjacent roles.",
    rolling: true,
    cycleNote: "Self-paced",
    moiAccepted: true,
    moiNote: "English with subtitles in many languages.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None.",
    essayRequired: false,
    applicationSteps: [
      { title: "Enroll and audit free", detail: "coursera.org/professional-certificates/google-it-automation." },
      { title: "Apply for Financial Aid per course", detail: "6 courses — the honest-need essays approve in about 15 days." },
      { title: "Automate real tasks", detail: "Write Python scripts that manage files, pull web data, interact with cloud resources." },
      { title: "Earn the certificate", detail: "Add to LinkedIn; Google's consortium employers recognise it directly." },
    ],
    requirementsSummary: "None — IT basics taught inside.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://www.coursera.org/professional-certificates/google-it-automation",
    competitiveNote: "Open enrolment.",
    successTips: "Do Google IT Support first (also aid-free) if computers are new to you.",
  },

  // ── COMMUNICATIONS & MEDIA (industry + university-backed) ───────────
  {
    name: "Google Digital Marketing & E-commerce Professional Certificate",
    slug: "google-digital-marketing",
    kind: "CERTIFICATE",
    provider: "Google · Coursera",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Mountain View, CA (online)",
    lat: 37.422,
    lng: -122.0841,
    levels: ["certificate"],
    fields: ["communications & media", "business & economics", "information technology"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free to audit; the paid certificate becomes FREE via Coursera Financial Aid (two-question application per course, approved in ~15 days).",
    fundingType: "PARTIAL",
    fundingNote: "7 courses covering social media strategy, email marketing, SEO, analytics and e-commerce stores — one of the most recognised entry credentials in digital communications.",
    rolling: true,
    cycleNote: "Self-paced — instant start",
    moiAccepted: true,
    moiNote: "English with subtitles in many languages.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None — open enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Open the certificate page on Coursera", detail: "coursera.org/professional-certificates/google-digital-marketing-ecommerce → Enroll for free." },
      { title: "Apply for Financial Aid on course 1", detail: "Click 'Financial aid available' — answer honestly; approval takes about 15 days." },
      { title: "Start free and apply aid course-by-course", detail: "7 courses total — submit the next aid application while finishing the current course so you never wait." },
      { title: "Build real artifacts", detail: "A social campaign, an email sequence, an online storefront — all portfolio pieces." },
      { title: "Earn the certificate", detail: "Verifiable URL for LinkedIn/CV; recognised across Google's employer consortium." },
    ],
    requirementsSummary: "None — designed for beginners in marketing/communications.",
    eligibilityNote: "Open worldwide; financial aid is the standard free route.",
    officialUrl: "https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce",
    competitiveNote: "Open enrolment; recognised for Google's brand + hands-on tool practice.",
    successTips: "Run the course projects on a real page/cause you own — live results impress employers far more than the badge.",
  },
  {
    name: "Digital Marketing — University of Illinois Urbana-Champaign Specialization",
    slug: "illinois-digital-marketing",
    kind: "CERTIFICATE",
    provider: "University of Illinois · Coursera",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Urbana, IL (online)",
    lat: 40.102,
    lng: -88.2272,
    levels: ["certificate"],
    fields: ["communications & media", "business & economics"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free to audit; certificate FREE via Coursera Financial Aid (per-course application).",
    fundingType: "PARTIAL",
    fundingNote: "From a top-5 US advertising faculty: marketing in a digital world, analytics, SEO/social, and marketing strategy — 7 courses, credit-bearing toward their IMC master's.",
    rolling: true,
    cycleNote: "Self-paced",
    moiAccepted: true,
    moiNote: "English with subtitles.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None.",
    essayRequired: false,
    applicationSteps: [
      { title: "Enroll free on Coursera", detail: "Search 'Digital Marketing University of Illinois'." },
      { title: "Apply for Financial Aid per course", detail: "7 courses — apply to the next while finishing the current one." },
      { title: "Complete the applied projects", detail: "Real campaign briefs and analytics exercises you can show employers." },
      { title: "Earn the certificate", detail: "University-backed credential; courses carry credit toward the Illinois MS in strategic communication if you continue." },
    ],
    requirementsSummary: "None.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://www.coursera.org/specializations/digital-marketing",
    competitiveNote: "Open enrolment — Illinois' advertising programme is one of the oldest and most respected in the US.",
    successTips: "Run the capstone on your own social project — real numbers beat certificates.",
  },

  // ── BUSINESS / MANAGEMENT ───────────────────────────────────────────
  {
    name: "Google Project Management Professional Certificate",
    slug: "google-project-management",
    kind: "CERTIFICATE",
    provider: "Google · Coursera",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Mountain View, CA (online)",
    lat: 37.422,
    lng: -122.0841,
    levels: ["certificate"],
    fields: ["business & economics", "public policy", "communications & media"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free to audit; certificate FREE via Coursera Financial Aid (per-course, ~15 days).",
    fundingType: "PARTIAL",
    fundingNote: "6 courses covering Agile, Scrum, stakeholder management and capstone — plus prep materials for the PMI CAPM certification.",
    rolling: true,
    cycleNote: "Self-paced",
    moiAccepted: true,
    moiNote: "English with subtitles in many languages.",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None.",
    essayRequired: false,
    applicationSteps: [
      { title: "Enroll and audit free", detail: "coursera.org/professional-certificates/google-project-management." },
      { title: "Apply for Financial Aid per course", detail: "6 courses; ~15-day approval each." },
      { title: "Build the capstone charter + plan", detail: "A real project charter, schedule and budget you can reuse at work." },
      { title: "Earn the certificate + CAPM path", detail: "Certificate lands on LinkedIn; CAPM prep materials included for the PMI exam." },
    ],
    requirementsSummary: "None.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://www.coursera.org/professional-certificates/google-project-management",
    competitiveNote: "Open enrolment.",
    successTips: "Document any community project you manage as the capstone — instant interview story.",
  },

  // ── DEVELOPMENT / POLICY (university & institution backed) ──────────
  {
    name: "World Bank Group Open Learning Campus — free development certificates",
    slug: "wbg-open-learning",
    kind: "CERTIFICATE",
    provider: "World Bank Group",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Washington, DC (online)",
    lat: 38.8977,
    lng: -77.0365,
    levels: ["certificate"],
    fields: ["development studies", "public policy", "business & economics", "environment", "energy"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Free — most self-paced courses issue a completion certificate at no cost.",
    fundingType: "NO_TUITION",
    fundingNote: "The World Bank's own learning platform: climate, public finance, health systems, data for development — courses taught by the people who run the programmes.",
    rolling: true,
    cycleNote: "Self-paced — instant start",
    moiAccepted: true,
    moiNote: "English (some courses in French/Spanish/Arabic).",
    englishTests: "None required",
    localLanguageRequired: false,
    recommendationsRequired: false,
    unofficialTranscripts: true,
    transcriptsNote: "None.",
    essayRequired: false,
    applicationSteps: [
      { title: "Create a free OLC account", detail: "olc.worldbank.org — register with your email." },
      { title: "Pick WB Academy self-paced courses", detail: "Filter by topic: climate change, public-private partnerships, data, health financing." },
      { title: "Complete modules + quizzes", detail: "A few hours each; progress saves automatically." },
      { title: "Download completion certificates", detail: "Free PDFs — recognised in development-sector CVs worldwide." },
    ],
    requirementsSummary: "None — free account.",
    eligibilityNote: "Open worldwide; built for practitioners in developing countries.",
    officialUrl: "https://olc.worldbank.org/",
    competitiveNote: "Open enrolment; inside the development sector the World Bank name carries real weight.",
    successTips: "Take the course closest to your country's national plan — it makes your scholarship 'return plan' essays concrete.",
  },
];
