import { SeedOpportunity } from "./seed-types";

// ─── United Kingdom & Germany ────────────────────────────────────────────────
export const EUROPE_SEED_1: SeedOpportunity[] = [
  {
    name: "Chevening Scholarships",
    kind: "SCHOLARSHIP",
    provider: "UK Government (FCDO)",
    country: "United Kingdom",
    countryCode: "gb",
    continent: "Europe",
    city: "London",
    lat: 51.5072,
    lng: -0.1276,
    levels: ["masters"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "GBP",
    feeConfirmedFree: true,
    feeNote: "Applying to Chevening itself is 100% free — no application fee at any stage. University applications come only after you are conditionally selected.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition (any UK university), monthly living stipend (~£1,300-1,600 depending on city), return economy flights, arrival allowance, visa fee reimbursement, and a £75 TB test contribution.",
    opensMonth: 8,
    opensDay: 6,
    closesMonth: 11,
    closesDay: 7,
    cycleNote: "Application window is identical every year: early August to the first Tuesday of November (usually 7 Nov).",
    moiAccepted: true,
    moiNote: "Chevening has NO English test requirement at application. You only need to meet your chosen UK university's language condition AFTER selection — many UK universities accept a Medium-of-Instruction (MOI) letter from Ghanaian universities where teaching was in English.",
    englishTests: "None required to apply. University-specific conditions later (typically IELTS 6.5 or MOI letter).",
    localLanguageRequired: false,
    localLanguageNote: "English is the language of instruction — no local language needed.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two references submitted online — one academic, one professional (not character references). Referees receive an email link and submit directly.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned/unofficial transcripts and degree certificates are accepted at application. Certified copies are only needed later from successful candidates.",
    essayRequired: true,
    essayNote: "Four essays (500 words each): Leadership & Influence, Networking, Studying in the UK, and Career Plan. These carry the most weight in screening.",
    applicationSteps: [
      { title: "Check eligibility", detail: "You need an undergraduate degree, at least 2 years (2,800 hours) of work experience, and citizenship of a Chevening-eligible country (Ghana is eligible). Return home for 2 years after the award." },
      { title: "Prepare your 4 essays + references", detail: "Draft the four 500-word essays around evidence and impact, not ambition statements. Line up your 2 referees early so they can respond within the window." },
      { title: "Apply online Aug-Nov (no fee)", detail: "Create an account at chevening.org, select 3 UK master's courses (order doesn't matter, and they can be changed later). Upload scans of your transcripts and passport. No English test needed at this stage." },
      { title: "Screening & scoring", detail: "Applications are scored independently by two assessors on essays and experience. Conditional applicants are placed on a longlist in November-December." },
      { title: "Interview (Feb-Mar)", detail: "If shortlisted, you attend a panel interview at the British Commission in Accra (or online). Expect questions probing your essays, leadership, and how you'll use the degree in Ghana." },
      { title: "Receive conditional offer (Jun) & secure university admission", detail: "Only at this point do you apply to your 3 chosen universities — Chevening fee waivers or post-offer processes apply, and many universities waive application fees for Chevening candidates." },
      { title: "Submit documents & fly (Sep)", detail: "Submit final transcripts, references, and any language condition (MOI letter often accepted), then depart for the UK in September." },
    ],
    requirementsSummary: "Bachelor's degree + 2 years work experience + 4 essays + 2 references. No application fee, no English test at application, scanned transcripts accepted.",
    eligibilityNote: "Citizens of ~160 countries — Ghanaians are fully eligible and apply directly through the global window.",
    officialUrl: "https://www.chevening.org/",
    competitiveNote: "~65,000 applicants for ~1,800 awards globally. Ghana typically wins 15-25 awards per year.",
    successTips: "Score in essays comes from SPECIFIC examples: name the project, the team you led, the measurable result. For the Career Plan essay, be concrete about Ghana — name the sector, the institution, the problem you will return to solve.",
  },
  {
    name: "Commonwealth Master's Scholarships",
    kind: "SCHOLARSHIP",
    provider: "Commonwealth Scholarship Commission (CSC UK)",
    country: "United Kingdom",
    countryCode: "gb",
    continent: "Europe",
    city: "London",
    lat: 51.4934,
    lng: -0.0098,
    levels: ["masters"],
    fields: ["any", "development studies", "engineering", "medicine & health", "natural sciences", "agriculture & food", "education"],
    feeAmount: 0,
    feeCurrency: "GBP",
    feeConfirmedFree: true,
    feeNote: "No application fee. You apply directly on the CSC online system — you do NOT need to already hold a UK university offer at the time of application.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition, monthly stipend (£1,378 outside London / £1,690 in London), return flights, thesis grant, study travel grant, and warm clothing allowance.",
    opensMonth: 9,
    opensDay: 10,
    closesMonth: 10,
    closesDay: 16,
    cycleNote: "Roughly 10 September to mid-October every year — a short window, prepare documents in August.",
    moiAccepted: true,
    moiNote: "No English test is required by the CSC at application. Your university English condition comes after nomination; many UK universities waive IELTS for degrees taught in English (MOI letter from a Ghanaian university usually works).",
    englishTests: "Not required at application.",
    localLanguageRequired: false,
    localLanguageNote: "English only.",
    recommendationsRequired: false,
    recommendationsNote: "References are NOT required at application — this is one of the few fully-funded UK scholarships without that burden. Courses may ask for references after nomination.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scanned (unofficial) degree certificates and transcripts. Certified/official copies only for winners.",
    essayRequired: true,
    essayNote: "Structured questions inside the application form on Development Impact — how your study plan solves a development problem in Ghana.",
    applicationSteps: [
      { title: "Confirm eligibility", detail: "Citizen of a least-developed or lower/middle-income Commonwealth country (Ghana qualifies), hold a 2:1 undergraduate degree or 2:2 plus relevant postgrad qualification, and be unable to afford UK study without the scholarship." },
      { title: "Prepare development-impact answers", detail: "Read the six CSC development themes and frame your study plan around one of them (e.g. science and technology for development, strengthening health systems)."},
      { title: "Apply on the CSC online system (Sep-mid Oct)", detail: "One application, no fee. Select up to several participating UK master's courses. Upload scanned transcripts, degree certificate, passport/national ID, and (if applicable) proof of refugee status." },
      { title: "Nomination & shortlisting", detail: "CSC scores applications, then shortlists by department. No interview at this scholarship — selection is paper-based." },
      { title: "Place offer & university admission (Mar-Jul)", detail: "Shortlisted candidates are placed at a specific university; the university then runs its own admission check (language condition via MOI/IELTS can be settled here)." },
      { title: "Depart for the UK (Sep)", detail: "CSC handles flights, visa guidance, and stipend setup." },
    ],
    requirementsSummary: "Bachelor's (min 2:1), Ghanaian citizenship, development-themed answers, scanned transcripts. No fee, no references, no English test at application.",
    eligibilityNote: "Ghana is a priority Commonwealth country; awards target those who could not otherwise afford UK study.",
    officialUrl: "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",
    competitiveNote: "~2,000 applications per country cluster for ~150 awards. Development-impact framing is the decisive factor.",
    successTips: "Name a specific development problem in Ghana (e.g. post-harvest losses, maternal health in Northern Region) and show how the exact course modules map onto it.",
  },
  {
    name: "Commonwealth Shared Scholarships",
    kind: "SCHOLARSHIP",
    provider: "CSC UK + participating UK universities",
    country: "United Kingdom",
    countryCode: "gb",
    continent: "Europe",
    city: "London",
    lat: 51.5074,
    lng: -0.1278,
    levels: ["masters"],
    fields: ["any", "development studies", "engineering", "medicine & health", "agriculture & food"],
    feeAmount: 0,
    feeCurrency: "GBP",
    feeConfirmedFree: true,
    feeNote: "No fee for the scholarship application. You simultaneously apply to the university's own master's course — most participating universities charge no fee for the Shared Scholarship route, but check the course page (a few charge £25-60).",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition, monthly stipend, flights, thesis grant — same package as CSC Master's awards.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 2,
    closesDay: 28,
    cycleNote: "Universities open Shared Scholarship calls from early December to late February — each course sets its own deadline inside that range.",
    moiAccepted: true,
    moiNote: "University-specific; Ghanaian English-medium degrees are widely accepted as proof via MOI letters by participating universities.",
    englishTests: "Per university — often waivable with MOI.",
    localLanguageRequired: false,
    localLanguageNote: "English only.",
    recommendationsRequired: false,
    recommendationsNote: "Not required in the CSC portion; a few universities request academic references for admission.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts accepted by both the CSC system and most university application portals.",
    essayRequired: true,
    essayNote: "Development-impact questions similar to the main CSC Master's form.",
    applicationSteps: [
      { title: "Find a participating course", detail: "The CSC publishes the list of eligible master's courses per university each December — usually development-facing fields (public health, engineering for development, agriculture)." },
      { title: "Apply to the course AND the scholarship", detail: "Apply for admission to the course on the university portal and complete the CSC Shared Scholarship section. Do both before the course's stated deadline." },
      { title: "University nominates", detail: "Universities shortlist and nominate strong candidates to the CSC." },
      { title: "CSC confirms & funds", detail: "CSC confirms nominations and issues award letters with funding details." },
    ],
    requirementsSummary: "Bachelor's 2:1+, Ghanaian citizenship, cannot afford UK study. Apply via the university's course page during Dec-Feb.",
    eligibilityNote: "Least developed and lower-middle-income Commonwealth countries — Ghana eligible.",
    officialUrl: "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-shared-scholarships/",
    competitiveNote: "Fewer applicants than the main CSC Master's scheme because candidates must apply course-by-course — a genuine edge.",
    successTips: "Apply to 2-3 Shared courses in the same season; each application is independent and free, multiplying your chances.",
  },
  {
    name: "Gates Cambridge Scholarship",
    kind: "SCHOLARSHIP",
    provider: "Gates Cambridge Trust, University of Cambridge",
    country: "United Kingdom",
    countryCode: "gb",
    continent: "Europe",
    city: "Cambridge",
    lat: 52.2043,
    lng: 0.1218,
    levels: ["masters", "phd"],
    fields: ["any"],
    feeAmount: 50,
    feeCurrency: "GBP",
    feeConfirmedFree: false,
    feeNote: "The scholarship application itself is free, but you must apply to a Cambridge graduate course first and Cambridge charges a graduate application fee (~£50-90 for most courses). Fee waivers exist for applicants from low-income countries.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full university fees + £20,000+/yr maintenance + flights + family/academic development funding.",
    opensMonth: 9,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 2,
    cycleNote: "International round: apply by 2-3 December (or early January for some US-resident rounds). Course deadlines vary slightly.",
    moiAccepted: true,
    moiNote: "Cambridge departments accept MOI evidence case-by-case; many accept degrees from English-speaking countries such as Ghana in lieu of IELTS.",
    englishTests: "IELTS 7.0-7.5 typical for Cambridge courses unless waived via English-medium degree.",
    localLanguageRequired: false,
    localLanguageNote: "English only.",
    recommendationsRequired: true,
    recommendationsCount: 3,
    recommendationsNote: "Cambridge admission requires 2 academic references; the Gates Cambridge section adds a third (Gates) reference.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts are accepted during admission; certified documents after an offer.",
    essayRequired: true,
    essayNote: "A 3,000-character Gates Cambridge statement: why this course, why Cambridge, and how you will contribute to the programme and society.",
    applicationSteps: [
      { title: "Choose a course & supervisor", detail: "Identify a Cambridge master's/PhD course; for PhDs contact a potential supervisor months ahead with a 1-page research pitch." },
      { title: "Apply to the course (Sep-Dec)", detail: "Submit the Cambridge graduate application online (fee ~£50-90, waivers for low-income applicants) and tick the Gates Cambridge option — you then complete the Gates statement and third reference within the same application." },
      { title: "Departmental ranking", detail: "Departments rank admitted applicants on academic strength and fit; Gates shortlists from that ranking." },
      { title: "Shortlist interview (Feb-Mar)", detail: "Shortlisted candidates are interviewed by the Gates Cambridge panel (online interviews available)." },
      { title: "Award & enrolment (Oct)", detail: "Roughly 80 new scholars join Cambridge each year across all disciplines." },
    ],
    requirementsSummary: "Cambridge course application (fee, waiver possible) + Gates statement + 3 references. Fully funded if selected.",
    eligibilityNote: "Any non-UK citizen — Ghanaians are consistently among awardees.",
    officialUrl: "https://www.gatescambridge.org/",
    competitiveNote: "~6,000 applications for ~80 awards — the most selective scholarship in this database.",
    successTips: "The Gates statement must show intellectual commitment to a problem, not a biography. Reference the specific Cambridge research group whose work you will extend.",
  },
  {
    name: "Rhodes Scholarship — West Africa (incl. Ghana)",
    kind: "SCHOLARSHIP",
    provider: "Rhodes Trust, University of Oxford",
    country: "United Kingdom",
    countryCode: "gb",
    continent: "Europe",
    city: "Oxford",
    lat: 51.7548,
    lng: -1.2544,
    levels: ["masters", "phd"],
    fields: ["any"],
    feeAmount: 75,
    feeCurrency: "GBP",
    feeConfirmedFree: false,
    feeNote: "The Rhodes application is free, but winners must secure Oxford admission where a ~£75 course application fee applies (fee waivers available on request for financial hardship).",
    fundingType: "FULLY_FUNDED",
    fundingNote: "All Oxford university fees + ~£19,000+/yr stipend + two flights + settling-in allowance + International Leadership Symposiums.",
    opensMonth: 6,
    opensDay: 1,
    closesMonth: 9,
    closesDay: 30,
    cycleNote: "West Africa constituency window typically June-September/October — check the country page for the exact cutoff each year.",
    moiAccepted: true,
    moiNote: "Oxford accepts English-medium degrees from recognized Ghanaian universities in many cases; confirm per course.",
    englishTests: "Oxford sets IELTS 7.0-7.5 per course unless an English-medium degree exemption applies.",
    localLanguageRequired: false,
    localLanguageNote: "English only.",
    recommendationsRequired: true,
    recommendationsCount: 5,
    recommendationsNote: "Typically 4-6 referees submitting detailed letters through the application portal — start these early.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts accepted at application; Oxford requires scans first, originals later.",
    essayRequired: true,
    essayNote: "A personal statement (~1,000 words) plus a proposed plan of study.",
    applicationSteps: [
      { title: "Verify constituency eligibility", detail: "West Africa constituency covers Ghana and neighbouring countries; age limits (typically ~19-25 at time of selection) and bachelor's completion requirements apply — read the country page carefully." },
      { title: "Build your referee panel (Jun-Jul)", detail: "Secure 4-6 referees who know your leadership and academics; Rhodes letters are long-form and referee effort matters." },
      { title: "Submit application by the September deadline", detail: "Online form: personal statement, plan of study, CV, transcripts (scans), and referee contacts. Free to apply." },
      { title: "Pre-selection & social", detail: "Shortlisted candidates are notified for a final selection weekend; get ready to discuss your statement under pressure." },
      { title: "Final interview weekend (Oct-Nov)", detail: "Panel of academics and Rhodes alumni interview finalists over one to two days." },
      { title: "Apply to Oxford as an Elect (Nov-Jan)", detail: "Winners ('Elects') apply to their chosen Oxford course — the £75 fee is commonly waived for Elects on request." },
    ],
    requirementsSummary: "Strong academics + proven leadership + service. Free Rhodes application; Oxford fee applies after election (waiver possible).",
    eligibilityNote: "West Africa constituency includes Ghana — one of the fastest-growing Rhodes constituencies.",
    officialUrl: "https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/",
    competitiveNote: "2-4 awards for the whole West Africa constituency per year.",
    successTips: "Rhodes selects for 'fight the world's fight' — evidence of service to others carries more weight than polished ambition.",
  },
  {
    name: "UK Funded PhD Projects (advertised studentships)",
    kind: "SCHOLARSHIP",
    provider: "UKRI / university research council studentships",
    country: "United Kingdom",
    countryCode: "gb",
    continent: "Europe",
    city: "Manchester",
    lat: 53.4808,
    lng: -2.2426,
    levels: ["phd"],
    fields: ["any", "engineering", "computer science", "natural sciences", "medicine & health", "environment", "energy"],
    feeAmount: 0,
    feeCurrency: "GBP",
    feeConfirmedFree: true,
    feeNote: "Advertised funded PhD projects (listed on FindAPhD and university sites) are free to apply for — no application fee for the studentship. Only self-proposed PhD applications often carry a fee.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "UKRI-rate stipend (~£20,780/yr tax-free, 2026-27 higher), full home/international tuition covered by most CDT/studentship calls (many projects explicitly fund international fees).",
    rolling: true,
    cycleNote: "Projects are advertised year-round with deadlines typically Oct-Jan for autumn starts; CDT calls open Sept-Nov.",
    moiAccepted: true,
    moiNote: "Most UK universities accept a degree taught in English (MOI letter from a Ghanaian university) in place of IELTS — check each project's language requirements page.",
    englishTests: "IELTS 6.5 overall typical, frequently waived with MOI from an English-medium degree.",
    localLanguageRequired: false,
    localLanguageNote: "English only.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two academic references standard for PhD admission.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts are the norm for PhD applications; originals later.",
    essayRequired: true,
    essayNote: "A research proposal or project-specific statement of purpose (1-2 pages).",
    applicationSteps: [
      { title: "Search FindAPhD + university pages", detail: "Filter FindAPhD for 'funded' UK projects that state 'fees + stipend available to international students'. CDT (Centres for Doctoral Training) calls are the most international-friendly." },
      { title: "Email the supervisor first", detail: "Send a short email: your CV, one paragraph on why the project fits you, and one question about the project. Supervisors influence shortlisting heavily." },
      { title: "Submit formal application (free)", detail: "Apply through the university portal for that specific project — upload CV, scans of transcripts, 2 referee contacts, and a tailored statement." },
      { title: "Interview (often online)", detail: "Expect a 30-45 min technical discussion of your background and the project; practice explaining your past research clearly." },
      { title: "Award & visa", detail: "Studentship confirmation letter supports your Student visa; stipend is paid monthly." },
    ],
    requirementsSummary: "Master's (or strong bachelor's) in field, 2 references, scans accepted, MOI often accepted, free application.",
    eligibilityNote: "Open to all nationalities; always confirm the project funds international (not just home) fees.",
    officialUrl: "https://www.findaphd.com/phds/united-kingdom/?Keywords=funded&Location=United%20Kingdom",
    competitiveNote: "Less competitive than named scholarships — a single project may attract 20-60 applicants.",
    successTips: "Apply to 8-12 projects in one season. Supervisor contact BEFORE applying doubles your interview odds.",
  },
  {
    name: "DAAD EPOS — Development-Related Postgraduate Courses",
    kind: "SCHOLARSHIP",
    provider: "German Academic Exchange Service (DAAD)",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Bonn",
    lat: 50.7374,
    lng: 7.0982,
    levels: ["masters", "phd"],
    fields: ["any", "development studies", "engineering", "agriculture & food", "public policy", "environment", "energy", "medicine & health", "business & economics"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "No application fee to DAAD. Note: the host course itself may ask for a small processing fee in a few cases — most EPOS courses are free to apply to directly.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "€992/month full scholarship for master's students (€1,300 for PhD), health insurance, travel allowance, study/research subsidy, and optional German language course (2-6 months) before the degree.",
    opensMonth: 8,
    opensDay: 1,
    closesMonth: 10,
    closesDay: 31,
    cycleNote: "Each of the ~40 EPOS courses sets its own deadline between August and October (a few run to December) for intake the following October.",
    moiAccepted: true,
    moiNote: "Many English-taught EPOS courses accept a Medium-of-Instruction certificate from Ghanaian universities instead of IELTS — it is stated course-by-course in the DAAD database ('proof of English: MOI acceptable').",
    englishTests: "Course-dependent: IELTS 6.0-6.5 OR MOI certificate for many courses.",
    localLanguageRequired: false,
    localLanguageNote: "Not required for English-taught courses — and DAAD funds a free German language course (2-6 months) before your degree starts, which is ideal for daily life in Germany.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two letters using the DAAD reference form — at least one from your employer if you have work experience.",
    unofficialTranscripts: true,
    transcriptsNote: "Certified scanned copies of certificates and transcripts are uploaded at application — attested scans, not originals.",
    essayRequired: true,
    essayNote: "A DAAD-format motivation letter (max 2 pages) tied to development relevance of your current work.",
    applicationSteps: [
      { title: "Confirm the work-experience rule", detail: "EPOS requires a bachelor's (usually four-year) degree AND at least 2 years of relevant professional experience by application time. This is the number one rejection reason — check before investing time." },
      { title: "Pick up to 3 courses in the DAAD database", detail: "Filter the DAAD Scholarship Database for 'Development-Related Postgraduate Courses'. Each listing shows the deadline, English requirements (watch for 'MOI accepted'), and direct application address." },
      { title: "Apply to each course (Aug-Oct, free)", detail: "Most courses want the DAAD application form + motivation letter + 2 DAAD reference forms + certified scans + employer statement. Apply directly to the university (not DAAD)." },
      { title: "Course nominates you to DAAD", detail: "The university shortlists and recommends candidates; DAAD makes the final decision." },
      { title: "Award & language course (Jan-Aug)", detail: "Winners receive funding decisions around Jan-Mar, then may get a funded German course starting ~June before the October intake." },
    ],
    requirementsSummary: "2 yrs work experience + bachelor's + motivation letter + 2 DAAD references + certified scans. Free application, MOI often accepted, funded German pre-course.",
    eligibilityNote: "Citizens of developing countries incl. Ghana; courses target public-sector and NGO professionals especially.",
    officialUrl: "https://www.daad.de/en/study-and-research-in-germany/scholarships/development-related-postgraduate-courses/",
    competitiveNote: "Ghanaian applicants have a historically strong success rate in water/engineering/governance EPOS courses.",
    successTips: "The employer recommendation on the official DAAD form matters enormously — brief your referee with your development-impact narrative.",
  },
  {
    name: "Deutschlandstipendium",
    kind: "SCHOLARSHIP",
    provider: "German Federal Government + private sponsors",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Berlin",
    lat: 52.5200,
    lng: 13.4050,
    levels: ["undergraduate", "masters"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "Applying to the scholarship at your enrolled university is free.",
    fundingType: "PARTIAL",
    fundingNote: "€300/month for at least 2 semesters (half from the federal government, half from private sponsors) — designed to top up tuition-free study, not cover everything.",
    opensMonth: 9,
    opensDay: 15,
    closesMonth: 10,
    closesDay: 31,
    cycleNote: "Most universities run calls in Sept-Oct before the winter semester; some have spring rounds. You must already be admitted/enrolled at that university.",
    moiAccepted: true,
    moiNote: "Follows your university's own language rules — German public universities commonly accept MOI letters for English-taught master's admission.",
    englishTests: "Per university admission rules.",
    localLanguageRequired: false,
    localLanguageNote: "Not required for English-taught degrees; B1-B2 German opens more scholarship calls and daily life.",
    recommendationsRequired: true,
    recommendationsCount: 1,
    recommendationsNote: "One letter (academic or employer) at most universities; some just want a CV + transcript.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans accepted.",
    essayRequired: true,
    essayNote: "Short motivation statement (1 page) — social engagement and perseverance weigh heavily.",
    applicationSteps: [
      { title: "Get admitted to a German university first", detail: "Deutschlandstipendium is applied for AFTER admission — search '[university name] + Deutschlandstipendium' for its call page." },
      { title: "Watch the Sept-Oct call window", detail: "Each university publishes criteria; upload CV, scans, letter, and proof of social engagement (volunteering, student leadership)." },
      { title: "Selection committee review", detail: "Universities weigh grades, social engagement, and personal circumstances (e.g. financing challenges, family background)." },
      { title: "€300/month starts", detail: "Awarded for 2+ semesters, renewable by re-application." },
    ],
    requirementsSummary: "University admission + strong grades + social engagement. Free, partial funding — stack it with tuition-free study.",
    eligibilityNote: "Open to international students at participating German universities — Ghanaians eligible.",
    officialUrl: "https://www.deutschlandstipendium.de/deutschlandstipendium/de/english/english_node.html",
    competitiveNote: "Acceptance odds are much higher than big-name scholarships — often 1 in 4-8 at less-famous universities.",
    successTips: "Document volunteer work with dates and roles. Committees explicitly look for community engagement, not just grades.",
  },
  {
    name: "RWTH Aachen University — Free Direct Application",
    kind: "UNIVERSITY",
    provider: "RWTH Aachen",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Aachen",
    lat: 50.7783,
    lng: 6.0835,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any", "engineering", "computer science", "natural sciences", "energy", "medicine & health"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "RWTH's online application portal is free of charge (self-processing route). Only if your documents must go through the uni-assist VPD pre-check does uni-assist's €75 first-certificate fee apply — many RWTH programs accept direct processing.",
    fundingType: "NO_TUITION",
    fundingNote: "No tuition fees for any nationality — only the semester contribution (~€320/semester) which includes regional public transport. Germany's NRW state charges zero tuition to non-EU students.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 7,
    closesDay: 15,
    cycleNote: "Winter-semester intake: 1 Dec - 15 Jul (non-EU applicants should apply by 1 Mar for visa time). Some English MSc programs also admit for summer (Dec 1 - Jan 15).",
    moiAccepted: true,
    moiNote: "RWTH English-taught master's programmes commonly accept an MOI certificate from English-medium universities as English proof.",
    englishTests: "English MSc: TOEFL 90 / IELTS 5.5-6.5 depending on program; MOI frequently accepted.",
    localLanguageRequired: false,
    localLanguageNote: "German NOT required for English-taught master's. German-taught bachelor's requires DSH/TestDaF — plan a language year if needed.",
    recommendationsRequired: false,
    recommendationsNote: "Generally NOT required for taught admissions (only for PhDs).",
    unofficialTranscripts: true,
    transcriptsNote: "Certified digital scans uploaded to the portal; originals checked at enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Choose your programme in the RWTH course catalogue", detail: "Filter by 'English' language — Aachen runs 30+ English MSc programmes (mechanical, data science, energy, metallurgy...). Each page states exact deadlines and document lists." },
      { title: "Register on the RWTHonline portal (free)", detail: "Create an account, select the programme and semester, and receive your applicant number. No payment step." },
      { title: "Upload scans (Dec 1 - Jul 15)", detail: "Bachelor certificate + transcript (certified scans), language proof (MOI often ok), CV, and APS certificate — NOTE: applicants from Ghana currently need an APS certificate for German student visas, which takes 2-4 months; start it early." },
      { title: "Track the admission decision", detail: "Non-EU decisions roll out Feb-Aug. Most RWTH MSc are NC-free (no GPA cut-off) but require module-match checks." },
      { title: "Open a blocked account & enrol", detail: "Once admitted: blocked account (~€11,904/yr), visa, arrival, enrolment — then pay only the ~€320 semester fee." },
    ],
    requirementsSummary: "Free portal application, certified scans, MOI often accepted, no tuition (€320/semester only). APS needed for Ghanaian visa.",
    eligibilityNote: "All nationalities; module-matching check for master's (your bachelor's courses must map to the MSc curriculum).",
    officialUrl: "https://www.rwth-aachen.de/go/id/a/?lidx=1",
    competitiveNote: "Admission is requirements-based rather than ranked — if you match the module map, you get in. Aachen is Germany's top technical university.",
    successTips: "Use RWTH's free 'module check' service — submit your transcript for a pre-assessment before formally applying. It tells you exactly which courses mismatch.",
  },
  {
    name: "FAU Erlangen-Nürnberg — Free Direct Application",
    kind: "UNIVERSITY",
    provider: "Friedrich-Alexander-Universität",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Erlangen",
    lat: 49.5935,
    lng: 11.0067,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any", "engineering", "computer science", "natural sciences", "medicine & health", "energy"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "FAU's campo portal application is completely free for all programmes.",
    fundingType: "NO_TUITION",
    fundingNote: "No tuition fees (Bavaria's fee option is not applied at FAU for most programmes) — only ~€130/semester administrative fee.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 7,
    closesDay: 15,
    cycleNote: "Winter intake: apply Dec 1 - Jul 15 (non-EU: by mid-May for visa time); summer intake: Dec 1 - Jan 15 for selected programmes.",
    moiAccepted: true,
    moiNote: "FAU English master's programmes (e.g. Advanced Materials, Chemical Engineering, AI) accept MOI certificates case-by-case — confirm on the programme page.",
    englishTests: "IELTS 6.5 / TOEFL 92 for most English MSc; MOI often accepted.",
    localLanguageRequired: false,
    localLanguageNote: "Not needed for English programmes; free German courses offered to enrolled students.",
    recommendationsRequired: false,
    recommendationsNote: "Not required for taught degrees.",
    unofficialTranscripts: true,
    transcriptsNote: "Digital certified scans accepted at application.",
    essayRequired: false,
    applicationSteps: [
      { title: "Shortlist FAU English-taught master's", detail: "FAU runs one of Germany's widest English MSc catalogues — check 'Master's programmes in English' list." },
      { title: "Apply via campo portal (free)", detail: "One portal for all FAU programmes; upload scans directly. No fee at any step." },
      { title: "Document check & admission", detail: "Admissions verifies module matching and language proof; decisions in 4-10 weeks." },
      { title: "Visa + enrolment", detail: "Admission letter + blocked account → visa → enrol with ~€130 semester fee. APS certificate required for Ghanaian applicants." },
    ],
    requirementsSummary: "Free application, scans, MOI often accepted, ~€130/semester total cost of study.",
    eligibilityNote: "Open worldwide; strong engineering & AI departments with Siemens proximity for internships.",
    officialUrl: "https://www.fau.eu/education/international/applying/",
    competitiveNote: "Moderate competition; module match matters more than GPA.",
    successTips: "FAU replies to pre-check emails with free transcript assessments — use it before formal application.",
  },
  {
    name: "Saarland University — Free Direct Application",
    kind: "UNIVERSITY",
    provider: "Universität des Saarlandes",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Saarbrücken",
    lat: 49.2551,
    lng: 7.0424,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any", "computer science", "engineering", "natural sciences"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "Free online application — Saarland processes applications itself, no uni-assist for most programmes.",
    fundingType: "NO_TUITION",
    fundingNote: "No tuition fees; ~€300/semester contribution incl. transport. Home of the Max Planck Institute for Informatics and CISPA cybersecurity hub — exceptional free CS/AI environment.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 7,
    closesDay: 15,
    cycleNote: "Winter intake Dec 1 - Jul 15 (non-EU by May); summer window for some MSc.",
    moiAccepted: true,
    moiNote: "CS master's (English-taught) accepts MOI evidence from English-medium degrees in many cases.",
    englishTests: "IELTS 6.0-6.5 / TOEFL 80-90 or MOI.",
    localLanguageRequired: false,
    localLanguageNote: "Not required for English CS programmes.",
    recommendationsRequired: false,
    recommendationsNote: "Not for taught admissions.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans accepted.",
    essayRequired: false,
    applicationSteps: [
      { title: "Pick CS/AI/data science programmes", detail: "Saarbrücken's CS department is top-3 in Germany — programmes: Cybersecurity, Data Science & AI, Computer Science (all English)."},
      { title: "Apply free via the online portal", detail: "Upload scans of degree + transcript + language proof. No fee." },
      { title: "Admission & visa", detail: "Decisions typically within 6 weeks; then blocked account, visa (APS for Ghana), enrolment." },
    ],
    requirementsSummary: "Free application, scans, MOI often ok, tiny semester fee. Elite CS environment at zero tuition.",
    eligibilityNote: "Worldwide open admission on requirements.",
    officialUrl: "https://www.uni-saarland.de/en/study/international.html",
    competitiveNote: "Cybersecurity and AI programmes attract strong applicants but are requirements-based.",
    successTips: "Mention research interests of CISPA/Max Planck groups in your CV if applying for CS — PhD doors open from master's research projects there.",
  },
  {
    name: "TU Chemnitz — Free Direct Application",
    kind: "UNIVERSITY",
    provider: "Technische Universität Chemnitz",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Chemnitz",
    lat: 50.8333,
    lng: 12.9167,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any", "engineering", "computer science", "energy", "natural sciences"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "Free direct application for most programmes (some use uni-assist VPD — check programme page; direct route is free).",
    fundingType: "NO_TUITION",
    fundingNote: "No tuition; ~€290/semester fee incl. regional transport. Chemnitz is one of Germany's lowest cost-of-living university cities (rooms from €220/month).",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 7,
    closesDay: 15,
    cycleNote: "Winter intake Dec 1 - Jul 15; summer intake for selected English MSc.",
    moiAccepted: true,
    moiNote: "English-taught master's (e.g. Automotive Software Engineering, Micro & Nano Systems) widely accept MOI certificates.",
    englishTests: "IELTS 6.0 / TOEFL 79-90 or MOI.",
    localLanguageRequired: false,
    localLanguageNote: "Not for English programmes.",
    recommendationsRequired: false,
    recommendationsNote: "Not for taught admissions.",
    unofficialTranscripts: true,
    transcriptsNote: "Certified scans accepted.",
    essayRequired: false,
    applicationSteps: [
      { title: "Select English-taught MSc", detail: "Known for engineering/AI masters with relaxed admission thresholds." },
      { title: "Apply free via TUCaN/online portal", detail: "Upload scans; track status online." },
      { title: "Admission, visa, enrolment", detail: "Low living costs make the blocked account stretch further; APS needed for Ghana." },
    ],
    requirementsSummary: "Free application, scans, MOI accepted on many English MSc, lowest-cost German city.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://www.tu-chemnitz.de/international/",
    competitiveNote: "Among the most accessible German technical universities for international students.",
    successTips: "Apply early (Dec-Jan) — some English MSc fill via first-come document checks.",
  },
  {
    name: "University of Passau — Free Direct Application",
    kind: "UNIVERSITY",
    provider: "Universität Passau",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Passau",
    lat: 48.5667,
    lng: 13.4333,
    levels: ["undergraduate", "masters"],
    fields: ["any", "computer science", "business & economics", "law", "social sciences"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "Free application via the campus portal for all programmes.",
    fundingType: "NO_TUITION",
    fundingNote: "No tuition fees; ~€300/semester incl. transport. Beautiful Danube-river campus with strong 'Digital Technologies & Society' interdisciplinary masters.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 7,
    closesDay: 15,
    cycleNote: "Winter intake Dec 1 - Jul 15 (non-EU by May 31); summer for some programmes.",
    moiAccepted: true,
    moiNote: "English MSc programmes accept MOI from English-medium universities in many cases.",
    englishTests: "IELTS 6.5 / TOEFL 90 or MOI per programme.",
    localLanguageRequired: false,
    localLanguageNote: "Not for English programmes.",
    recommendationsRequired: false,
    recommendationsNote: "Not for taught admissions.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans accepted.",
    essayRequired: false,
    applicationSteps: [
      { title: "Browse English MSc list", detail: "MSc Computer Science, Digital Technologies, International Economics & Business — all English." },
      { title: "Apply free on the campus portal", detail: "Upload scans + language proof; no fee." },
      { title: "Admission & arrival", detail: "Fast document checks; enrol with semester fee only." },
    ],
    requirementsSummary: "Free application, scans, MOI often ok.",
    eligibilityNote: "Open worldwide.",
    officialUrl: "https://www.uni-passau.de/en/",
    competitiveNote: "Accessible admission; high teaching quality.",
    successTips: "Combine with Deutschlandstipendium (Passau runs an active call every autumn).",
  },
];
