import { SeedOpportunity } from "./seed-types";

/** NEW universities — free or ≤$30 confirmed application fees (Asia/ME/Africa part 2). */
export const UNIS_WORLD_2: SeedOpportunity[] = [
  {
    name: "Universiti Sains Malaysia (USM) — RM 50 Application (~$11)",
    slug: "usm-malaysia",
    kind: "UNIVERSITY",
    provider: "Universiti Sains Malaysia",
    country: "Malaysia",
    countryCode: "my",
    continent: "Asia",
    city: "Penang",
    lat: 5.355,
    lng: 100.303,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 50,
    feeCurrency: "MYR",
    feeConfirmedFree: false,
    feeUsdApprox: 11,
    feeNote: "Confirmed: ~RM50 (~$11) processing fee — USM runs frequent fee-waiver campaigns; watch for 'no processing fee' months.",
    related: ["mis-malaysia", "mtcp"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Low tuition (UG from ~RM 6,000/year); MIS/MTCP scholarships cover tuition + RM 3,500/month living.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 6,
    closesDay: 30,
    cycleNote: "September intake ~Dec–Jun; some programmes run February intakes (Sep–Nov window).",
    moiAccepted: true,
    moiNote: "USM accepts MOI letters from English-medium institutions in place of IELTS for many programmes.",
    englishTests: "IELTS 5.5–6.0 / TOEFL / MOI letter.",
    localLanguageRequired: false,
    localLanguageNote: "English-medium international programmes.",
    recommendationsRequired: false,
    recommendationsNote: "Not required for coursework degrees.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans at application; originals at registration.",
    essayRequired: false,
    applicationSteps: [
      { title: "Check for the current fee-waiver window", detail: "USM periodically drops the RM50 fee during promotions — time your application to save even the $11." },
      { title: "Apply through USM's online portal", detail: "Upload passport, certificates, transcripts, language proof/MOI." },
      { title: "Postgrad: draft a 2-page research concept", detail: "USM engineering/science supervisors respond well to short, specific proposals — attach it even when optional." },
      { title: "Accept offer → EMGS student pass", detail: "Standard Malaysia visa route; USM's international office guides each step." },
      { title: "Stack MIS/MTCP scholarship applications", detail: "USM is a designated MIS host — apply with your offer for tuition + RM 3,500/month." },
    ],
    requirementsSummary: "RM 50 (sometimes waived), MOI accepted, MIS-designated host.",
    eligibilityNote: "Standard certificates; strong for pharmacy, engineering, materials science.",
    officialUrl: "https://www.usm.my/index.php/en/admission",
    competitiveNote: "Moderate; Penang campus is a favourite for African student communities.",
    successTips: "USM + MIS is the cheapest fully-funded combo in Asia: $11 to apply, $0 if you hit a waiver window, then full funding. Ghanaian student societies exist on campus.",
  },
  {
    name: "Islamic University of Madinah — $0 + Full Scholarship",
    slug: "madinah-university",
    kind: "UNIVERSITY",
    provider: "Islamic University of Madinah",
    country: "Saudi Arabia",
    countryCode: "sa",
    continent: "Middle East",
    city: "Madinah",
    lat: 24.47,
    lng: 39.611,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["Islamic & Arabic studies", "education", "law (Sharia)", "social sciences"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: no application fee — admission IS the scholarship (tuition, housing, meals allowance, monthly stipend, annual flights).",
    related: [],
    fundingType: "FULLY_FUNDED",
    fundingNote: "Comprehensive scholarship: free tuition + furnished housing + monthly stipend + food allowance + yearly round-trip ticket + healthcare for the student's family in some cases.",
    opensMonth: 1,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 31,
    cycleNote: "Applications accepted in windows year-round (portal opens for each intake); apply as early as possible for the next academic year.",
    moiAccepted: false,
    moiNote: "Not applicable — no English tests at all; all students take a 2-year Arabic institute first.",
    englishTests: "None required.",
    localLanguageRequired: true,
    localLanguageNote: "Arabic — the university's free 2-year Arabic Language Institute precedes every degree; zero Arabic needed to be admitted.",
    recommendationsRequired: false,
    recommendationsNote: "No formal letters; a general recommendation or clearance from a mosque/education authority helps but isn't mandatory.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scanned certificates + passport; originals verified on arrival.",
    essayRequired: true,
    essayNote: "Short personal/religious background statement in the application form.",
    applicationSteps: [
      { title: "Create an account on iu.edu.sa admissions", detail: "The portal opens periodically — register your email and wait for the open window notification." },
      { title: "Fill the scholarship application honestly", detail: "Personal info, education history, Quran/Islamic-studies background (helpful but not required for all faculties)." },
      { title: "Upload scans: passport + certificates", detail: "WASSCE or equivalent is fine for UG entry; translation handled by the university." },
      { title: "Await the admission decision (several months)", detail: "Decisions arrive by email in batches; accepted students receive visa authorisation from Saudi authorities." },
      { title: "Fly in — everything else is covered", detail: "Visa, housing in university accommodation, monthly stipend, meals allowance and annual tickets are provided from day one." },
    ],
    requirementsSummary: "$0 forever, 2-year free Arabic year, full board + stipend, no English test at all.",
    eligibilityNote: "Male students historically for most faculties (check current policy); age limits apply (UG typically ≤25); basic Islamic-knowledge interview for some faculties.",
    officialUrl: "https://admission.iu.edu.sa/",
    competitiveNote: "Huge applicant pool but thousands of seats; West African applicants (incl. Ghana) have a long admission history here.",
    successTips: "If you want Arabic + Islamic sciences (or a paid-for degree route), this is the most complete $0 package worldwide. Apply the moment a window opens and keep documents simple and truthful.",
  },
  {
    name: "University of Johannesburg — $0 Online Application",
    slug: "uj-south-africa",
    kind: "UNIVERSITY",
    provider: "University of Johannesburg (UJ)",
    country: "South Africa",
    countryCode: "za",
    continent: "Africa",
    city: "Johannesburg",
    lat: -26.178,
    lng: 28.0,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "ZAR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: UJ's ONLINE applications carry no fee at all (paper applications cost R200 — so apply online only).",
    related: [],
    fundingType: "SELF_FUNDED",
    fundingNote: "Tuition modest by world standards (UG from ~R 40,000–70,000/year ≈ $2,200–3,900). Merit bursaries + postgraduate funding pools exist.",
    opensMonth: 4,
    opensDay: 1,
    closesMonth: 9,
    closesDay: 30,
    cycleNote: "2028 intake online applications open ~1 Apr 2027 (South African cycle: Apr–Sep). Programmes close as they fill — apply early.",
    moiAccepted: true,
    moiNote: "English-medium prior schooling (WASSCE for Ghanaians) generally satisfies UJ's English requirement — assessment case-by-case with your results.",
    englishTests: "IELTS ~5.0–6.0 for some internationals; often waived with English-medium results slips.",
    localLanguageRequired: false,
    localLanguageNote: "English medium.",
    recommendationsRequired: false,
    recommendationsNote: "Not required.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload WASSCE/ results + transcripts as scans; SAQA evaluation may be requested for foreign qualifications.",
    essayRequired: false,
    applicationSteps: [
      { title: "Apply ONLINE only (free)", detail: "uj.ac.za → Study → Apply. The online route is free; never pay the R200 paper fee." },
      { title: "Upload results + passport scans", detail: "WASSCE certificate, transcript, passport bio page; SAQA/USAF evaluation for foreign quals where flagged." },
      { title: "Track your student number + status", detail: "UJ issues a student number instantly; check 'application status' weekly — programmes close as they fill." },
      { title: "Accept + pay the initial registration deposit", detail: "The first real money is the registration fee (~R 5,000+) at enrolment — budget that, not an application fee." },
      { title: "Ask about international merit bursaries", detail: "UJ runs bursary schemes for top international students — email the international office with your final results." },
    ],
    requirementsSummary: "R0 online, WASSCE-friendly, English waiver common, April openings.",
    eligibilityNote: "Foreign quals evaluated against SA matric equivalents (USAf); APS score matters.",
    officialUrl: "https://www.uj.ac.za/admission/",
    competitiveNote: "Moderate; fills fast for popular programmes (health sciences, engineering).",
    successTips: "April 1 is the gun — UJ's free applications + filling-fast programmes mean week-one applicants get the best programme pick. Pair with South Africa's low living costs.",
  },
  {
    name: "University of the Witwatersrand — R100 Application (~$6)",
    slug: "wits-university",
    kind: "UNIVERSITY",
    provider: "Wits University",
    country: "South Africa",
    countryCode: "za",
    continent: "Africa",
    city: "Johannesburg",
    lat: -26.191,
    lng: 28.031,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 100,
    feeCurrency: "ZAR",
    feeConfirmedFree: false,
    feeUsdApprox: 6,
    feeNote: "Confirmed: R100 (~$6) online application fee — among the world's cheapest for a top-200 university.",
    related: [],
    fundingType: "SELF_FUNDED",
    fundingNote: "Tuition ~R 60,000–90,000/year (≈$3,300–5,000); postgraduate research funding via NRF (South African national fund) accepts internationals at some levels.",
    opensMonth: 4,
    opensDay: 1,
    closesMonth: 6,
    closesDay: 30,
    cycleNote: "International applications for 2028: ~Apr–Jun 2027 (earlier than SA applicants — internationals close first).",
    moiAccepted: false,
    moiNote: "Wits generally requires proof of English proficiency (IELTS ~6.5/Wits test) from foreign quals — WAEC English alone may not suffice; confirm with admissions.",
    englishTests: "IELTS 6.5 / Wits English test / prior English-medium degree.",
    localLanguageRequired: false,
    localLanguageNote: "English medium.",
    recommendationsRequired: false,
    recommendationsNote: "Not required for entry; NRF funding applications need supervisor support.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans at application; USAf (matric board) evaluation for foreign certificates handled during admission.",
    essayRequired: false,
    applicationSteps: [
      { title: "Apply via the Wits self-service portal (R100)", detail: "Pay by card; one fee covers your programme choice set." },
      { title: "Trigger the USAf evaluation early", detail: "Foreign certificates (WASSCE etc.) go to Universities South Africa for benchmarking — Wits starts it, but supply documents fast." },
      { title: "Upload English proof", detail: "IELTS or the Wits English proficiency test option." },
      { title: "Watch the INTERNATIONAL deadline (Jun)", detail: "International deadlines run before SA ones — missing June closes the year for you." },
      { title: "Explore NRF + faculty bursaries for postgrad", detail: "Research master's/PhD applicants: email supervisors in mining, physics, public health — Wits is Africa's research heavyweight." },
    ],
    requirementsSummary: "R100 (~$6), USAf evaluation route, early international deadlines.",
    eligibilityNote: "Foreign quals benchmarked to matric/APS; health sciences require top APS.",
    officialUrl: "https://www.wits.ac.za/postgraduate/",
    competitiveNote: "Health sciences very competitive; science/humanities moderate.",
    successTips: "Ghanaians: Wits is a bargain R6 door-opener — but the USAf document loop is slow. Scan crystal-clear WASSCE certificates and respond to their emails within 48h.",
  },
  {
    name: "University of Cape Town — R100–300 Application (~$6–16)",
    slug: "uct-cape-town",
    kind: "UNIVERSITY",
    provider: "University of Cape Town (UCT)",
    country: "South Africa",
    countryCode: "za",
    continent: "Africa",
    city: "Cape Town",
    lat: -33.957,
    lng: 18.461,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 300,
    feeCurrency: "ZAR",
    feeConfirmedFree: false,
    feeUsdApprox: 16,
    feeNote: "Confirmed: R100 for SADC applicants, R300 (~$16) for other internationals — per application.",
    related: [],
    fundingType: "SELF_FUNDED",
    fundingNote: "Tuition ~R 60,000–100,000/year for internationals; postgraduate scholarships (UCT + NRF) are real money for research degrees.",
    opensMonth: 4,
    opensDay: 1,
    closesMonth: 7,
    closesDay: 31,
    cycleNote: "International applications: ~Apr – 31 Jul 2027 for 2028 intake; some programmes (medicine) close earlier.",
    moiAccepted: false,
    moiNote: "UCT requires formal English proof for most international applicants (IELTS ~7.0 for some faculties) — English-medium degree letters considered case-by-case.",
    englishTests: "IELTS 7.0 / TOEFL 100 for many programmes; lower for some.",
    localLanguageRequired: false,
    localLanguageNote: "English medium.",
    recommendationsRequired: false,
    recommendationsNote: "UG: no. Postgrad research: supervisor + proposal expected.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scans; USAf benchmarking for foreign secondary quals.",
    essayRequired: false,
    applicationSteps: [
      { title: "Apply online with the R300 fee", detail: "UCT's application portal; fee per application (not per programme)." },
      { title: "Complete the NBT if your programme asks", detail: "National Benchmark Tests (~R 500) required for some UG faculties — check before applying." },
      { title: "Submit transcripts + English proof", detail: "Scans fine initially; keep IELTS booking option open for 7.0 faculties." },
      { title: "Postgrad: secure a supervisor before applying", detail: "UCT research master's/PhD admission effectively requires supervisor buy-in — email departments with your CV." },
      { title: "Apply for UPGC postgraduate funding", detail: "UCT's postgraduate funding office lists scholarships for African internationals — deadline usually Aug–Oct." },
    ],
    requirementsSummary: "R100–300 fee, NBT for some, strong postgrad funding culture.",
    eligibilityNote: "Foreign quals benchmarked; faculty-specific English bands.",
    officialUrl: "https://uct.ac.za/",
    competitiveNote: "South Africa's most selective university; medicine/law hard, many other faculties accessible.",
    successTips: "For master's/PhD, UCT's African-targeted funding (e.g. postgraduate funding office awards) can beat European stipends once cost-of-living differences are counted.",
  },
  {
    name: "Stellenbosch University — R100 Application (~$6)",
    slug: "stellenbosch-university",
    kind: "UNIVERSITY",
    provider: "Stellenbosch University",
    country: "South Africa",
    countryCode: "za",
    continent: "Africa",
    city: "Stellenbosch",
    lat: -33.932,
    lng: 18.864,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 100,
    feeCurrency: "ZAR",
    feeConfirmedFree: false,
    feeUsdApprox: 6,
    feeNote: "Confirmed: R100 (~$6) application fee for international applicants.",
    related: [],
    fundingType: "SELF_FUNDED",
    fundingNote: "Tuition ~R 55,000–85,000/year; strong postgraduate bursary pool, especially agriculture, viticulture, water research.",
    opensMonth: 5,
    opensDay: 1,
    closesMonth: 8,
    closesDay: 31,
    cycleNote: "International window ~May–Aug 2027 for 2028 intake.",
    moiAccepted: false,
    moiNote: "Formal English proof typically required (IELTS ~6.5); English-medium prior degree accepted case-by-case.",
    englishTests: "IELTS 6.5 / TOEFL 90 for most programmes.",
    localLanguageRequired: false,
    localLanguageNote: "English/Afrikaans dual-medium heritage — English degrees fully available.",
    recommendationsRequired: false,
    recommendationsNote: "UG: no; research degrees: supervisor support.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans at application; USAf evaluation where applicable.",
    essayRequired: false,
    applicationSteps: [
      { title: "Apply via SU's application portal (R100)", detail: "Card payment; select up to two programme choices." },
      { title: "Supply foreign-qual documents", detail: "WASSCE + transcript; USAf benchmarking if requested." },
      { title: "Upload English test results", detail: "Book IELTS early if your programme demands 6.5." },
      { title: "Check residence + visa timelines", detail: "SU handles study-visa support letters; Cape dorms need early booking." },
      { title: "Postgrad: target the bursary calendar", detail: "SU's postgraduate bursaries page opens ~Jun–Oct — agriculture/water/institute roles often include project funding." },
    ],
    requirementsSummary: "R100 fee, English test typical, strong bursary culture for research degrees.",
    eligibilityNote: "USAf benchmarked entry; faculty-specific requirements.",
    officialUrl: "https://www.sun.ac.za/english/Pages/Apply.aspx",
    competitiveNote: "Moderate; agriculture/water sciences globally ranked.",
    successTips: "If your field touches agriculture, water or food systems, Stellenbosch is Africa's best-kept secret — R6 application, globally cited research groups, real bursary money.",
  },
  {
    name: "Eötvös Loránd University (ELTE) — Free via Stipendium Hungaricum",
    slug: "elte-budapest",
    kind: "UNIVERSITY",
    provider: "Eötvös Loránd Tudományegyetem",
    country: "Hungary",
    countryCode: "hu",
    continent: "Europe",
    city: "Budapest",
    lat: 47.512,
    lng: 19.043,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: $0 application via the Stipendium Hungaricum route (apply free at apply.stipendiumhungaricum.hu). Direct self-funded applications cost ~€150.",
    related: ["stipendium-hungaricum"],
    fundingType: "FULLY_FUNDED",
    fundingNote: "Through Stipendium Hungaricum: tuition fully covered + HUF 43,700/month stipend + free dorm or housing contribution + medical insurance.",
    opensMonth: 11,
    opensDay: 15,
    closesMonth: 1,
    closesDay: 15,
    cycleNote: "Stipendium window: ~15 Nov – 15 Jan for September intake. ELTE direct admissions run Feb–Jun separately.",
    moiAccepted: true,
    moiNote: "Stipendium route is flexible on English proof — medium-of-instruction letters from English-taught programmes (incl. Ghanaian universities) are widely accepted by ELTE.",
    englishTests: "B2 for English programmes — certificate OR MOI letter, per programme.",
    localLanguageRequired: false,
    localLanguageNote: "Hungarian for Hungarian-taught (also funded via SH); English BA/MSc catalogue is broad.",
    recommendationsRequired: false,
    recommendationsNote: "SH application needs no letters at submission; sending university nomination matters (Ghana's coordinating partner).",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scans to the SH portal; originals/notarised copies at enrolment.",
    essayRequired: true,
    essayNote: "Motivation letter required in the SH application.",
    applicationSteps: [
      { title: "Get Ghana's sending-partner nomination", detail: "SH applications must be nominated by your home country's coordinator (Ghana Scholarships Secretariat) — start this contact in October." },
      { title: "Apply free at apply.stipendiumhungaricum.hu (15 Nov–15 Jan)", detail: "Choose ELTE + 2 programme preferences; upload scans + motivation letter. Zero fees." },
      { title: "Sit the ELTE entrance (online interview/exam)", detail: "Departments test informatics/maths/language online for shortlisted SH applicants (Feb–Mar)." },
      { title: "Receive the SH decision + visa package", detail: "Results ~June; Hungary's consulate handles the visa with SH support letters." },
      { title: "Arrive to full coverage", detail: "Tuition paid by the state; stipend + dorm allocated during orientation week." },
    ],
    requirementsSummary: "Genuinely $0 via SH, home-country nomination required, MOI accepted, full funding on arrival.",
    eligibilityNote: "Ghana is a Stipendium partner country; age 18+; programme-specific academic requirements.",
    officialUrl: "https://www.elte.hu/en",
    competitiveNote: "SH is competitive but Ghana's quota is real — a strong motivation letter + clean transcripts go far.",
    successTips: "The nomination step is where most Ghanaians fail — contact the Ghana Scholarships Secretariat in September/October, not January. Then the SH application itself is free and fast.",
  },
];
