import { SeedOpportunity } from "./seed-types";

// ─── Asia & Middle East ──────────────────────────────────────────────────────
export const ASIA_ME_SEED: SeedOpportunity[] = [
  {
    name: "Singapore International Graduate Award (SINGA)",
    kind: "SCHOLARSHIP",
    provider: "A*STAR, NTU, NUS, SUTD, SMU",
    country: "Singapore",
    countryCode: "sg",
    continent: "Asia",
    city: "Singapore",
    lat: 1.2966,
    lng: 103.8487,
    levels: ["phd"],
    fields: ["any", "computer science", "engineering", "natural sciences", "medicine & health", "energy"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed free. No GRE and no IELTS mandatory.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "S$2,700/month (increased to ~S$3,200 after qualifying exam) + full tuition support + one-time settlement grant up to S$1,000 + airfare up to S$1,500. Up to 4 years.",
    opensMonth: 6,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 1,
    cycleNote: "Two intake deadlines yearly: 1 June (January intake) and 1 December (August intake). One long window covers both.",
    moiAccepted: true,
    moiNote: "No IELTS/TOEFL is mandatory — SINGA states English proficiency may be demonstrated by other means; an MOI letter from a Ghanaian university plus good interview English is typically sufficient.",
    englishTests: "IELTS/TOEFL NOT mandatory; good spoken English at interview.",
    localLanguageRequired: false,
    localLanguageNote: "English is Singapore's working language.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two academic referee reports submitted online through the portal.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts and certificates uploaded directly.",
    essayRequired: true,
    essayNote: "Research proposal (2-3 pages) submitted within the form — tailored to A*STAR/NUS/NTU lab themes.",
    applicationSteps: [
      { title: "Browse A*STAR/NTU/NUS research areas (Apr-May)", detail: "The SINGA portal lists supervising labs across biomedical sciences, computing, engineering, physical sciences. Shortlist 2-3 research interests." },
      { title: "Submit one free application (by 1 Jun / 1 Dec)", detail: "Single portal for all partner institutions: CV, scans, 2 referee contacts, research proposal. No fee, no GRE, no IELTS upload." },
      { title: "Shortlist interviews (1-3 months later)", detail: "Labs interview candidates over video; expect deep questions on your proposal and prior research." },
      { title: "Award & PhD start (Jan or Aug)", detail: "Successful candidates get placement with supervisor + full funding; visa handled by the host institution." },
    ],
    requirementsSummary: "Free application, scans, 2 online referees, research proposal. No IELTS/GRE required. S$2,700-3,200/month.",
    eligibilityNote: "Open to all international graduates (excellent bachelor's/master's in science or engineering); Ghanaians have won SINGA repeatedly.",
    officialUrl: "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
    competitiveNote: "Less competitive than US/EU equivalents because fewer applicants know IELTS/GRE are waived.",
    successTips: "Email potential supervisors BEFORE the deadline with your proposal draft — pre-endorsed proposals have far higher interview rates.",
  },
  {
    name: "Global Korea Scholarship (GKS) — Graduate",
    kind: "SCHOLARSHIP",
    provider: "Government of Korea (NIIED)",
    country: "South Korea",
    countryCode: "kr",
    continent: "Asia",
    city: "Seoul",
    lat: 37.5665,
    lng: 126.9780,
    levels: ["masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee via the embassy track — confirmed free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + monthly allowance (KRW 1,600,000 grad) + round-trip flights + 1-year Korean language program + medical insurance + settlement/research allowances.",
    opensMonth: 2,
    opensDay: 15,
    closesMonth: 3,
    closesDay: 15,
    cycleNote: "Embassy track: mid-Feb to mid-March every year. University track runs September-October (check both).",
    moiAccepted: true,
    moiNote: "English-taught programs require English proof — many Korean universities accept MOI certificates; TOPIK (Korean) is NOT required to apply because the language year is built in. TOPIK 3+ later adds extra stipend.",
    englishTests: "English test scores optional but strengthen the file; MOI often accepted for English-taught programs.",
    localLanguageRequired: false,
    localLanguageNote: "Korean NOT required — a funded one-year Korean language course precedes the degree (though it extends the program by a year).",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two recommendation letters on the official GKS form (professor/employer), uploaded as scans.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts and diplomas; notarized copies only for finalists.",
    essayRequired: true,
    essayNote: "A personal statement + study plan (~1,000 words each) on GKS forms.",
    applicationSteps: [
      { title: "Choose embassy track vs university track", detail: "Embassy track (via Korean Embassy in Accra) lets you pick up to 3 universities; university track means applying to one university directly. Embassy track Feb-Mar; university track Sep-Oct — you can try both in one year!" },
      { title: "Prepare the GKS document pack (Jan)", detail: "Download the forms from Study in Korea: personal statement, study plan, 2 GKS reference forms, GKS medical assessment, passport, scans of certificates/transcripts." },
      { title: "Submit to the Embassy of Korea in Accra (Feb 15 - Mar 15)", detail: "Follow the embassy's posted document checklist; free submission." },
      { title: "First selection round (Mar-Apr)", detail: "Embassy screens documents, then interviews shortlisted candidates in Accra." },
      { title: "NIIED final selection + university placement (May-Jul)", detail: "Your file goes to Korea; NIIED confirms scholars and places you at one of your chosen universities." },
      { title: "Korean language year + degree", detail: "Arrive August, study Korean 1 year (funded), then start the degree." },
    ],
    requirementsSummary: "Free application, GKS forms, 2 references, scans, medical form. Korean year included; MOI often accepted for English tracks.",
    eligibilityNote: "Ghana is a GKS partner country (embassy track active in Accra). Age: under 40 for graduate programs; GPA 80%+ required.",
    officialUrl: "https://www.studyinkorea.go.kr/",
    competitiveNote: "~2,500 grad awards globally across ~150 countries — one of the largest fully-funded pools in the world.",
    successTips: "Pick universities OUTSIDE Seoul as 2nd/3rd choices — placement success rates are much higher and stipends go further in regional cities.",
  },
  {
    name: "MEXT Japanese Government Scholarship (Embassy Recommendation)",
    kind: "SCHOLARSHIP",
    provider: "Government of Japan (MEXT)",
    country: "Japan",
    countryCode: "jp",
    continent: "Asia",
    city: "Tokyo",
    lat: 35.6762,
    lng: 139.6503,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee via the embassy track — confirmed free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + monthly stipend (¥117,000 undergrad; ¥144,000-145,000 grad) + round-trip airfare + no tuition at national universities. Plus optional free Japanese language training.",
    opensMonth: 4,
    opensDay: 15,
    closesMonth: 6,
    closesDay: 10,
    cycleNote: "Embassy of Japan in Ghana typically opens applications ~April-June (research/graduate categories); undergraduate categories may differ — check the embassy site from March.",
    moiAccepted: true,
    moiNote: "No IELTS/TOEFL needed at the embassy application stage — screening uses MEXT's own written exams (English + math/science) held in Accra. University placement later follows your academic record.",
    englishTests: "Not required at application — embassy written exams instead.",
    localLanguageRequired: false,
    localLanguageNote: "Japanese NOT required — many graduate programs are English-taught; free Japanese training is included.",
    recommendationsRequired: false,
    recommendationsNote: "Embassy track does NOT require recommendation letters at application (unlike university recommendation track).",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned/certified transcripts submitted with the application pack; originals verified later.",
    essayRequired: true,
    essayNote: "A short study/field-of-study plan form (written inside the application).",
    applicationSteps: [
      { title: "Monitor Embassy of Japan in Ghana (from March)", detail: "The embassy announces the MEXT call with exact categories (Research/graduate, Undergraduate, College of Technology) and deadlines — usually April-June." },
      { title: "Submit documents (free)", detail: "Application form, field-of-study plan, transcripts/certificates (scans ok), health certificate. No references, no language certificates." },
      { title: "Written exams in Accra (Jun-Jul)", detail: "MEXT's own exams: English is mandatory; math/science for undergrads or field questions for researchers. Past papers are downloadable — prepare with them." },
      { title: "Interview at the embassy (Jul-Aug)", detail: "Shortlisted candidates interview in Accra about study plans." },
      { title: "University placement (Sep-Oct)", detail: "MEXT matches you with universities; for research students you may contact Japanese professors to strengthen placement." },
      { title: "Depart (Jan or Apr/Sep)", detail: "Flights and tuition fully covered; stipend starts on arrival." },
    ],
    requirementsSummary: "Free application, no IELTS, no references needed, embassy exams in Accra. Full ride to Japan.",
    eligibilityNote: "Ghana is a MEXT embassy country. Grad: born on/after April 2, 1991 (approx.); undergrad: 17-24 age band.",
    officialUrl: "https://www.studyinjapan.go.jp/en/planning/scholarship/",
    competitiveNote: "Ghana's applicant pool is small; the exam + interview format rewards preparation over connections.",
    successTips: "Download 5 years of past embassy exam papers (available free) — the English paper's format repeats. For research students, pre-contacting 2-3 Japanese professors massively improves placement quality.",
  },
  {
    name: "Chinese Government Scholarship (CSC) — Embassy Track",
    kind: "SCHOLARSHIP",
    provider: "China Scholarship Council / Ministry of Education",
    country: "China",
    countryCode: "cn",
    continent: "Asia",
    city: "Beijing",
    lat: 39.9042,
    lng: 116.4074,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "Embassy track (Type A via the Chinese Embassy in Accra) is 100% free. University track (Type B) is usually free too, though some universities charge RMB 400-800 processing.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + free university dormitory or housing allowance + monthly stipend (RMB 2,500 undergrad / 3,000 master's / 3,500 PhD) + comprehensive medical insurance.",
    opensMonth: 1,
    opensDay: 10,
    closesMonth: 4,
    closesDay: 30,
    cycleNote: "Embassy track: January-April. University Type B deadlines cluster Feb-April. CSC portal opens ~December.",
    moiAccepted: true,
    moiNote: "English-taught programs accept IELTS OR a proof-of-English-medium certificate/MOI from your university — a documented waiver route for Ghanaians at many universities.",
    englishTests: "IELTS 6.0-6.5 or MOI certificate for English-taught programs; HSK for Chinese-taught (language year available).",
    localLanguageRequired: false,
    localLanguageNote: "Not required for English-taught programs; Chinese language year included for those needing it.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two recommendation letters for graduate applicants (scans fine).",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts/diplomas uploaded to the CSC portal; notarization for winners.",
    essayRequired: true,
    essayNote: "A study plan/personal statement (~800 words) in the CSC form.",
    applicationSteps: [
      { title: "Create CSC account (Dec-Jan)", detail: "Register at campuschina.org — the official portal. Choose Type A (embassy, agency number for Ghana) or Type B (a specific university)." },
      { title: "Apply to the Chinese Embassy in Accra (Jan-Apr)", detail: "Submit the online form + upload scans: passport, transcripts/diplomas, study plan, 2 letters, physical exam form, language proof (MOI ok)." },
      { title: "Embassy pre-selection (Apr-May)", detail: "The embassy shortlists and forwards files to China." },
      { title: "CSC final review (May-Jul)", detail: "CSC confirms awards and university placements; admission letters arrive June-August." },
      { title: "Visa & arrival (Aug-Sep)", detail: "JW201 form + admission letter = X1 visa; dormitory usually pre-assigned." },
    ],
    requirementsSummary: "Free (Type A), scans, 2 letters, study plan, MOI accepted for English tracks. Dorms + stipend + tuition all covered.",
    eligibilityNote: "Ghana eligible via the Chinese Embassy in Accra; age limits (UG <25, MSc <35, PhD <40).",
    officialUrl: "https://www.campuschina.org/",
    competitiveNote: "The largest scholarship pool on earth — tens of thousands of awards; embassy-track odds for Ghanaians are favorable.",
    successTips: "Type B applications to 2-3 universities directly (free on most) alongside the embassy track multiply chances — just don't accept duplicate awards.",
  },
  {
    name: "Schwarzman Scholars Program",
    kind: "SCHOLARSHIP",
    provider: "Schwarzman Scholars, Tsinghua University",
    country: "China",
    countryCode: "cn",
    continent: "Asia",
    city: "Beijing",
    lat: 40.0030,
    lng: 116.3260,
    levels: ["masters"],
    fields: ["public policy", "business & economics", "social sciences"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + room & board on the Tsinghua campus + travel to/from Beijing + in-country study tours + personal stipend (~$4,000) + health insurance. One-year Master's in Global Affairs.",
    opensMonth: 4,
    opensDay: 25,
    closesMonth: 9,
    closesDay: 10,
    cycleNote: "Global application opens late April; deadline ~10 September (early-October for China-based applicants). Decisions in November; program starts the following August.",
    moiAccepted: true,
    moiNote: "English fluency required but NO standardized test is demanded — the video essay and interview carry that weight. Ghanaian English-medium graduates fit naturally.",
    englishTests: "No TOEFL/IELTS required — fluency assessed via application + interview.",
    localLanguageRequired: false,
    localLanguageNote: "None — the program is fully English; Chinese classes provided.",
    recommendationsRequired: true,
    recommendationsCount: 3,
    recommendationsNote: "Three recommendation letters — at least one direct supervisor (for employed applicants), submitted online.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned/unofficial transcripts accepted at application; official copies from finalists.",
    essayRequired: true,
    essayNote: "A 600-word leadership essay + a 500-word 'current affairs' essay — the heart of the application.",
    applicationSteps: [
      { title: "Draft the two essays (Jun-Jul)", detail: "Leadership essay: one concrete moment you led under pressure. Current-affairs essay: your argument on a global issue. Both define your candidacy." },
      { title: "Secure 3 recommenders (Jul)", detail: "One must be a direct supervisor if you're employed; brief them with your essay themes." },
      { title: "Apply free by ~10 September", detail: "Online form + video essay (60 seconds) + scans + age check (18-28)." },
      { title: "Semi-final interviews (Oct-Nov)", detail: "Regional panels (for African candidates usually via video) assess poise, global awareness, and leadership signal." },
      { title: "Final selection & start (Nov → next Aug)", detail: "~150 scholars/year join Tsinghua's Schwarzman College — a living community of future leaders." },
    ],
    requirementsSummary: "Free, 3 references, 2 essays + video, scans. No language tests. Age 18-28. Fully funded 1-year master's.",
    eligibilityNote: "Open to all nationalities; Ghanaian applicants welcome — program seeks global diversity.",
    officialUrl: "https://www.schwarzmanscholars.org/",
    competitiveNote: "~4,000+ applicants for ~150 places.",
    successTips: "The video essay matters more than people think — practice until it shows natural authority, not recitation.",
  },
  {
    name: "Yenching Academy Fellowship (Peking University)",
    kind: "SCHOLARSHIP",
    provider: "Yenching Academy, Peking University",
    country: "China",
    countryCode: "cn",
    continent: "Asia",
    city: "Beijing",
    lat: 39.9926,
    lng: 116.3061,
    levels: ["masters"],
    fields: ["arts & humanities", "social sciences", "public policy", "business & economics", "law"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + housing on campus + living stipend + one round-trip airfare + field study across China. Master's in China Studies (English-taught, customizable).",
    opensMonth: 9,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 1,
    cycleNote: "Applications open ~early September and close ~1 December (international applicants) for the following September.",
    moiAccepted: true,
    moiNote: "No Chinese required; English proficiency shown through application/interview — no standardized test mandated.",
    englishTests: "No TOEFL/IELTS required explicitly.",
    localLanguageRequired: false,
    localLanguageNote: "Program is English-taught; Chinese language study encouraged and supported.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two recommendation letters (academic or professional) submitted online.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts accepted.",
    essayRequired: true,
    essayNote: "A personal statement (~750 words) on your interest in China + a research/professional proposal within China Studies.",
    applicationSteps: [
      { title: "Frame your 'China question' (Sep)", detail: "Decide what you want to understand about China's role in your field (e.g. China-Africa trade) — this anchors the statement and proposal." },
      { title: "Apply free by ~1 December", detail: "Online form: statement, proposal, CV, scans, 2 referees, optional video." },
      { title: "Shortlist interviews (Jan-Feb)", detail: "Video interviews probe your China engagement and intellectual range." },
      { title: "Fellowship begins (Sep)", detail: "~120 fellows/year from 40+ countries; full funding throughout." },
    ],
    requirementsSummary: "Free application, 2 references, scans, statement + proposal. No Chinese needed. Fully funded China Studies master's.",
    eligibilityNote: "Bachelor's holders under 25 preferred (flexible); all nationalities.",
    officialUrl: "https://yenchingacademy.pku.edu.cn/",
    competitiveNote: "~1,800 applications for ~120 fellowships.",
    successTips: "Ghana-China trade/development angles are distinctive in this pool — own that narrative.",
  },
  {
    name: "KAUST Fellowship (King Abdullah University)",
    kind: "UNIVERSITY",
    provider: "King Abdullah University of Science and Technology",
    country: "Saudi Arabia",
    countryCode: "sa",
    continent: "Middle East",
    city: "Thuwal",
    lat: 22.3059,
    lng: 39.1189,
    levels: ["masters", "phd"],
    fields: ["computer science", "engineering", "natural sciences", "energy", "environment", "agriculture & food"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — confirmed free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + free on-campus housing + $20,000-30,000/year living allowance + medical + relocation support. Every admitted student receives the fellowship — no separate application.",
    rolling: true,
    cycleNote: "Rolling review with Fall, Spring, and Summer intakes — apply 4-6 months before your target term.",
    moiAccepted: true,
    moiNote: "IELTS/TOEFL is listed as required, but KAUST admits students provisionally without a test and lets you submit scores (or demonstrate English-medium education) around arrival — Ghanaians with MOI letters have been admitted this way.",
    englishTests: "IELTS 6.5 / TOEFL 79 preferred; provisional admission possible without one.",
    localLanguageRequired: false,
    localLanguageNote: "None — campus language is English.",
    recommendationsRequired: true,
    recommendationsCount: 3,
    recommendationsNote: "Two to three academic recommendation letters submitted online by referees.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned/unofficial transcripts accepted at application.",
    essayRequired: true,
    essayNote: "A personal statement focused on research interests.",
    applicationSteps: [
      { title: "Match your research to KAUST faculty", detail: "Browse KAUST's research groups (solar, water desalination, AI, computational biology...). Name 2-3 faculty in your statement." },
      { title: "Apply free anytime (rolling)", detail: "Online form: CV, scans, statement, 2-3 referee contacts. No fee, no GRE." },
      { title: "Faculty-led review (2-8 weeks)", detail: "Admission is professor-driven; strong faculty interest can override test-score gaps." },
      { title: "Admission + automatic fellowship", detail: "Every admit gets housing + stipend — you never apply for funding separately." },
      { title: "Relocate to Thuwal", detail: "KAUST handles visa, flights, and airport pickup; families get campus housing support." },
    ],
    requirementsSummary: "Free rolling application, scans, 2-3 referees, statement. Automatic full fellowship for all admits.",
    eligibilityNote: "Strong science/engineering bachelor's or master's; all nationalities; Ghana well represented.",
    officialUrl: "https://admissions.kaust.edu.sa/",
    competitiveNote: "Selective but far more accessible than US peers — the automatic fellowship removes funding stress entirely.",
    successTips: "Apply in September-October for the Fall cycle when professors have fresh funding; reference specific KAUST lab outputs.",
  },
  {
    name: "Khalifa University Graduate Scholarships",
    kind: "UNIVERSITY",
    provider: "Khalifa University of Science and Technology",
    country: "United Arab Emirates",
    countryCode: "ae",
    continent: "Middle East",
    city: "Abu Dhabi",
    lat: 24.4539,
    lng: 54.3773,
    levels: ["masters", "phd"],
    fields: ["engineering", "computer science", "energy", "natural sciences", "medicine & health"],
    feeAmount: 0,
    feeCurrency: "AED",
    feeConfirmedFree: true,
    feeNote: "No application fee for graduate admissions — confirmed free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + monthly stipend (MSc ~AED 8,000; PhD ~AED 10,000-12,000) + textbooks + medical insurance; top students get housing. Ranked #1 in the Arab region for engineering.",
    rolling: true,
    cycleNote: "Rolling review for Fall and Spring intakes — apply at least 4 months ahead.",
    moiAccepted: true,
    moiNote: "IELTS 6.5 (iBT 91) is standard, but MOI certificates from English-medium universities are considered case-by-case — attach yours and email admissions.",
    englishTests: "IELTS 6.5 / TOEFL 91 (MOI considered case-by-case).",
    localLanguageRequired: false,
    localLanguageNote: "None — English instruction throughout.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two referees submit online forms.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts accepted at application.",
    essayRequired: true,
    essayNote: "Statement of purpose for graduate programs.",
    applicationSteps: [
      { title: "Choose an MSc/PhD program", detail: "Electrical/ME/aerospace engineering, CS/AI, nuclear energy, biomedical — check each program's 'scholarships' tab (most admits get funding)." },
      { title: "Apply free online (rolling)", detail: "Upload CV, scans, statement, referee contacts. No fee." },
      { title: "Admission + scholarship decision", detail: "The same file is considered for the full scholarship package — no separate application." },
      { title: "Visa & relocate", detail: "University sponsors UAE visa; stipend starts with enrollment." },
    ],
    requirementsSummary: "Free rolling application, scans, 2 referees, statement. Automatic scholarship consideration; MOI case-by-case.",
    eligibilityNote: "All nationalities; strong engineering/science records.",
    officialUrl: "https://www.ku.ac.ae/admissions",
    competitiveNote: "Generous funding with lighter competition than KAUST — good pairing for the UAE.",
    successTips: "Email 1-2 target faculty with your CV before applying — funded RA positions often route through professors.",
  },
  {
    name: "Islamic Development Bank Scholarships (IsDB)",
    kind: "SCHOLARSHIP",
    provider: "Islamic Development Bank",
    country: "Saudi Arabia",
    countryCode: "sa",
    continent: "Middle East",
    city: "Jeddah",
    lat: 21.4858,
    lng: 39.1925,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any", "engineering", "medicine & health", "agriculture & food", "computer science", "energy"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee — online submission only.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Tuition + monthly living stipend + health insurance; master's/PhD are scholarship-plus-loan structures (repayment after graduation is to a development fund, community service can offset); undergrad is interest-free loan-scholarship.",
    opensMonth: 2,
    opensDay: 1,
    closesMonth: 3,
    closesDay: 20,
    cycleNote: "Call usually opens February and closes ~20 March (dates shift slightly yearly).",
    moiAccepted: true,
    moiNote: "For study in home country or abroad — language requirements follow your chosen university; MOI certificates commonly accepted by English-taught universities.",
    englishTests: "Per host university; MOI often accepted.",
    localLanguageRequired: false,
    localLanguageNote: "None imposed by IsDB.",
    recommendationsRequired: false,
    recommendationsNote: "Not required for most IsDB tracks.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans uploaded to the portal.",
    essayRequired: true,
    essayNote: "A short statement on how your study serves development in your home country — IsDB's core mission.",
    applicationSteps: [
      { title: "Confirm eligibility (Jan)", detail: "Citizen of an IsDB member country (Ghana IS a member) or Muslim community in non-member countries; strong academics in development-relevant fields." },
      { title: "Apply on the IsDB portal (Feb 1 - Mar 20)", detail: "Free online form + scans + development statement." },
      { title: "Shortlisting & interviews", detail: "Country-level shortlists; some tracks interview online." },
      { title: "Award & placement", detail: "You secure admission at an approved university (IsDB advises on eligible programs); funding follows." },
    ],
    requirementsSummary: "Free application, scans, development statement. Ghana is an IsDB member country.",
    eligibilityNote: "IsDB member countries incl. Ghana; science & technology focus.",
    officialUrl: "https://www.isdb.org/scholarships",
    competitiveNote: "Underestimated by West African applicants — solid odds with a good development narrative.",
    successTips: "Anchor your statement in a specific SDG-relevant problem in Ghana (health, food security, energy access).",
  },
  {
    name: "Hong Kong PhD Fellowship Scheme (HKPFS)",
    kind: "SCHOLARSHIP",
    provider: "Research Grants Council of Hong Kong",
    country: "Hong Kong",
    countryCode: "hk",
    continent: "Asia",
    city: "Hong Kong",
    lat: 22.3193,
    lng: 114.1694,
    levels: ["phd"],
    fields: ["any"],
    feeAmount: 300,
    feeCurrency: "HKD",
    feeConfirmedFree: false,
    feeNote: "The RGC fellowship application is free, but you must also apply to the university's PhD program where HK$180-500 application fees apply (some universities waive them for HKPFS applicants — HKUST and CityU have waived in recent cycles).",
    fundingType: "FULLY_FUNDED",
    fundingNote: "HK$331,200/year stipend (~US$42,000) + HK$13,800/year conference travel allowance for 3 years + full tuition waiver at HKU/CUHK/HKUST/PolyU/CityU/BaptistU/LingU/EdUHK.",
    opensMonth: 9,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 1,
    cycleNote: "RGC portal opens 1 September; initial application deadline 1 December at 12:00 (HKT) sharp, for the following September.",
    moiAccepted: true,
    moiNote: "Hong Kong universities commonly accept degrees from English-medium institutions (Ghana included) in lieu of IELTS — department-dependent; state your MOI clearly.",
    englishTests: "IELTS 6.5/TOEFL 80 per university — MOI often accepted for English-medium degrees.",
    localLanguageRequired: false,
    localLanguageNote: "English throughout.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two academic references in the RGC form.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans at initial application; certified later.",
    essayRequired: true,
    essayNote: "Research proposal (2-5 pages) + personal statement.",
    applicationSteps: [
      { title: "Pick 1-2 universities + supervisors (Aug-Sep)", detail: "Contact prospective supervisors at HK universities with your proposal — their endorsement shapes the departmental ranking." },
      { title: "Submit RGC initial application by 1 Dec", detail: "Free on the RGC HKPFS portal: proposal, statement, scans, 2 referees, chosen institutions." },
      { title: "Complete university applications (Dec)", detail: "Each chosen university directs you to its PhD application (small fee; waivers exist for HKPFS)." },
      { title: "Panel review (Jan-Apr)", detail: "Universities shortlist; RGC panel makes final fellowship decisions." },
      { title: "Award (Apr-May)", detail: "~325 fellowships/year; non-winners frequently still receive regular PhD studentships with full funding." },
    ],
    requirementsSummary: "Free RGC application + small university fee (often waived). Scans, 2 referees, proposal. HK$331k/yr stipend.",
    eligibilityNote: "All nationalities; top-tier academic record expected.",
    officialUrl: "https://cerg1.ugc.edu.hk/hkpfs/index.html",
    competitiveNote: "~325 awards but the fallback (normal studentship ~HK$220k/yr) softens the risk.",
    successTips: "Apply through 2 universities in the single RGC form — double exposure for one proposal.",
  },
  {
    name: "ICCR Scholarships (Indian Council for Cultural Relations)",
    kind: "SCHOLARSHIP",
    provider: "Government of India (ICCR)",
    country: "India",
    countryCode: "in",
    continent: "Asia",
    city: "New Delhi",
    lat: 28.6139,
    lng: 77.2090,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any", "engineering", "medicine & health", "business & economics", "arts & humanities", "natural sciences"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee on the A2A portal — free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + monthly living stipend (INR 18,000-25,000 by level) + accommodation or house-rent allowance + annual grant for books + medical coverage under CGHS.",
    opensMonth: 2,
    opensDay: 1,
    closesMonth: 4,
    closesDay: 30,
    cycleNote: "A2A portal call usually runs February-April for the July academic year.",
    moiAccepted: true,
    moiNote: "Indian universities teach in English; for English-medium applicants from Ghana, IELTS is generally NOT demanded — the A2A form asks for English-medium schooling evidence, which Ghana satisfies easily.",
    englishTests: "Not required for English-medium backgrounds (Ghana qualifies).",
    localLanguageRequired: false,
    localLanguageNote: "None — English instruction at ICCR-allocated universities.",
    recommendationsRequired: false,
    recommendationsNote: "Not required in the A2A form.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned certificates/transcripts uploaded directly.",
    essayRequired: true,
    essayNote: "A ~500-word 'Statement of Purpose' in the portal.",
    applicationSteps: [
      { title: "Register on the A2A portal (Feb)", detail: "a2ascholarships.iccr.gov.in — choose the Africa scholarship scheme available to Ghanaians." },
      { title: "Select up to 5 universities/programs", detail: "Rank 5 choices across ICCR-recognized universities; upload scans + SOP. Free." },
      { title: "University acceptance rounds (Mar-May)", detail: "Universities accept/decline based on your ranking; you accept the first available offer." },
      { title: "Visa & July arrival", detail: "ICCR issues the award letter for the Indian visa; stipends start on enrollment." },
    ],
    requirementsSummary: "Free portal application, scans, SOP, 5 university choices. No IELTS needed for English-medium Ghanaians.",
    eligibilityNote: "Ghana included in ICCR's Africa schemes (confirm annual slots with the Indian High Commission in Accra).",
    officialUrl: "https://a2ascholarships.iccr.gov.in/",
    competitiveNote: "Large number of slots across Africa; engineering and commerce are the biggest pools.",
    successTips: "Include at least one 'newer' university (NITs, Pune, Hyderabad) among your 5 choices — placement is faster outside the most famous names.",
  },
];
