import { SeedOpportunity } from "./seed-types";

// ─── Hungary, Türkiye, EU-wide, France, Switzerland, Belgium, Ireland, Sweden, Italy, Russia, Germany ──
export const EUROPE_SEED_2: SeedOpportunity[] = [
  {
    name: "Stipendium Hungaricum Scholarship",
    kind: "SCHOLARSHIP",
    provider: "Government of Hungary (Tempus Foundation)",
    country: "Hungary",
    countryCode: "hu",
    continent: "Europe",
    city: "Budapest",
    lat: 47.4979,
    lng: 19.0402,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any", "engineering", "computer science", "medicine & health", "agriculture & food", "business & economics", "natural sciences"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "Application is 100% free on the Tempus application system — one of the very few government scholarships covering ALL degree levels with a free application.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition exemption + monthly stipend (HUF 43,700 BA/MSc; HUF 140,000 PhD) + free dormitory or HUF 40,000 housing contribution + medical insurance. PhD adds research support.",
    opensMonth: 11,
    opensDay: 15,
    closesMonth: 1,
    closesDay: 15,
    cycleNote: "Reliable fixed window every year: 15 November - 15 January for September intake.",
    moiAccepted: true,
    moiNote: "English-taught programmes require English proof — many Hungarian universities accept an MOI letter from a Ghanaian university in place of IELTS (each university lists this in its entry requirements).",
    englishTests: "IELTS 5.5-6.5 or MOI certificate (university-specific).",
    localLanguageRequired: false,
    localLanguageNote: "NOT required — thousands of seats are English-taught. Optional free Hungarian language year available if you pick Hungarian-taught tracks.",
    recommendationsRequired: false,
    recommendationsNote: "Not required — motivation letter + documents only.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned certificates and transcripts uploaded directly; certified copies only at enrolment.",
    essayRequired: true,
    essayNote: "Motivation letter (~1 page) submitted inside the application system.",
    applicationSteps: [
      { title: "Check the Ghana-Hungary bilateral list", detail: "Ghana has an allocation of Stipendium Hungaricum seats via the Ministry of Education — Ghanaian applicants apply both in the Tempus system AND register interest with Ghana's Scholarship Secretariat." },
      { title: "Pick up to 2 programmes + universities (Nov-Jan)", detail: "Browse 600+ English-taught programmes; you may apply for 2 choices. Fee: zero." },
      { title: "Upload scans to the Tempus portal", detail: "Passport, scanned certificates/transcripts, motivation letter, language proof (MOI ok), medical certificate — all scans, no originals at this stage." },
      { title: "Entrance exams/university review (Feb-Apr)", detail: "Universities may hold online entrance exams or interviews (esp. medicine/engineering); they then rank candidates." },
      { title: "Nomination via Ghana's Ministry + Hungarian decision (Apr-Jun)", detail: "Your application goes through the sending partner (Ghana's Ministry of Education) for endorsement before final Hungarian approval." },
      { title: "Visa + September arrival", detail: "Free tuition letter supports the visa; dormitory placement is automatic for most freshmen." },
    ],
    requirementsSummary: "Free application, scanned documents, MOI often accepted, no references needed, fixed Nov 15 - Jan 15 window.",
    eligibilityNote: "Ghana has participated since 2016 — dedicated bilateral seats each year.",
    officialUrl: "https://stipendiumhungaricum.hu/",
    competitiveNote: "Globally ~44,000 applications for ~5,000 scholarships; Ghanaians enjoy a dedicated quota so odds beat the global average.",
    successTips: "Choose your second programme strategically (less popular universities like Miskolc/Dunaújváros have far fewer applicants for the same quality).",
  },
  {
    name: "Türkiye Bursları (Türkiye Scholarships)",
    kind: "SCHOLARSHIP",
    provider: "Government of Türkiye",
    country: "Türkiye",
    countryCode: "tr",
    continent: "Europe",
    city: "Istanbul",
    lat: 41.0082,
    lng: 28.9784,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "No application fee at any level — confirmed free every cycle.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + monthly stipend (undergrad ~$200, master's ~$260, PhD ~$330) + free state accommodation + Turkish language year + return flights + health insurance + one-year Turkish course.",
    opensMonth: 1,
    opensDay: 10,
    closesMonth: 2,
    closesDay: 20,
    cycleNote: "Very consistent window: 10 January - 20 February every year.",
    moiAccepted: true,
    moiNote: "For English-taught programmes, universities accept IELTS/TOEFL OR the university's own free English proficiency exam — many also accept MOI certificates from English-medium universities.",
    englishTests: "Optional: IELTS/TOEFL OR sit the university's own exam; some programmes accept MOI.",
    localLanguageRequired: false,
    localLanguageNote: "Not required to apply — a fully funded 1-year Turkish language course is included, and thousands of seats are English-taught.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two reference letters uploaded as scans — teacher/employer letters are accepted as scanned PDFs.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts/diplomas (or 'proof of graduation') accepted at application.",
    essayRequired: false,
    essayNote: "No long essays — short answer questions in the form.",
    applicationSteps: [
      { title: "Apply Jan 10 - Feb 20 at turkiyeburslari.gov.tr", detail: "One application form for up to 12 programme preferences. Free. Upload scans: passport, transcript/diploma (or graduation proof), 2 reference letters, optional test scores." },
      { title: "Shortlisting (Mar-May)", detail: "Candidates are screened on academics + short answers; shortlist emails arrive in April-May." },
      { title: "Online/embassy interview (May-Jun)", detail: "Interview at the Turkish Embassy in Accra (or online for some cycles) — 15-20 minutes on your goals and choices." },
      { title: "Placement & university admission (Jun-Jul)", detail: "Successful candidates are placed at Turkish universities matching their preferences." },
      { title: "Visa + arrival (Aug-Sep)", detail: "Flight tickets and accommodation are arranged; one year of free Turkish language study precedes degree programmes (or you test out). " },
    ],
    requirementsSummary: "Free application, scans + 2 reference letters, no essays, no language certificate mandatory, fixed Jan 10 - Feb 20 window.",
    eligibilityNote: "Ghana fully eligible; undergrad applicants need 70%+ average, graduate 75%+; age limits (UG <21, MSc <30, PhD <35).",
    officialUrl: "https://www.turkiyeburslari.gov.tr/",
    competitiveNote: "~165,000 applicants for ~5,000 awards globally, but Ghana's applicant pool is smaller than Nigeria/Kenya's.",
    successTips: "Rank all 12 preferences — candidates who list only famous universities (Istanbul/Ankara) are harder to place than those including Izmir/Anatolian universities.",
  },
  {
    name: "Erasmus Mundus Joint Masters (EMJM) Scholarships",
    kind: "SCHOLARSHIP",
    provider: "European Commission",
    country: "Multiple EU countries",
    countryCode: "eu",
    continent: "Europe",
    city: "Brussels",
    lat: 50.8466,
    lng: 4.3518,
    levels: ["masters"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "The large majority of EMJM consortia charge NO application fee (a handful charge €30-100 — each catalogue page states this). One application can put you in 2-3 European countries.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "€1,400/month for 12-24 months + full tuition waiver + travel/installation costs + comprehensive insurance. Study in 2-3 countries with a joint/double degree.",
    opensMonth: 10,
    opensDay: 1,
    closesMonth: 2,
    closesDay: 15,
    cycleNote: "Consortia open applications Oct-December with deadlines typically Nov-Feb (most mid-January) for September intake.",
    moiAccepted: true,
    moiNote: "Varies by consortium — a growing number accept MOI certificates from English-medium universities (check each EMJM's 'admission requirements' for wording like 'proof of English-medium education').",
    englishTests: "IELTS 6.0-7.0 typical; MOI accepted by some consortia.",
    localLanguageRequired: false,
    localLanguageNote: "Never required — all EMJM are English-taught.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two academic/professional recommendation letters uploaded as PDFs.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned (unofficial) transcripts are standard at application; certified/enrolled copies only after selection.",
    essayRequired: true,
    essayNote: "Motivation letter tailored to the consortium's objectives (500-1,000 words).",
    applicationSteps: [
      { title: "Search the EMJM catalogue", detail: "Filter the Erasmus Mundus catalogue (200+ programmes across all fields) — each lists its fee policy, English requirements, and deadline. Shortlist 5-8 programmes; you can apply to as many as you like, mostly free." },
      { title: "Prepare a master document pack (Sep)", detail: "One pack serves all applications: CV (Europass), scanned transcript + certificate, 2 reference letters, motivation letter template you customize, passport scan." },
      { title: "Apply to each consortium (Oct-Feb)", detail: "Follow each consortium's own portal — they are independent. No fee for most. Confirm 'unofficial transcripts accepted' per programme." },
      { title: "Consortium ranking (Feb-Apr)", detail: "Each consortium ranks scholarship candidates against its criteria (academics, relevance, regional balance)." },
      { title: "Scholarship offer (Mar-May)", detail: "You can hold multiple offers briefly — decline others promptly so scholarship spots cascade to waitlisted candidates." },
      { title: "Visa & multi-country mobility", detail: "The consortium issues admission + funding letters for your visa; you'll live in 2-3 countries (e.g. Belgium → Portugal → Sweden) during the degree." },
    ],
    requirementsSummary: "Bachelor's degree, scans, 2 letters, motivation. Mostly free applications. MOI accepted by many consortia. Apply to several at once.",
    eligibilityNote: "Open to ALL nationalities; some programmes give extra slots to 'partner country' applicants (incl. Ghana).",
    officialUrl: "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
    competitiveNote: "Per-programme odds are 3-10% for scholarships — but applying to 6-8 programmes lifts your season odds dramatically.",
    successTips: "Ghanaians win EMJM every year in water management, renewable energy, and public health consortia. Mirror each consortium's own language from its 'objectives' section in your motivation letter.",
  },
  {
    name: "Eiffel Excellence Scholarship Programme",
    kind: "SCHOLARSHIP",
    provider: "French Ministry for Europe and Foreign Affairs",
    country: "France",
    countryCode: "fr",
    continent: "Europe",
    city: "Paris",
    lat: 48.8566,
    lng: 2.3522,
    levels: ["masters", "phd"],
    fields: ["any", "engineering", "computer science", "business & economics", "public policy", "law", "natural sciences"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "No fee from the Eiffel programme — the French institution applies on your behalf. Note: some institutions charge their own small application fee for admission (€0-100); many (Université Paris-Saclay, Grenoble, most public universities) apply for you free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "€1,181/month for master's (€1,700 for PhD) + international return flights + insurance + cultural activities. Tuition is generally covered or waived by the host institution for laureates.",
    opensMonth: 10,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 10,
    cycleNote: "Institutions collect candidates Oct-December; Campus France's central deadline is ~10 January each year.",
    moiAccepted: true,
    moiNote: "French universities offering English-taught master's frequently accept MOI certificates — check each institution's Eiffel call page.",
    englishTests: "Per institution; English-taught tracks accept IELTS or often MOI.",
    localLanguageRequired: false,
    localLanguageNote: "French NOT required for English-taught programmes — and laureates get free French courses to settle in.",
    recommendationsRequired: false,
    recommendationsNote: "You don't submit references — the institution writes the Eiffel nomination dossier for you.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans uploaded to the institution's own admission portal.",
    essayRequired: true,
    essayNote: "Motivation letter to the institution (which feeds into its Eiffel nomination).",
    applicationSteps: [
      { title: "Pick Eiffel-participating institutions", detail: "Check the official list of French institutions that run Eiffel nominations (Sorbonne, Paris-Saclay, Grenoble INP, Institut Polytechnique de Paris, Sciences Po...)." },
      { title: "Apply for admission at the institution (Oct-Dec)", detail: "Apply to the master's programme and SAY you want to be considered for Eiffel — the institution builds your nomination file (most do this free)." },
      { title: "Institution nominates you (by ~10 Jan)", detail: "The institution submits your dossier to Campus France. You cannot apply to Eiffel directly — the nomination IS your application." },
      { title: "Campus France decision (Mar)", detail: "Results in mid-March. Non-selected candidates may still get admission + other institution scholarships." },
      { title: "Visa & arrival (Aug-Sep)", detail: "Laureates get priority handling for the long-stay visa." },
    ],
    requirementsSummary: "Free via institution nomination; scans accepted; English-taught tracks available; French not required.",
    eligibilityNote: "Non-French nationals only; age limit ≤25 for master's (born after ~2000), ≤30 for PhD. Ghanaians fully eligible.",
    officialUrl: "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",
    competitiveNote: "~1,000 awards/year across all institutions; engineering and political science tracks are the largest pools.",
    successTips: "Contact the international office of 2-3 institutions in October asking exactly how they shortlist Eiffel candidates — processes differ and some require extra documents.",
  },
  {
    name: "Ampère Excellence Scholarships (ENS Lyon)",
    kind: "SCHOLARSHIP",
    provider: "École Normale Supérieure de Lyon",
    country: "France",
    countryCode: "fr",
    continent: "Europe",
    city: "Lyon",
    lat: 45.7485,
    lng: 4.8519,
    levels: ["masters"],
    fields: ["natural sciences", "computer science", "mathematics", "engineering", "arts & humanities", "social sciences"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "Free application to both ENS de Lyon admission and the Ampère scholarship.",
    fundingType: "PARTIAL",
    fundingNote: "€1,000/month for 12-24 months (M1 + M2), plus help finding subsidized housing. Not a full ride — but ENS Lyon's own tuition is near-zero (French public rates ~€250/yr).",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 31,
    cycleNote: "Applications typically open December and close mid-to-late January for September intake.",
    moiAccepted: true,
    moiNote: "English-taught master's at ENS Lyon accept English-medium degrees; MOI letters generally accepted.",
    englishTests: "C1 English or MOI for English tracks; French tracks need B2 French.",
    localLanguageRequired: false,
    localLanguageNote: "English-taught master's available; French B2 only for French-language tracks.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two academic references submitted online.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans accepted.",
    essayRequired: true,
    essayNote: "Research/study project statement — ENS is research-first, so a concrete academic project matters.",
    applicationSteps: [
      { title: "Choose an ENS Lyon master's", detail: "Sciences (maths, physics, CS, chemistry, biology) or humanities — check which are English-taught." },
      { title: "Apply for admission + tick Ampère (Dec-Jan)", detail: "Single application portal; scholarship consideration is integrated and free." },
      { title: "Selection (Feb-Mar)", detail: "Committee ranks on academic excellence and the project statement." },
      { title: "Award & enrolment (Sep)", detail: "€1,000/month starts with enrolment; top-up with the near-zero tuition to live cheaply." },
    ],
    requirementsSummary: "Free application, 2 references, scans, project statement. €1,000/month at near-zero tuition = effectively fully funded.",
    eligibilityNote: "International students only (non-French-bachelor holders prioritized); Ghanaians eligible.",
    officialUrl: "https://www.ens-lyon.fr/en/studies/admissions",
    competitiveNote: "~20-30 awards/year; smaller pool than Paris schools.",
    successTips: "Name a specific ENS Lyon research lab in your statement — committees reward fit with their lab culture.",
  },
  {
    name: "Swiss Government Excellence Scholarships",
    kind: "SCHOLARSHIP",
    provider: "Swiss Confederation (FCS)",
    country: "Switzerland",
    countryCode: "ch",
    continent: "Europe",
    city: "Bern",
    lat: 46.9480,
    lng: 7.4474,
    levels: ["phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "CHF",
    feeConfirmedFree: true,
    feeNote: "No application fee for the Swiss Excellence scholarship itself.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "CHF 1,920/month + tuition fee exemption + health insurance + housing allowance (~CHF 300) + airfare for some countries. For PhD/research only (not taught master's).",
    opensMonth: 9,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 15,
    cycleNote: "Country deadlines fall between September and December (embassy in your country sets the exact date).",
    moiAccepted: true,
    moiNote: "Language requirements follow your host professor — English-medium research is standard in Swiss labs (ETH/EPFL/UniGE), and MOI-backed English is usually fine.",
    englishTests: "Usually not demanded formally for research candidates — the host professor's acceptance matters most.",
    localLanguageRequired: false,
    localLanguageNote: "Depends on the host institution's language; PhD research in English is widespread.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two academic references on the FCS reference forms + a research proposal + CV.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans of degree certificates and transcripts at application.",
    essayRequired: true,
    essayNote: "A 5-10 page research proposal is the heart of the application.",
    applicationSteps: [
      { title: "Find a Swiss professor (Jun-Aug)", detail: "Email professors at ETH Zurich, EPFL, Basel, Geneva etc. with your CV + 1-page research idea. The acceptance/commitment letter from a professor is mandatory — this is 80% of the work." },
      { title: "Prepare the FCS dossier (Aug-Sep)", detail: "Download forms from the Swiss embassy covering your region; complete research proposal, 2 reference forms, medical form, scans." },
      { title: "Submit to the embassy (Sep-Dec)", detail: "Ghanaian applicants typically submit through the Swiss Embassy in Accra/Abidjan — confirm the current channel. No fee." },
      { title: "Federal Commission review (Jan-Mar)", detail: "FCS in Bern scores proposals with input from Swiss universities." },
      { title: "Award & matriculation (Apr-Oct)", detail: "Awards confirmed ~spring; you register as a doctoral researcher and relocate by autumn." },
    ],
    requirementsSummary: "Professor acceptance + research proposal + 2 FCS references + scans. Free application. PhD/research only.",
    eligibilityNote: "Country-based allocations; Ghana falls under the Swiss embassy regional process — verify the current channel for Ghana.",
    officialUrl: "https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships",
    competitiveNote: "~300 awards globally; the professor's genuine commitment is the decisive variable.",
    successTips: "Write professor emails that reference their last 2 papers and propose a specific extension — generic emails get ignored.",
  },
  {
    name: "VLIR-UOS Scholarships (ICP Connect)",
    kind: "SCHOLARSHIP",
    provider: "Flemish Interuniversity Council (Belgium)",
    country: "Belgium",
    countryCode: "be",
    continent: "Europe",
    city: "Brussels",
    lat: 50.8503,
    lng: 4.3517,
    levels: ["masters"],
    fields: ["development studies", "environment", "agriculture & food", "medicine & health", "engineering", "water", "public policy"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "No application fee for ICP Connect master's programmes — confirmed free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + ~€1,150-1,300/month allowance + international travel + visa/insurance + accommodation allowance.",
    opensMonth: 11,
    opensDay: 1,
    closesMonth: 2,
    closesDay: 28,
    cycleNote: "Per-programme deadlines mostly Nov-Feb (a few run to June) for September intake.",
    moiAccepted: true,
    moiNote: "English-taught ICP programmes generally accept proof of English-medium instruction (MOI) — Ghanaian applicants commonly qualify this way.",
    englishTests: "IELTS ~6.0-6.5 OR MOI certificate.",
    localLanguageRequired: false,
    localLanguageNote: "All ICP programmes are English-taught; Dutch not required.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Motivation + 2 recommendation letters (scans fine).",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts/certificates accepted; originals on arrival.",
    essayRequired: true,
    essayNote: "Motivation letter tied to development relevance for your home country.",
    applicationSteps: [
      { title: "Choose an ICP Connect programme", detail: "VLIR-UOS funds ~15-20 English-taught master's (water, aquaculture, nutrition, development economics, rural development...) at Flemish universities (Ghent, KU Leuven, Antwerp, VUB...)." },
      { title: "Apply directly to the programme (Nov-Feb)", detail: "Each university hosts its own form — free. Upload scans, references, motivation." },
      { title: "VLIR-UOS selection", detail: "Programmes rank candidates; VLIR-UOS confirms scholarships with attention to country balance and development relevance." },
      { title: "Award & visa (May-Jul)", detail: "Scholarship letter + Belgian student visa (D visa) through the Belgian embassy for Ghana (Accra covers Ghana)." },
    ],
    requirementsSummary: "Free application, scans, 2 letters, MOI often accepted. Development-focused master's in Flanders.",
    eligibilityNote: "29 partner countries in Africa/Asia/Latin America — GHANA IS ON THE LIST.",
    officialUrl: "https://www.vliruos.be/en/scholarships",
    competitiveNote: "Smaller applicant pool than Erasmus Mundus; development-sector work experience boosts you strongly.",
    successTips: "Frame your motivation around a concrete development gap in Ghana the programme addresses — VLIR-UOS exists precisely for that mission.",
  },
  {
    name: "Government of Ireland International Education Scholarship (GOI-IES)",
    kind: "SCHOLARSHIP",
    provider: "Higher Education Authority Ireland",
    country: "Ireland",
    countryCode: "ie",
    continent: "Europe",
    city: "Dublin",
    lat: 53.3498,
    lng: -6.2603,
    levels: ["masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "No application fee for the GOI-IES award.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "€10,000 stipend for one study year + FULL tuition fee waiver + registration contribution waiver (worth €10k-25k on top). 60 awards/year.",
    opensMonth: 11,
    opensDay: 1,
    closesMonth: 3,
    closesDay: 20,
    cycleNote: "Call opens ~November with deadline in March (check the HEA page — exact dates shift yearly).",
    moiAccepted: true,
    moiNote: "Irish universities commonly accept English-medium education (MOI letter) for admission — Ghanaian degrees are widely recognized as English-medium.",
    englishTests: "IELTS 6.5 typical for admission; MOI often accepted.",
    localLanguageRequired: false,
    localLanguageNote: "English only.",
    recommendationsRequired: true,
    recommendationsCount: 1,
    recommendationsNote: "One academic reference + a letter of acceptance from the Irish institution.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans accepted.",
    essayRequired: true,
    essayNote: "A statement of the study plan + how you will promote Ireland's links with Ghana (the scheme is cultural-diplomacy flavoured).",
    applicationSteps: [
      { title: "Secure admission to an eligible Irish institution first", detail: "Apply for your master's/PhD at a participating Irish university (Trinity, UCD, Galway, UCC, DCU...) — admission is a precondition." },
      { title: "Submit the GOI-IES application (Nov-Mar)", detail: "Online via the HEA: scans, reference, acceptance letter, and your personal statement. Free." },
      { title: "HEA shortlisting & interview", detail: "Shortlisted candidates may be interviewed (online) about their study plan and ambassadorial potential." },
      { title: "Award (May-Jun)", detail: "60 laureates get tuition waiver + €10,000 for the academic year." },
    ],
    requirementsSummary: "Irish admission + 1 reference + acceptance letter + scans. Free. €10k + full tuition.",
    eligibilityNote: "Non-EU/EEA students incl. Ghana.",
    officialUrl: "https://hea.ie/policy/internationalisation/",
    competitiveNote: "~60 awards from ~1,500-2,500 applications.",
    successTips: "The statement must balance academic excellence with 'ambassador' potential — how you'll strengthen Ghana-Ireland ties.",
  },
  {
    name: "Swedish Institute Scholarships for Global Professionals (SISGP)",
    kind: "SCHOLARSHIP",
    provider: "Swedish Institute",
    country: "Sweden",
    countryCode: "se",
    continent: "Europe",
    city: "Stockholm",
    lat: 59.3293,
    lng: 18.0686,
    levels: ["masters"],
    fields: ["any", "environment", "engineering", "public policy", "social sciences", "business & economics", "energy"],
    feeAmount: 900,
    feeCurrency: "SEK",
    feeConfirmedFree: false,
    feeNote: "The SISGP scholarship application is free, BUT you first need admission to a Swedish master's, and universityadmissions.se charges a one-time SEK 900 (~$85) application fee for non-EU applicants. Everything after that is free.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full tuition + SEK 12,000/month living + SEK 15,000 travel grant + insurance + membership of the SI Network for Future Global Leaders.",
    opensMonth: 2,
    opensDay: 10,
    closesMonth: 2,
    closesDay: 24,
    cycleNote: "Two-step cycle: university admission round Oct 16 - mid-Jan (SEK 900 fee), then the FREE SISGP scholarship window ~10-24 February.",
    moiAccepted: true,
    moiNote: "Swedish universities are among the most MOI-friendly in Europe: if your Ghanaian bachelor's was taught in English, most universities accept the MOI certificate instead of IELTS (documented per university).",
    englishTests: "IELTS 6.5 (5.5 in parts) OR MOI certificate for English-medium degrees.",
    localLanguageRequired: false,
    localLanguageNote: "Not required — all listed master's are English-taught.",
    recommendationsRequired: false,
    recommendationsNote: "No reference letters at scholarship stage — instead you upload leadership/employment certificates documenting 3,000+ hours of work experience.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts/certificates accepted at both stages.",
    essayRequired: true,
    essayNote: "Motivation answers on leadership and contribution to sustainable development in your home country.",
    applicationSteps: [
      { title: "Apply to Swedish master's (Oct 16 - mid-Jan)", detail: "Via universityadmissions.se — pay the one-time SEK 900 fee, rank up to 4 programmes, upload scans. Choose programmes on the SISGP-eligible list." },
      { title: "Get admission notice (Mar)", detail: "Admission results arrive mid-March — you must hold a place to apply for SISGP... NOTE: SI runs a 'pre-nomination' in Dec-Feb where shortlisted candidates proceed; track SI's announcements." },
      { title: "Submit SISGP application (Feb window)", detail: "Free application: leadership certificates, employer certificates proving 3,000 hours, motivation answers, scans." },
      { title: "SI selection (Apr)", detail: "Scores on work/leadership experience + relevance of the programme to development in Ghana." },
      { title: "Award & arrival (Aug)", detail: "Full package starts with the autumn semester." },
    ],
    requirementsSummary: "3,000 hrs work experience + Swedish admission (SEK 900) + free scholarship application in Feb. MOI widely accepted.",
    eligibilityNote: "Ghana is on the SISGP eligible-country list.",
    officialUrl: "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
    competitiveNote: "~300 awards; leadership evidence outweighs grades.",
    successTips: "Your employer certificates must quantify hours and leadership scope — vague letters sink SISGP applications.",
  },
  {
    name: "Invest Your Talent in Italy",
    kind: "SCHOLARSHIP",
    provider: "Italian Ministry of Foreign Affairs + ICE Agency",
    country: "Italy",
    countryCode: "it",
    continent: "Europe",
    city: "Rome",
    lat: 41.9028,
    lng: 12.4964,
    levels: ["masters"],
    fields: ["engineering", "business & economics", "computer science", "architecture", "design", "energy"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "No application fee — one free application covers the programme admission AND the scholarship.",
    fundingType: "PARTIAL",
    fundingNote: "€900/month grant for 9 months + most partner universities waive tuition for scholarship winners + a 3-month internship with an Italian company.",
    opensMonth: 11,
    opensDay: 15,
    closesMonth: 2,
    closesDay: 28,
    cycleNote: "Applications ~mid-November to end of February for autumn intake.",
    moiAccepted: true,
    moiNote: "Italian partner universities (Bologna, Padua, Trento, Pavia, L'Aquila...) largely accept MOI certificates from English-medium degrees.",
    englishTests: "IELTS 6.0-6.5 or MOI for English-taught programmes.",
    localLanguageRequired: false,
    localLanguageNote: "Programmes are English-taught; free Italian courses are usually offered.",
    recommendationsRequired: false,
    recommendationsNote: "Not required for most partner programmes.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans uploaded to the portal.",
    essayRequired: true,
    essayNote: "Short motivation section in the online form.",
    applicationSteps: [
      { title: "Browse partner universities (Nov)", detail: "The portal lists participating English-taught programmes (engineering, management, design) across Italy." },
      { title: "One free application (Nov 15 - Feb 28)", detail: "Apply via the Invest Your Talent portal — it routes your admission request to chosen universities + the grant application simultaneously." },
      { title: "University admission (Mar-May)", detail: "Universities evaluate and may interview; grant ranking follows admission." },
      { title: "Grant + internship (Sep)", detail: "Winners receive €900/month and are matched to an Italian company internship during/after the programme." },
    ],
    requirementsSummary: "Free application, scans, MOI often accepted, internship built in.",
    eligibilityNote: "Ghana and other non-EU target countries eligible.",
    officialUrl: "https://investyourtalentapplication.esteri.it/",
    competitiveNote: "Hundreds of grants across many partner programmes — better odds than famous-name scholarships.",
    successTips: "Pick 2-3 programmes across different universities — the grant follows admission, so wider choices raise your odds.",
  },
  {
    name: "Open Doors Russian Scholarship Olympiad",
    kind: "SCHOLARSHIP",
    provider: "Russian Ministry of Science & Higher Education",
    country: "Russia",
    countryCode: "ru",
    continent: "Europe",
    city: "Moscow",
    lat: 55.7558,
    lng: 37.6173,
    levels: ["masters", "phd"],
    fields: ["any", "computer science", "mathematics", "natural sciences", "engineering", "medicine & health", "business & economics", "energy"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeNote: "Completely free — registration, olympiad, and the resulting tuition-free place.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Tuition-free state-funded place at ANY of 300+ Russian universities + modest monthly state stipend + free/cheap dormitories. (Living costs are low; some universities add stipends.)",
    opensMonth: 11,
    opensDay: 10,
    closesMonth: 2,
    closesDay: 10,
    cycleNote: "Registration ~10 November - 10 February; first stage online February-March; final stage April.",
    moiAccepted: true,
    moiNote: "NO language certificate required AT ALL to enter the olympiad — the single friendliest entry test worldwide. Olympiad itself is in English.",
    englishTests: "None required to apply or win.",
    localLanguageRequired: false,
    localLanguageNote: "English-taught track available in most subject fields; Russian-taught track includes a free preparatory language year.",
    recommendationsRequired: false,
    recommendationsNote: "No references needed — you qualify purely through the olympiad.",
    unofficialTranscripts: true,
    transcriptsNote: "Simple scans of your diploma/current transcript uploaded at registration.",
    essayRequired: false,
    applicationSteps: [
      { title: "Register free (Nov 10 - Feb 10)", detail: "Sign up at the Open Doors portal with a passport scan + diploma scan. Pick your subject field (physics, CS, economics, biology...)." },
      { title: "First stage — online portfolio quiz (Feb-Mar)", detail: "An online multiple-choice test in English on your field; no proctoring hassles." },
      { title: "Second stage — online problem-solving (Mar-Apr)", detail: "Finalists complete subject tasks (also online) again in English." },
      { title: "Win a state-funded place (May-Jun)", detail: "Winners rank universities; the tuition-free place covers master's (after bachelor's) or PhD admission without entrance exams." },
      { title: "University admission & visa", detail: "Choose your university, complete its simple enrollment, get the invitation letter, and apply for the visa." },
    ],
    requirementsSummary: "Free registration, scans, NO English test, NO references, NO essays — pure online olympiad in English.",
    eligibilityNote: "Open to all foreign citizens (except Russians); Ghana fully eligible.",
    officialUrl: "https://od.globaluni.ru/",
    competitiveNote: "Several thousand participants per field with hundreds of free places — one of the best odds-to-reward ratios anywhere.",
    successTips: "Practice past olympiad papers on the portal — they recycle question styles. CS and physics fields have the most free places.",
  },
  {
    name: "Heinrich Böll Foundation Scholarships",
    kind: "SCHOLARSHIP",
    provider: "Heinrich Böll Foundation (German Green Party affiliate)",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Berlin",
    lat: 52.5323,
    lng: 13.3845,
    levels: ["masters", "phd"],
    fields: ["any", "environment", "social sciences", "public policy", "arts & humanities", "law"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "No application fee — fully online submission.",
    fundingType: "PARTIAL",
    fundingNote: "€992/month + allowances for master's students (PhD: €1,700+), generally 4 semesters. Combined with tuition-free German universities, this is effectively a full ride for living costs.",
    opensMonth: 1,
    opensDay: 1,
    closesMonth: 3,
    closesDay: 1,
    cycleNote: "Two deadlines yearly: 1 March (for studies starting autumn) and 1 September (spring start). Apply ~6-8 weeks early.",
    moiAccepted: true,
    moiNote: "Your university admission language rules apply; MOI letters work for English-taught master's at most German universities.",
    englishTests: "Per your university admission.",
    localLanguageRequired: true,
    localLanguageNote: "German B2 (DSD-2/DSH-2 level proof) is required for most Böll scholarships — this is the key language gate. Plan a German course; Böll values applicants engaged with German society.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two letters of recommendation submitted online by referees.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans of certificates and transcripts uploaded.",
    essayRequired: true,
    essayNote: "Detailed motivation letter + CV showing green/political/social engagement — values fit is decisive.",
    applicationSteps: [
      { title: "Assess the German requirement honestly", detail: "You need certified B2 German before applying. If you don't have it, take Goethe-Institut Accra courses — Böll is best attempted after a year of German study." },
      { title: "Secure German university admission first", detail: "You must already be admitted/enrolled at a German university for master's/PhD." },
      { title: "Submit online dossier (by 1 Mar / 1 Sep)", detail: "Forms, scans, 2 online recommendations, and your political/social engagement record (NGO work, activism, journalism — aligned with green values)." },
      { title: "Selection workshop", detail: "Shortlisted candidates join a virtual selection seminar with interviews and group work." },
      { title: "Award + network", detail: "€992/month + belonging to one of Germany's most politically connected scholarship networks." },
    ],
    requirementsSummary: "German B2 required + university admission + 2 references + strong social/green engagement. Free application.",
    eligibilityNote: "International students in Germany incl. Ghanaians.",
    officialUrl: "https://www.boell.de/en/scholarships",
    competitiveNote: "~1,200 awards across all programs; values-alignment questions dominate interviews.",
    successTips: "Document real civic engagement (climate, gender, democracy work) with specifics — Böll selects people, not just grades.",
  },
  {
    name: "Ghent University BOF Doctoral Scholarships",
    kind: "SCHOLARSHIP",
    provider: "Ghent University Special Research Fund",
    country: "Belgium",
    countryCode: "be",
    continent: "Europe",
    city: "Ghent",
    lat: 51.0543,
    lng: 3.7174,
    levels: ["phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeNote: "No application fee.",
    fundingType: "FULLY_FUNDED",
    fundingNote: "Full PhD salary (~€2,300-2,600 gross/month) + doctoral fee waiver for 2×2-year periods — a full employment contract as a PhD researcher.",
    opensMonth: 1,
    opensDay: 15,
    closesMonth: 3,
    closesDay: 1,
    cycleNote: "Two calls yearly (deadlines ~1 March and ~1 October) — but you must first convince a Ghent professor to host you.",
    moiAccepted: true,
    moiNote: "Ghent research groups operate in English; MOI-backed English is generally fine for PhD supervision.",
    englishTests: "Often not formally required when the supervisor accepts you.",
    localLanguageRequired: false,
    localLanguageNote: "English is the working language of Ghent PhD labs.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Supervisor agreement + academic references in the BOF file.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans accepted in the application file.",
    essayRequired: true,
    essayNote: "Research proposal (with the supervisor) is the core document.",
    applicationSteps: [
      { title: "Find a Ghent promoter (months ahead)", detail: "Email professors whose research matches yours with a 1-page pitch + CV. Their written agreement to supervise is mandatory." },
      { title: "Co-build the BOF proposal (Jan-Feb)", detail: "The supervisor co-authors the research plan with you — this is a joint application." },
      { title: "Submit in the call (1 Mar / 1 Oct)", detail: "Free online submission of the full file." },
      { title: "Expert panel review", detail: "Proposals are scored by external reviewers; top candidates get the 2+2 year contract." },
    ],
    requirementsSummary: "Supervisor agreement + joint proposal + scans. Free. Full PhD salary in Belgium.",
    eligibilityNote: "All nationalities incl. Ghana.",
    officialUrl: "https://www.ugent.be/en/research/funding",
    competitiveNote: "Success tracks with supervisor seniority — pick a professor with recent BOF wins.",
    successTips: "Check Ghent's 'Vacatures' (PhD vacancies) first — funded positions advertised there skip the competitive BOF call entirely.",
  },
];
