import { SeedOpportunity } from "./seed-types";

/**
 * NEW universities — free or ≤$30 confirmed application fees (Europe part 1).
 * Every entry links to the scholarships that can fund studying there.
 */
export const UNIS_EUROPE_1: SeedOpportunity[] = [
  {
    name: "Technical University of Munich (TUM) — $0 Application",
    slug: "tum",
    kind: "UNIVERSITY",
    provider: "TUM School of Management / TUM Graduate School",
    country: "Germany",
    countryCode: "de",
    continent: "Europe",
    city: "Munich",
    lat: 48.149,
    lng: 11.772,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: applying directly via TUMonline costs nothing — TUM does not use uni-assist and charges no application or processing fee.",
    related: ["deutschlandstipendium", "heinrich-boll", "erasmus-mundus"],
    fundingType: "NO_TUITION",
    fundingNote: "No tuition for everyone (incl. internationals) — only the ~€85–150/semester student services fee. Non-EU tuition proposals exist but are NOT currently charged; check the current semester fee page.",
    opensMonth: 1,
    opensDay: 1,
    closesMonth: 5,
    closesDay: 31,
    cycleNote: "Winter intake: apply 1 Jan – 31 May (a few programmes extend to 31 Jul). Summer intake: 1 Sep – 30 Nov. PhD: rolling via open positions.",
    moiAccepted: true,
    moiNote: "English test (IELTS 6.5 / TOEFL 88) is waived when your previous degree was taught entirely in English — a Medium-of-Instruction (MOI) letter from your university is accepted.",
    englishTests: "IELTS 6.5 / TOEFL 88 for English-taught MSc; German B2–C1 (or DSH/TestDaF) for German-taught degrees.",
    localLanguageRequired: false,
    localLanguageNote: "Many English-taught MSc programmes need zero German; most bachelor's tracks are German-taught (B2+). Free German courses run each semester.",
    recommendationsRequired: false,
    recommendationsNote: "Most TUM master's programmes do NOT require recommendation letters — admission is score-based (grade + CV + essay for some schools).",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scanned certificates/transcripts in TUMonline; certified copies are only checked later at enrolment.",
    essayRequired: true,
    essayNote: "TUM School of Management and some MSc programmes require a short motivation essay (1–2 pages).",
    applicationSteps: [
      { title: "Create a TUMonline applicant account", detail: "Register at tumonline.tum.de — it is free. Choose 'Prospective students → Apply' and pick your programme (English-taught list is filterable)." },
      { title: "Prepare your digital document set", detail: "Passport, bachelor certificate + transcript (scanned, English or German translation), CV, MOI letter if waiving IELTS, and the TUM-specific curricular analysis form for some MSc." },
      { title: "Complete the curricular analysis (MSc applicants)", detail: "Many engineering/management MSc ask you to map your undergraduate modules to their module catalogue (Excel form). This replaces interviews and recommendations." },
      { title: "Submit before 31 May (winter intake)", detail: "Upload everything in TUMonline and submit. No fee is charged at any point. You can track status online." },
      { title: "Apply for funding after admission", detail: "With an admission letter, apply for Deutschlandstipendium (€300/month) via TUM's portal, DAAD scholarships, and confirm enrolment (€85 semester fee)." },
    ],
    requirementsSummary: "Free direct application, no recommendations on most MSc, scans accepted at application, MOI letter waives IELTS.",
    eligibilityNote: "Bachelor's from a recognised university with equivalent curriculum; GRE optional for some programmes; work experience not required.",
    officialUrl: "https://www.tum.de/en/studies/application",
    competitiveNote: "Very competitive for CS/management MSc (grade-driven). Less known English MSc tracks (e.g. geodesy, biomedical computing) admit more freely.",
    successTips: "Submit the curricular analysis early and thoroughly — it is the single biggest decision factor for MSc admission. Applying in January beats May: earlier processing and better dorm odds.",
  },
  {
    name: "University of Oslo — $0 Application",
    slug: "university-oslo",
    kind: "UNIVERSITY",
    provider: "University of Oslo (UiO)",
    country: "Norway",
    countryCode: "no",
    continent: "Europe",
    city: "Oslo",
    lat: 59.943,
    lng: 10.719,
    levels: ["masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "NOK",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: UiO charges NO application fee for international master's or PhD applicants.",
    related: ["erasmus-mundus"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Norway introduced tuition for non-EU students (2023): roughly NOK 130,000–550,000/year by programme. Some scholarship schemes and PhD positions (salaried jobs) remain fully funded — PhD is the free route.",
    opensMonth: 10,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 1,
    cycleNote: "International master's applications: ~1 Oct – 1 Dec for the August intake. Verify the exact deadline on each programme page — a few close in November.",
    moiAccepted: false,
    moiNote: "UiO normally requires a formal English test (IELTS 6.5 / TOEFL 90) — MOI letters are rarely accepted; check your programme's exceptions.",
    englishTests: "IELTS 6.5 overall (6.5 writing) / TOEFL iBT 90 for most English master's.",
    localLanguageRequired: false,
    localLanguageNote: "English master's need no Norwegian. Norwegian/Swedish/Danish skills open many more programmes (free language courses offered).",
    recommendationsRequired: false,
    recommendationsNote: "UiO master's applications generally need NO recommendation letters — grades and course descriptions decide.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scanned transcripts + diploma with English translation at application; originals verified only at registration.",
    essayRequired: false,
    applicationSteps: [
      { title: "Browse English master's programmes", detail: "Use uio.no's programme catalogue — filter 'English' and 'master'. Note the special code and requirements of each programme." },
      { title: "Register in Søknadsweb", detail: "UiO's application portal (Søknadsweb) opens 1 Oct. Create an account and apply — there is no fee at any stage." },
      { title: "Upload your document package", detail: "Certified? No — scanned copies are fine at this stage: diploma, transcript (English translation), passport, English test result." },
      { title: "Prepare course descriptions if applying on basis of exemptions", detail: "Detailed syllabi of your relevant undergraduate courses help credit/placement decisions for selective programmes." },
      { title: "Plan financing in parallel", detail: "Show NOK ~137,907/year living funds for the study permit. Explore the Quota successor schemes, Erasmus Mundus routes, or PhD positions (salaried, no tuition)." },
    ],
    requirementsSummary: "No application fee, no recommendations, scans at application; formal English test usually required.",
    eligibilityNote: "Bachelor's degree equivalent to Norwegian cand.mag. (typically 3+ years); some programmes demand a specific subject background.",
    officialUrl: "https://www.uio.no/english/studies/admission/index.html",
    competitiveNote: "Popular programmes (data science, peace studies) are heavily oversubscribed; Nordic/development-adjacent programmes are gentler.",
    successTips: "The PhD route is Norway's real free ticket — doctorates are paid university jobs (NOK 550k+/year). Track UiO job vacancies year-round and apply with a master's + research proposal.",
  },
  {
    name: "Norwegian University of Science & Technology (NTNU) — $0 Application",
    slug: "ntnu",
    kind: "UNIVERSITY",
    provider: "NTNU",
    country: "Norway",
    countryCode: "no",
    continent: "Europe",
    city: "Trondheim",
    lat: 63.419,
    lng: 10.403,
    levels: ["masters", "phd"],
    fields: ["engineering", "natural sciences", "computer science", "environment", "energy"],
    feeAmount: 0,
    feeCurrency: "NOK",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: NTNU charges no application fee for international applicants.",
    related: ["erasmus-mundus"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Non-EU tuition now applies for master's (programme-dependent); PhD positions remain salaried jobs with full benefits — engineering doctorates are NTNU's strongest free-apply channel.",
    opensMonth: 10,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 1,
    cycleNote: "International master's: ~1 Oct – 1 Dec for August intake. PhD positions posted continuously on jobbnorge.no.",
    moiAccepted: false,
    moiNote: "IELTS 6.5 / TOEFL 90 generally required; MOI rarely accepted — confirm on the programme page.",
    englishTests: "IELTS 6.5 / TOEFL iBT 90.",
    localLanguageRequired: false,
    localLanguageNote: "English-taught MSc available in engineering/science; Norwegian B1 needed for some programmes.",
    recommendationsRequired: false,
    recommendationsNote: "No recommendation letters for master's applications — academic record decides.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned documents accepted at application; originals checked at enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Choose 2–3 NTNU master's programmes", detail: "English-taught options concentrate in engineering, marine tech, renewable energy and CS. Each has its own code and subject prerequisites." },
      { title: "Apply free in Søknadsweb (NTNU's portal)", detail: "Open 1 Oct – 1 Dec. No fee. Upload scanned transcripts, diploma, passport and English proof." },
      { title: "Document your subject-specific background", detail: "NTNU is strict on maths/physics credit amounts — include course syllabi if your degree's titles are ambiguous." },
      { title: "Answer the tuition/scholarship section honestly", detail: "Non-EU applicants must show they can fund tuition + living costs for the residence permit unless a scholarship applies." },
      { title: "Separately hunt PhD openings", detail: "Filter jobbnorge.no for 'PhD' + Trondheim; apply with CV, transcripts and a 1-page research statement — salaried (NOK ~560k/year), no tuition, no fee." },
    ],
    requirementsSummary: "No fee, no references, scans fine; English test standard; PhD = paid job route.",
    eligibilityNote: "Relevant bachelor's with strong quantitative content; work experience not required.",
    officialUrl: "https://www.ntnu.edu/",
    competitiveNote: "Marine/renewable MSc competitive; PhD positions depend on the specific project call.",
    successTips: "Email a prospective PhD supervisor with a concrete idea tied to their recent papers — NTNU hiring is supervisor-driven and email outreach works.",
  },
  {
    name: "University of Helsinki — $0 Application",
    slug: "university-helsinki",
    kind: "UNIVERSITY",
    provider: "University of Helsinki",
    country: "Finland",
    countryCode: "fi",
    continent: "Europe",
    city: "Helsinki",
    lat: 60.205,
    lng: 24.962,
    levels: ["masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: Finnish universities charge no application fee — apply free via the national Studyinfo.fi portal.",
    related: ["helsinki-scholarship", "erasmus-mundus"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Non-EU tuition €8,000–18,000/year, BUT the University of Helsinki Scholarship covers 100% or 50% of tuition for admitted fee-payers — apply with the same admission form.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 1,
    closesDay: 14,
    cycleNote: "Master's application window: ~1 Dec – 14 Jan for August intake. Scholarship consideration is inside the same form.",
    moiAccepted: false,
    moiNote: "IELTS 6.5 (no band below 6.0) / TOEFL 92 usually required — MOI waivers are rare at Helsinki.",
    englishTests: "IELTS 6.5 (min 6.0 per band) / TOEFL iBT 92 / PTE 62.",
    localLanguageRequired: false,
    localLanguageNote: "No Finnish needed for English master's; Finnish/Swedish B2 for Finnish-taught degrees.",
    recommendationsRequired: false,
    recommendationsNote: "Most Helsinki master's programmes need no references; a few do — always check the programme page.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned transcripts + diploma uploaded with the application; certified copies only if admitted.",
    essayRequired: true,
    essayNote: "A motivation letter is required by most programmes (1–2 pages, programme-specific questions).",
    applicationSteps: [
      { title: "Shortlist programmes on Studyinfo.fi", detail: "One national portal covers all Finnish universities. Helsinki lists 30+ English master's programmes with scholarship info embedded." },
      { title: "File ONE application listing your programme choices", detail: "You may list up to 2–7 programme preferences depending on faculty — one application, no fee." },
      { title: "Tick the scholarship option", detail: "The application includes the University of Helsinki Scholarship question — select 'yes' to be considered for 100%/50% tuition waiver." },
      { title: "Upload scans before 14 Jan", detail: "Transcript, diploma (or expected graduation certificate), passport, English test, motivation letter." },
      { title: "Handle the admissions examination stage", detail: "Some faculties give alternative admissions tasks (essay/review) instead of requiring tests — treat them as seriously as exams." },
    ],
    requirementsSummary: "Free national portal application, scholarship option built-in, scans accepted, motivation letter central.",
    eligibilityNote: "Relevant bachelor's; some programmes (e.g. neuroscience, atmospheric sciences) expect specific coursework.",
    officialUrl: "https://www.helsinki.fi/en/admissions-and-education",
    competitiveNote: "100% tuition waivers go to top-ranked applicants; 50% waivers are more common.",
    successTips: "Mirror the programme's own learning-outcome wording in your motivation letter — Helsinki readers score against a rubric. Apply on day one of the window.",
  },
  {
    name: "Aalto University — $0 Application",
    slug: "aalto-university",
    kind: "UNIVERSITY",
    provider: "Aalto University",
    country: "Finland",
    countryCode: "fi",
    continent: "Europe",
    city: "Espoo",
    lat: 60.187,
    lng: 24.832,
    levels: ["masters", "phd"],
    fields: ["engineering", "business & economics", "arts & humanities", "computer science", "energy"],
    feeAmount: 0,
    feeCurrency: "EUR",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: no application fee via Studyinfo.fi.",
    related: ["erasmus-mundus"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Non-EU tuition €8,000–15,000/year. The Aalto Scholarship waives 50% or 100% of tuition for admitted fee-paying students (decided at admission).",
    opensMonth: 11,
    opensDay: 28,
    closesMonth: 1,
    closesDay: 14,
    cycleNote: "Master's window ~late Nov – mid Jan. PhD applications go directly to doctoral programmes year-round.",
    moiAccepted: false,
    moiNote: "English test standard (IELTS 6.5 / TOEFL 92); MOI rarely accepted.",
    englishTests: "IELTS 6.5 (writing 5.5) / TOEFL iBT 92 / PTE-A 62.",
    localLanguageRequired: false,
    localLanguageNote: "English MSc across art+tech+business; Finnish B2 for Finnish-taught.",
    recommendationsRequired: false,
    recommendationsNote: "Generally no references for master's; design programmes use portfolios instead.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans at application; originals at enrolment.",
    essayRequired: true,
    essayNote: "Motivation letter required; Art & Design additionally requires a portfolio.",
    applicationSteps: [
      { title: "Explore Aalto's 50+ English master's programmes", detail: "Cross-disciplinary options (e.g. Creative Sustainability, ICT Innovation) accept many backgrounds — check each programme's eligible degrees list." },
      { title: "Apply once via Studyinfo.fi", detail: "One application, up to 2 programme preferences at Aalto, zero fee." },
      { title: "Request the Aalto Scholarship in the same form", detail: "The tuition-waiver question is embedded — 50% or 100% off non-EU tuition, decided with admission." },
      { title: "Upload documents + letter/portfolio", detail: "Scans are fine: transcript, diploma or expected-graduation certificate, English proof, motivation letter, portfolio where relevant." },
      { title: "Secure living funds for the permit", detail: "Show ~€800/month (Finnish requirement) for the residence permit; Helsinki dorm queues are long — apply to HOAS/Domo immediately after admission." },
    ],
    requirementsSummary: "Free application, embedded tuition-waiver scholarship, scans OK, portfolio for design.",
    eligibilityNote: "Relevant bachelor's; business programmes like quantitative backgrounds.",
    officialUrl: "https://www.aalto.fi/en/study-at-aalto",
    competitiveNote: "Aalto's design/CS programmes are Finland's most selective; engineering tracks admit more openly.",
    successTips: "For ICT Innovation you can pick a second-year European partner university — a cheap path to two countries. Apply early; Aalto processes first-come.",
  },
  {
    name: "EPFL — CHF 10 Application (~$11)",
    slug: "epfl",
    kind: "UNIVERSITY",
    provider: "École Polytechnique Fédérale de Lausanne",
    country: "Switzerland",
    countryCode: "ch",
    continent: "Europe",
    city: "Lausanne",
    lat: 46.522,
    lng: 6.566,
    levels: ["masters", "phd"],
    fields: ["engineering", "computer science", "natural sciences", "mathematics", "energy"],
    feeAmount: 10,
    feeCurrency: "CHF",
    feeConfirmedFree: false,
    feeUsdApprox: 11,
    feeNote: "Confirmed: EPFL's application fee is CHF 10 (~$11) — one of Europe's lowest, charged once per application (up to 2 programme choices).",
    related: ["swiss-excellence"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Tuition CHF 780/semester (≈$870) — very low for Europe. Swiss Government Excellence fellowships + EPFL Excellence fellowships cover masters/PhD costs.",
    opensMonth: 11,
    opensDay: 1,
    closesMonth: 12,
    closesDay: 15,
    cycleNote: "Master's applications: ~1 Nov – 15 Dec for September intake. PhD: rolling — apply to posted doctoral positions anytime.",
    moiAccepted: true,
    moiNote: "English test (IELTS 7.0 / C1) is waived if your previous degree was taught fully in English — MOI certificate accepted.",
    englishTests: "IELTS 7.0 / TOEFL 95 (C1) for English-taught MSc; French CEFR B2 for French-taught sections.",
    localLanguageRequired: false,
    localLanguageNote: "Most EPFL master's are English-taught; daily life works in English; free French classes offered.",
    recommendationsRequired: true,
    recommendationsCount: 2,
    recommendationsNote: "Two referees submit contact details in the application — EPFL emails them directly for letters.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scans of transcripts + diplomas; attested copies needed only at registration.",
    essayRequired: false,
    applicationSteps: [
      { title: "Register on the EPFL admissions portal (isacademia)", detail: "Choose up to 2 master's programmes; pay the CHF 10 fee by card — total cost to apply stays under $12." },
      { title: "Enter two referees", detail: "EPFL contacts them directly — warn your referees in advance so letters arrive before 15 Dec." },
      { title: "Upload the document set", detail: "Scanned transcripts (all years), diplomas, passport, MOI/English certificate, CV. No motivation letter for most programmes — the file speaks." },
      { title: "Meet the 15 Dec deadline", detail: "Late files are not reviewed. Results come Feb–Mar." },
      { title: "Stack funding once admitted", detail: "Combine the (low) tuition with Excellence fellowships, Swiss Excellence Scholarship (PhD), or paid research assistantships at labs." },
    ],
    requirementsSummary: "CHF 10 fee, 2 recommendations, scans accepted, MOI waiver for English-medium degrees.",
    eligibilityNote: "Bachelor's in a comparable field with excellent grades; EPFL screens against a grade threshold.",
    officialUrl: "https://www.epfl.ch/education/studies/en/",
    competitiveNote: "CS/robotics MSc very selective; less-known sections (chemistry, environmental eng.) admit more freely.",
    successTips: "Because EPFL weighs grades above all, attach course descriptions that prove equivalence to EPFL's BSc — it prevents rejection-by-administration.",
  },
  {
    name: "Czech Technical University in Prague (CTU) — CZK 500 (~$21)",
    slug: "ctu-prague",
    kind: "UNIVERSITY",
    provider: "České vysoké učení technické (CTU)",
    country: "Czech Republic",
    countryCode: "cz",
    continent: "Europe",
    city: "Prague",
    lat: 50.102,
    lng: 14.391,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["engineering", "computer science", "natural sciences", "architecture & design", "energy"],
    feeAmount: 500,
    feeCurrency: "CZK",
    feeConfirmedFree: false,
    feeUsdApprox: 21,
    feeNote: "Confirmed: application fee CZK 500 (~$21) per programme — payable by card in the CTU application portal.",
    related: ["erasmus-mundus"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Czech-taught degrees are tuition-free; English programmes cost ~€2,000–6,000/year. PhD stipends + fee waivers exist for strong candidates.",
    opensMonth: 11,
    opensDay: 1,
    closesMonth: 2,
    closesDay: 28,
    cycleNote: "Applications typically 1 Nov – Feb/Mar (deadlines vary by faculty) for September intake.",
    moiAccepted: true,
    moiNote: "Many CTU faculties accept proof of previous English-medium study (MOI letter) instead of IELTS — confirm with your faculty admissions office.",
    englishTests: "IELTS 5.0–6.5 or B2 certificate or MOI letter, depending on faculty.",
    localLanguageRequired: false,
    localLanguageNote: "Czech-taught = free tuition; English tracks need no Czech. One-year Czech prep course available.",
    recommendationsRequired: false,
    recommendationsNote: "No recommendation letters — faculty entrance exams or grade screening decide.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scans; notarised copies required only at enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Pick your faculty + programme", detail: "CTU has 8 faculties (FIT, FEL, FS, FCE…). English degree finder lists each with fees and deadlines." },
      { title: "Register and pay CZK 500 in the online portal", detail: "The fee is per programme; paying unlocks the upload area." },
      { title: "Upload scans: diploma, transcript, passport", detail: "No attestation needed yet. Add MOI letter if waiving the English test." },
      { title: "Sit the entrance exam (if required)", detail: "Some faculties test maths/physics online or accept grades outright — check your programme's 'admission procedure' PDF." },
      { title: "Confirm + enrol, then apply for accommodation", detail: "CTU dorms are cheap (~€150/month); international office helps with visa invitation letters." },
    ],
    requirementsSummary: "CZK 500 (~$21) fee, no references, scans fine, MOI often accepted, exams for some faculties.",
    eligibilityNote: "Recognised secondary/bachelor certificate with relevant subjects; technical faculties check maths proficiency.",
    officialUrl: "https://www.cvut.cz/en",
    competitiveNote: "Less competitive than Western Europe for equivalent quality; FIT/FEL CS programmes popular but not oversubscribed.",
    successTips: "Apply to two programmes to double your odds for a single CZK 1,000 (~$42) total spend. Czech-taught route = free tuition if you commit to a year of Czech prep.",
  },
  {
    name: "Masaryk University Brno — CZK 500 (~$21)",
    slug: "masaryk-university",
    kind: "UNIVERSITY",
    provider: "Masarykova univerzita (MUNI)",
    country: "Czech Republic",
    countryCode: "cz",
    continent: "Europe",
    city: "Brno",
    lat: 49.202,
    lng: 16.611,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 500,
    feeCurrency: "CZK",
    feeConfirmedFree: false,
    feeUsdApprox: 21,
    feeNote: "Confirmed: application fee CZK 500 (~$21) for most programmes (a few CZK 990). Paid once per application.",
    related: ["erasmus-mundus"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Czech-taught = free; English programmes ~€2,000–5,000/year. MUNI offers tuition discounts and CEITEC PhD stipends.",
    opensMonth: 11,
    opensDay: 1,
    closesMonth: 4,
    closesDay: 30,
    cycleNote: "Window 1 Nov – Feb/Apr (faculty-dependent) for September intake.",
    moiAccepted: true,
    moiNote: "Several faculties waive English certificates with an MOI letter or a Skype interview — stated per programme in the e-application.",
    englishTests: "B2 certificate (IELTS ~6.0) or equivalent/MOI per programme.",
    localLanguageRequired: false,
    localLanguageNote: "Czech for Czech-taught; English degrees need none.",
    recommendationsRequired: false,
    recommendationsNote: "Generally not required at application.",
    unofficialTranscripts: true,
    transcriptsNote: "Scans at application; certified later.",
    essayRequired: false,
    applicationSteps: [
      { title: "Search MUNI's English catalogue", detail: "60+ English degrees across informatics, social studies, natural sciences, medicine." },
      { title: "Fill the e-application and pay CZK 500", detail: "Card payment; fee covers one programme." },
      { title: "Upload scanned documents", detail: "Transcript, certificate, passport, language proof or MOI letter." },
      { title: "Attend the entrance interview/exam", detail: "Many master's use online interviews; some use written tests. Questions are published in advance in admission criteria." },
      { title: "Apply for MUNI housing + visa", detail: "Brno dorms ~€120–200/month; the university issues visa confirmation letters quickly." },
    ],
    requirementsSummary: "CZK 500 fee, no references, MOI often accepted, interviews common.",
    eligibilityNote: "Programme-specific prerequisites; medicine has its own entrance exam.",
    officialUrl: "https://www.muni.cz/en",
    competitiveNote: "Moderate; informatics and CEITEC life-sciences tracks are the strongest.",
    successTips: "Read each faculty's published 'admission criteria' PDF — it literally lists interview questions themes. MUNI is friendlier to non-EU applicants than Prague schools.",
  },
];
