import { SeedOpportunity } from "./seed-types";

/** NEW universities — free or ≤$30 confirmed application fees (Americas + Asia part 1). */
export const UNIS_WORLD_1: SeedOpportunity[] = [
  {
    name: "Berea College — $0 Application + No-Tuition Promise",
    slug: "berea-college",
    kind: "UNIVERSITY",
    provider: "Berea College, Kentucky",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Berea, KY",
    lat: 37.576,
    lng: -84.296,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: $0 application fee — and every admitted student (international included) receives the No-Tuition Promise worth >$200,000 over 4 years.",
    related: ["common-app-waiver"],
    fundingType: "FULLY_FUNDED",
    fundingNote: "No-Tuition Promise covers full tuition; every international student also gets a ≥$1,000/year job on campus + housing/meals support. Only personal/travel costs remain.",
    opensMonth: 8,
    opensDay: 1,
    closesMonth: 11,
    closesDay: 30,
    cycleNote: "International applications: ~1 Aug – 30 Nov for August entry. After 30 Nov, contact admissions — later rounds depend on space.",
    moiAccepted: true,
    moiNote: "English proficiency may be waived for applicants from English-medium education systems (incl. Ghana) — counselor letter confirming English-medium schooling accepted.",
    englishTests: "TOEFL/IELTS/Duolingo accepted when required; waiver possible with English-medium schooling proof.",
    localLanguageRequired: false,
    localLanguageNote: "English medium throughout.",
    recommendationsRequired: true,
    recommendationsCount: 3,
    recommendationsNote: "Counselor report + 2 teacher recommendations — standard US college set.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned national exam results (e.g. WASSCE) + school transcript accepted for review; originals verified later.",
    essayRequired: true,
    essayNote: "Personal essays via Berea's own application — focus on service, resilience, and financial-need context.",
    applicationSteps: [
      { title: "Confirm you fit the mission", detail: "Berea admits academically strong students with demonstrated financial need who couldn't otherwise afford US college — say so plainly in your essays." },
      { title: "Use Berea's own free application (not Common App)", detail: "Apply at berea.edu/admissions — no fee ever, no Common App account needed." },
      { title: "Send scans + 3 recommendations by 30 Nov", detail: "WASSCE results slip (if Ghanaian), school transcript, counselor + 2 teacher letters, English-proof or waiver letter." },
      { title: "Complete the financial documentation", detail: "Submit the International Financial Aid form honestly — need is an admission PLUS here, not a weakness." },
      { title: "Apply for the student visa with the I-20", detail: "Berea issues the I-20; pay only the SEVIS + visa appointment fees (the real costs of entry, ~$510 total)." },
    ],
    requirementsSummary: "Genuinely $0 to apply, full-tuition promise, jobs on campus, need-friendly admissions.",
    eligibilityNote: "Strong academics + financial need; admits ~30 internationals/year from ~70 countries; Ghana consistently represented.",
    officialUrl: "https://admissions.berea.edu/",
    competitiveNote: "Selective but need-aware in your favor — great fit beats perfect stats.",
    successTips: "This is the single best $0-to-apply deal in the USA for African undergrads. Apply by October, not November — early files get the first admission committee reads.",
  },
  {
    name: "MIT — $0 PhD Application (most departments)",
    slug: "mit-phd",
    kind: "UNIVERSITY",
    provider: "Massachusetts Institute of Technology",
    country: "United States",
    countryCode: "us",
    continent: "North America",
    city: "Cambridge, MA",
    lat: 42.36,
    lng: -71.092,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["engineering", "computer science", "natural sciences", "mathematics", "business & economics", "medicine & health"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: most MIT doctoral programmes charge NO application fee (e.g. EECS explicitly states no fee). Undergrad is $75 but automatic fee waivers exist for eligible students.",
    related: ["us-phd-fee-waivers", "fulbright-ghana"],
    fundingType: "FULLY_FUNDED",
    fundingNote: "All MIT PhD admits get full funding: tuition, stipend (~$4,500+/month) and health insurance via RA/TA/fellowship. Undergrad aid meets 100% of demonstrated need.",
    opensMonth: 9,
    opensDay: 15,
    closesMonth: 12,
    closesDay: 15,
    cycleNote: "PhD applications: mid-Sep – 1–15 Dec (department-specific) for fall entry. Undergrad: Nov 1 (Early Action) / Jan 1 (Regular).",
    moiAccepted: true,
    moiNote: "English test may be waived for applicants whose instruction language was English — MIT accepts TOEFL/IELTS/Duolingo or a waiver where the department allows; check your department's grad FAQ.",
    englishTests: "TOEFL 90+ / IELTS 7.0+ (some departments 100+); waived case-by-case with English-medium degrees.",
    localLanguageRequired: false,
    localLanguageNote: "English medium.",
    recommendationsRequired: true,
    recommendationsCount: 3,
    recommendationsNote: "3 letters standard for PhD (research-focused); UG uses 2 teacher + counselor reports.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload unofficial scanned transcripts for review; official copies only after admission.",
    essayRequired: true,
    essayNote: "Statement of objectives (PhD) / essays (UG) — MIT reads for research fit and impact.",
    applicationSteps: [
      { title: "Shortlist departments + professors", detail: "MIT admission is department-level. Read 3–5 faculty pages and name research intersections in your statement." },
      { title: "Create the application account and confirm the $0 fee", detail: "Most engineering/science PhD apps show no fee at submission — if a department charges, email the grad office; waivers are routine." },
      { title: "Upload unofficial transcripts + 3 letters", detail: "Scans fine at review. Choose referees who supervised actual research, not just good grades." },
      { title: "Write a research-anchored statement of objectives", detail: "2 pages: problem you care about, what you built/measure, which MIT groups you'd join and why." },
      { title: "Undergrad route: use the fee waiver", detail: "Applicants who qualify for SAT waivers or economic need get the $75 fee waived automatically — request it in the application, no documents drama." },
    ],
    requirementsSummary: "PhD = no fee + full funding; UG = fee waiver; scans accepted; research fit decides.",
    eligibilityNote: "Exceptional academic record + research experience (publications not mandatory but projects/theses matter).",
    officialUrl: "https://gradadmissions.mit.edu/",
    competitiveNote: "Ultra-competitive; but the $0 fee removes all financial excuse to try — apply across several MIT departments where fit exists.",
    successTips: "Ghanaians/other internationals: email 2–3 professors in September with a specific idea referencing their latest paper — a warm faculty reply materially lifts your file in committee.",
  },
  {
    name: "University of São Paulo (USP) — R$0 Application",
    slug: "usp-brazil",
    kind: "UNIVERSITY",
    provider: "Universidade de São Paulo",
    country: "Brazil",
    countryCode: "br",
    continent: "South America",
    city: "São Paulo",
    lat: -23.561,
    lng: -46.656,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "BRL",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: no application fee; USP is a tuition-free public university.",
    related: [],
    fundingType: "NO_TUITION",
    fundingNote: "Zero tuition at all levels. International UG entry via PEC-G agreement (includes free Portuguese prep year); graduate fellowships (CAPES/FAPESP) pay stipends.",
    opensMonth: 7,
    opensDay: 1,
    closesMonth: 9,
    closesDay: 30,
    cycleNote: "PEC-G (undergraduate): applications ~Jul–Sep each year. Graduate (mestrado/doutorado): rolling per programme, usually Feb–Apr and Aug–Oct windows.",
    moiAccepted: false,
    moiNote: "Not applicable — instruction is in Portuguese; PEC-G includes a 1-year free Portuguese course (CELPE-Bras pathway).",
    englishTests: "Not required; Portuguese proficiency is the gate (CELPE-Bras intermediate for direct entry or via PEC-G prep year).",
    localLanguageRequired: true,
    localLanguageNote: "Portuguese B1–B2 required; PEC-G students get a fully-funded language year at a partner university first.",
    recommendationsRequired: false,
    recommendationsNote: "Undergrad PEC-G: no letters. Graduate: supervisor acceptance letter is the key document.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned, translated documents accepted at application; sworn translations validated later.",
    essayRequired: false,
    applicationSteps: [
      { title: "Register for PEC-G through Brazil's MEC portal", detail: "PEC-G = Programa de Estudantes-Convênio de Graduação — Ghana has an agreement; apply via the Brazilian embassy in Accra + MEC system (Jul–Sep)." },
      { title: "Submit scanned, translated documents", detail: "WASSCE certificate + transcript translated to Portuguese (sworn translation) — start translation early." },
      { title: "Get selected + complete the free Portuguese year", detail: "Successful PEC-G candidates study Portuguese tuition-free (CEPE) before degree entry." },
      { title: "Take USP's entrance route (FUVEST or transfer exam)", detail: "After the language year, sit FUVEST or the international-student exam — free to register for PEC-G holders." },
      { title: "Graduate route: email a supervisor directly", detail: "For mestrado/doutorado, secure an adviser's acceptance letter, then apply to the programme with CAPES/FAPESP stipend options (R$ 2,500–7,000/month)." },
    ],
    requirementsSummary: "R$0 fees, free tuition, PEC-G path with free language year, graduate stipends.",
    eligibilityNote: "PEC-G: completed secondary school, under ~25–27 preferred, from a signatory country (Ghana eligible).",
    officialUrl: "https://internationaloffice.usp.br/",
    competitiveNote: "Low international competition — Brazilians mostly compete among themselves; a solid WASSCE file stands out.",
    successTips: "Almost nobody in West Africa applies to Brazil — that's your arbitrage. PEC-G + free Portuguese year + free degree costs $0 end-to-end except flights.",
  },
  {
    name: "University of Buenos Aires (UBA) — $0 Application",
    slug: "uba-argentina",
    kind: "UNIVERSITY",
    provider: "Universidad de Buenos Aires",
    country: "Argentina",
    countryCode: "ar",
    continent: "South America",
    city: "Buenos Aires",
    lat: -34.601,
    lng: -58.44,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 0,
    feeCurrency: "USD",
    feeConfirmedFree: true,
    feeUsdApprox: 0,
    feeNote: "Confirmed: free application and free tuition for internationals — one of the world's largest cost-free universities.",
    related: [],
    fundingType: "NO_TUITION",
    fundingNote: "No tuition at UBA for any student. Costs: Spanish prep (~$100–300/month courses) + living in Buenos Aires.",
    rolling: true,
    cycleNote: "Rolling enrolment: Spanish certification + the Ciclo Básico Común (CBC) entry cycle can start at multiple points year-round.",
    moiAccepted: false,
    moiNote: "Not applicable — Spanish is required for almost all degrees.",
    englishTests: "Not required; Spanish B2+ needed.",
    localLanguageRequired: true,
    localLanguageNote: "Spanish proficiency essential; UBA's Centro Universitario de Idiomas offers affordable courses from total-beginner level.",
    recommendationsRequired: false,
    recommendationsNote: "No letters for UG; graduate programmes vary by faculty.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned, apostilled documents at enrolment; digital submission accepted initially.",
    essayRequired: false,
    applicationSteps: [
      { title: "Start Spanish now (this is the whole game)", detail: "Reach B1–B2 via local institutes or online; UBA's CUI offers semester courses with certificates." },
      { title: "Legalise (apostille) your certificates", detail: "WASSCE/degree documents need apostille or Argentine consulate legalisation — process this at home before travelling." },
      { title: "Choose CBC route (UG) or direct graduate entry", detail: "UG: enrol in the Ciclo Básico Común (6-subject intro cycle) for your faculty — open admission once documents are ready." },
      { title: "Register as a foreign student at UBA", detail: "Free registration via the international students office; residency paperwork supported with a student visa (temporary residence for study)." },
      { title: "Budget the real costs", detail: "Tuition $0; living ~$450–700/month in Buenos Aires; many students work part-time legally on student residency." },
    ],
    requirementsSummary: "Genuinely $0 everywhere; the filter is Spanish proficiency + apostilled documents.",
    eligibilityNote: "Completed secondary education; no age limits; open admission structure via CBC.",
    officialUrl: "https://www.uba.international/",
    competitiveNote: "Not competitive — capacity-open; persistence with language + paperwork wins.",
    successTips: "Argentina's economic situation makes living costs very low for dollar holders. Pair UBA with Ghana Secretariat or home-country funding for living costs — tuition is already $0.",
  },
  {
    name: "National University of Singapore (NUS) — S$20 Undergrad Application (~$15)",
    slug: "nus-singapore",
    kind: "UNIVERSITY",
    provider: "National University of Singapore",
    country: "Singapore",
    countryCode: "sg",
    continent: "Asia",
    city: "Singapore",
    lat: 1.297,
    lng: 103.774,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 20,
    feeCurrency: "SGD",
    feeConfirmedFree: false,
    feeUsdApprox: 15,
    feeNote: "Confirmed: S$20 (~$15) undergraduate application fee. Graduate admission fees are higher (S$50–100) — this entry covers the UG route.",
    related: ["singa"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Non-subsidised tuition is high, BUT the MOE Tuition Grant subsidises it heavily in exchange for a 3-year work stint in Singapore. Need-based bursaries + scholarships stack on top.",
    opensMonth: 10,
    opensDay: 1,
    closesMonth: 3,
    closesDay: 3,
    cycleNote: "International UG applications: ~Oct – early Mar. Some quotas close early — file by November for best chances.",
    moiAccepted: true,
    moiNote: "Applicants from English-medium schooling (incl. Ghanaian WASSCE background) are usually exempt from TOEFL/IELTS — NUS reviews case-by-case.",
    englishTests: "IELTS/TOEFL only if your schooling language wasn't English.",
    localLanguageRequired: false,
    localLanguageNote: "English medium; mother-tongue requirements waived for international students.",
    recommendationsRequired: false,
    recommendationsNote: "Not required for most programmes; some scholarships ask for one later.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload WASSCE/school results + transcripts; originals verified at enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Apply in the international applicants portal (S$20)", detail: "Choose up to programme preferences; pay S$20 by card — total cost of trying stays ~$15." },
      { title: "Upload WASSCE + transcripts", detail: "Scans accepted. Include school profile if available." },
      { title: "WASSCE-specific step", detail: "NUS evaluates WASSCE results; strong A1s in maths/science matter for CS/engineering. Some faculties may set an entrance test/interview." },
      { title: "Check Tuition Grant obligation before accepting", detail: "The MOE Tuition Grant cuts tuition ~60–70% but binds you to 3 years working in Singapore after graduation — sign knowingly." },
      { title: "Apply for bursaries/scholarships after admission", detail: "NUS Global Merit, science & tech awards, and need bursaries are applied for with your admission ID." },
    ],
    requirementsSummary: "S$20 fee, WASSCE evaluated directly, Tuition Grant cuts cost massively, English waiver likely for Ghanaians.",
    eligibilityNote: "Excellent national exam results; competitive STEM programmes expect top grades.",
    officialUrl: "https://www.nus.edu.sg/admissions",
    competitiveNote: "Highly competitive for CS/business; quieter routes exist in less-hyped faculties.",
    successTips: "The Tuition Grant is the real scholarship — a 3-year work bond in a country with graduate salaries ~S$4,000+/month is a strong deal. Apply in October.",
  },
  {
    name: "Nanyang Technological University (NTU) — S$10 Undergrad Application (~$8)",
    slug: "ntu-singapore",
    kind: "UNIVERSITY",
    provider: "Nanyang Technological University",
    country: "Singapore",
    countryCode: "sg",
    continent: "Asia",
    city: "Singapore",
    lat: 1.348,
    lng: 103.683,
    levels: ["undergraduate"],
    fields: ["any"],
    feeAmount: 10,
    feeCurrency: "SGD",
    feeConfirmedFree: false,
    feeUsdApprox: 8,
    feeNote: "Confirmed: S$10 (~$8) application fee for international undergraduates — the cheapest branded-university application on Earth.",
    related: ["singa"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Same MOE Tuition Grant system as NUS: ~60–70% tuition subsidy with a 3-year Singapore work bond; NTU scholarships (e.g. Nanyang Scholarship) then cover the rest.",
    opensMonth: 10,
    opensDay: 1,
    closesMonth: 3,
    closesDay: 1,
    cycleNote: "International UG window ~Oct – Feb/Mar depending on programme.",
    moiAccepted: true,
    moiNote: "English-medium schooling (Ghana included) typically exempts you from IELTS/TOEFL.",
    englishTests: "Only if prior schooling wasn't in English.",
    localLanguageRequired: false,
    localLanguageNote: "English medium.",
    recommendationsRequired: false,
    recommendationsNote: "Not required.",
    unofficialTranscripts: true,
    transcriptsNote: "Scanned results accepted; verification at enrolment.",
    essayRequired: false,
    applicationSteps: [
      { title: "Apply via NTU international portal (S$10)", detail: "One of the world's lowest application fees; card payment inside the portal." },
      { title: "Upload WASSCE/national results + transcripts", detail: "Scans fine at application stage." },
      { title: "Indicate scholarship interest", detail: "NTU screens admitted internationals for Nanyang/College scholarships automatically — strong files get invited." },
      { title: "Accept Tuition Grant terms if offered", detail: "Understand the 3-year work bond before signing — it's the mechanism that makes NTU affordable." },
      { title: "Visa (Student's Pass) via ICA SOLAR+", detail: "NTU sponsors the Student's Pass; apply as soon as the offer lands." },
    ],
    requirementsSummary: "S$10 fee, WASSCE accepted, scholarships auto-screened, Tuition Grant pathway.",
    eligibilityNote: "Top national-exam grades; engineering/CS most competitive.",
    officialUrl: "https://www.ntu.edu.sg/admissions",
    competitiveNote: "Competitive but S$10 makes trying free-ish — apply alongside NUS.",
    successTips: "Apply to BOTH NUS (S$20) and NTU (S$10) for under $25 total. NTU's engineering reputation is on par with NUS at slightly lower competition.",
  },
  {
    name: "Universiti Malaya (UM) — RM 100 Application (~$22)",
    slug: "universiti-malaya",
    kind: "UNIVERSITY",
    provider: "Universiti Malaya (UM)",
    country: "Malaysia",
    countryCode: "my",
    continent: "Asia",
    city: "Kuala Lumpur",
    lat: 3.12,
    lng: 101.655,
    levels: ["undergraduate", "masters", "phd"],
    fields: ["any"],
    feeAmount: 100,
    feeCurrency: "MYR",
    feeConfirmedFree: false,
    feeUsdApprox: 22,
    feeNote: "Confirmed: ~RM100 (~$22) application processing fee for international applicants (varies slightly by programme).",
    related: ["mis-malaysia", "mtcp"],
    fundingType: "SELF_FUNDED",
    fundingNote: "Tuition low: UG ~RM 8,000–20,000/year, master's ~RM 12,000–30,000 total. MIS (Malaysia International Scholarship) covers tuition + RM 3,500/month stipend.",
    opensMonth: 12,
    opensDay: 1,
    closesMonth: 6,
    closesDay: 30,
    cycleNote: "September intake: applications ~Dec – Jun. February intake (some programmes): Sep – Nov.",
    moiAccepted: true,
    moiNote: "UM commonly accepts a Medium-of-Instruction letter instead of IELTS for applicants from English-medium systems — Ghanaians regularly use this route; confirm with the faculty.",
    englishTests: "IELTS 5.5–6.5 / TOEFL / MUET — or MOI letter where accepted.",
    localLanguageRequired: false,
    localLanguageNote: "English medium for most international degrees; Bahasa for some programmes.",
    recommendationsRequired: false,
    recommendationsNote: "UG: no letters. Postgrad research: a supervisor's consent letter helps hugely.",
    unofficialTranscripts: true,
    transcriptsNote: "Upload scanned certificates + transcripts; originals on arrival.",
    essayRequired: false,
    applicationSteps: [
      { title: "Register at UM's international admission portal", detail: "Choose degree level → programme; the system lists the exact RM fee for your selection." },
      { title: "Pay RM 100 and upload scans", detail: "Certificate, transcript, passport page, language proof (or MOI letter)." },
      { title: "Postgrad research: contact a supervisor first", detail: "Email potential supervisors your CV + proposal summary — their consent letter accelerates everything." },
      { title: "Get the offer + EMGS visa process", detail: "UM routes your student pass via EMGS (Education Malaysia); pay the visa processing (~RM 1,000+) once, after the offer." },
      { title: "Apply for MIS/MTCP funding", detail: "With the UM offer (or in parallel), apply for Malaysia International Scholarship / MTCP — full tuition + RM 3,500/month." },
    ],
    requirementsSummary: "RM 100 fee, MOI accepted broadly, supervisor-led postgrad, MIS/MTCP funding stack.",
    eligibilityNote: "UG via WASSCE/A-levels equivalence; master's need a relevant bachelor's; PhD needs proposal.",
    officialUrl: "https://www.um.edu.my/",
    competitiveNote: "Moderate; UM is Malaysia's #1 but far less saturated than UK/US peers.",
    successTips: "Malaysia is the best-value English-medium option for Ghanaians: ~$22 to apply, MOI waivers, $0-cost MIS scholarship covering everything. Apply Dec–Feb for the best funding window.",
  },
];
